Mergifyio/mergify

- default_rule.yml
- doc/source/configuration.rst
Github doc say null, but that doesn't disable the flag, while false
works.
> enforce_admins should be false, not none

- mergify_engine/engine.py
- mergify_engine/gh_pr.py
- mergify_engine/gh_pr_fullifier.py
This implements a new field called `base_is_modifiable` which shows if the base
of a PR can be modified for the strict workflow. The current field provided by
GitHub does not cover the case where the base branch comes from the same repo
than the target branch, and not from a fork — see #51. This should fix it.
Fixes #51
> Do not only trust GitHub maintainer_can_modify field

- mergify_engine/engine.py
- mergify_engine/gh_pr_fullifier.py
- mergify_engine/tests/test_engine.py
- setup.cfg
It does not seem like GitHub cares about negative review, so it's likely
Mergify should do the same by default. Another option could be added to not
block merge on negative reviews.
Also, send a better description on the number of approval that Mergify is
waiting for.
> Change approved computing to ignore negative, improve reporting

- mergify_engine/engine.py
We currently post status "Merged", do backports and delete backport
branches each times we receive an event for a closed pull request.
We should do them only when the PR have just been merged and not
for status event that could come after.
Closes #80
> Create backport and close status only when PR is closed

- mergify_engine/engine.py
- mergify_engine/gh_pr.py
- mergify_engine/gh_pr_fullifier.py
- mergify_engine/static/table.html
- mergify_engine/tests/test_engine.py
This change reworks the statuses checker to just track if all required
statuses succeed or not.
This also adds a small behavior change to match how context work at
Github.
When you put "continuous-integration" as context, this means Github
requires all statuses with the context starting with
"continuous-integration/"
We was doing an exact match before. Now we use "startswith(...)" like
Github does.
> Rework status checks

- mergify_engine/worker.py
When an installation remove the access_token, we got some 401 in logs.
This change replace the backtrace by an error message.
> Don't throw backtrace on 401

- fake.yml
- mergify_engine/engine.py
- mergify_engine/tests/test_engine.py
- mergify_engine/utils.py
- mergify_engine/web.py
- mergify_engine/worker.py
- run-tests.sh
- setup.cfg
This change allows to spawn multiple workers.
For now, all events for a repository should go in order to
the same worker.
This change uses a static hashring to describe all
workers/queues we can use to do that.
Each worker now have two queues, one for account with subscription
and one for free account.
> Allow to spawn multiple workers of the engine

- mergify_engine/initial_configuration.py
> initial PR: Don't fail when repo is empty

- mergify_engine/engine.py
- mergify_engine/gh_pr.py
- mergify_engine/gh_pr_fullifier.py
- mergify_engine/tests/test_engine.py
Add workaround about not updated mergeable_state
Don't set ALMOST_READY if the CIs fail.
> Pull request for sileht/blocked-gh-bug-workaround

- mergify_engine/backports.py
- mergify_engine/branch_protection.py
- mergify_engine/branch_updater.py
- mergify_engine/config.py
- mergify_engine/debug.py
- mergify_engine/engine.py
- mergify_engine/initial_configuration.py
- mergify_engine/mergify_pull.py
- mergify_engine/rules.py
- mergify_engine/utils.py
- setup.cfg
This changes the logging mechanism to leverage daiquiri and log a bit better.
- It passes most context information as keyword arguments so they are printed
correctly on the line and can be embedded to Sentry
- It uses a log object per MergifyPull object so it's automatically prepended
with information on the pull request logging
> Use daiquiri and extra prepending to log

- mergify_engine/queue.py
- mergify_engine/tests/test_engine.py
- mergify_engine/web.py
- mergify_engine/worker.py
This change moves all logic into MergifyWorker
Queue hash and methods pickled by rq are now in queue.py
web.py now just drops messages into redis and nothing more.
This allow us to retry anything without requiring to use the Github UI
to resend events.
> Make web.py dummier

- mergify_engine/mergify_pull.py
- mergify_engine/tasks/engine/__init__.py
- mergify_engine/tasks/engine/v1.py
- mergify_engine/tasks/github_events.py
- mergify_engine/tests/test_backports.py
- mergify_engine/tests/test_engine.py
This change moves out from engine, the retrieval of the mergify
configuration and the incoming pull request info.
> Move out of engine config and mergify_pull

- mergify_engine/rules/__init__.py
- mergify_engine/rules/convert.py
- mergify_engine/tests/unit/rules/test_convert.py
This fixes some problem when the config has e.g. no backport labels.
> convert: fix edge cases

- mergify_engine/rules/__init__.py
- mergify_engine/rules/convert.py
- mergify_engine/tests/unit/rules/test_convert.py
- mergify_engine/tests/unit/test_config.py
The current format is too restrictive. List the branches in a branches subkey
so we can add more options if needed to the backport action.
> backport: allow action to be expandable

- mergify_engine/rules/convert.py
- mergify_engine/tests/unit/rules/test_convert.py
That is not needed since backport only affect merged PRs.
> convert: remove 'merged' from conditions

- doc/source/automated-backport.rst
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>
> Doc that pull requests can be labeled for backport after merging.

- mergify_engine/mergify_pull.py
- mergify_engine/rules/parser.py
This is closed to what GitHub API v4 offers and makes more sense with the
`merged` filtering attribute.
> rules: replace state with closed

- mergify_engine/rules/parser.py
- mergify_engine/tests/unit/rules/test_parser.py
This changes the status success/failure to match against any string that follow
the operator. The text parsing is now done with whatever chars are after the
operator.
> rules: fix white space parsing

- mergify_engine/mergify_pull.py
- mergify_engine/tasks/engine/v1.py
Many methods and attributes are used only by v1 engine.
This change moves them there.
> Move out MergifyPull v1 stuff to v1 engine

- mergify_engine/actions/merge.py
We must only looks are required checks only to cancel tasks.
Because "Mergify Merge" checks are always pending.
This change filters checks with only those that configuration requires.
> strict v2: must looks at required checks only

- mergify_engine/tasks/engine/__init__.py
This marks a big red cross whereas everything's fine — you just need to act
manually.
> engine: do not report failure on config changes

- mergify_engine/tests/functional/base.py
- tox.ini
Since I move the cassette removal from tox to test itself.
record-all and record target are almost the same.
The only diff is the -s flag passed for record.
So merge them
> test: fix record

- mergify_engine/actions/merge.py
merge: strict, handle manually closed/merged pr
merge: fixup logging
> Pull request for master

- doc/source/examples.rst
This pull request addresses #66 by adding a new boolean rule called `requested-reviews-approved`. A few notes:
* I don't know how to test or debug Mergify (I didn't see any CONTRIBUTING information that explains how to do this – let me know if I just missed it!). Any help with verifying that it works as expected would be helpful!
* Did I update everything that needs to be updated? I added the data in `mergify_engine/mergify_pull.py`, the search rule in `mergify_engine/rules/parser.py` and the docs in `doc/source/conditions.rst`. Anything else?
* Currently this condition ignores teams. (As I understand it, additional lookups would be needed to get the list of users for each team in order to confirm whether or not the entire team has approved).
> Added requested-reviews-approved condition

- doc/source/conditions.rst
- doc/source/examples.rst
- doc/source/getting-started.rst
- doc/source/strict-workflow.rst
Always use "continuous-integration/travis-ci/pr", as
"continuous-integration/travis-ci" is not a valid CI.
Precise everywhere that team need to be prefixed by '@'
> doc: some cleanup

- mergify_engine/debug.py
- mergify_engine/mergify_pull.py
- mergify_engine/worker.py
mergeable_state is computed asynchronously at GitHub, most of the time
wait a couple of seconds is enough.
This change handle the case where the couple of seconds is not enough by
retrying the whole celery tasks 5 seconds later.
Signed-off-by: Mehdi Abaakouk <sileht@sileht.net>
> Fix retry mechanism of mergeable_state

- doc/source/actions.rst
> merge doc: rebase_fallback can be null, not none

- mergify_engine/actions/merge.py
- setup.cfg
If a repository hits the invalid mergeable state GitHub Bug, it
currently block other repo.
This change fixes that, so only the impacted repository is blocked.
> Better smart queue error handling

- mergify_engine/debug.py
This can happens if the branch has been deleted, e.g.:
github.GithubException.GithubException: 404 {'message': 'Branch not found', 'documentation_url': 'https://developer.github.com/v3/repos/branches/#get-branch'}
> debug: handle error on `is_behind()`

- mergify_engine/web.py
We have some races because we depends on some Github asynchronous
operations. This change adds a small delay to events to ensure this
operations have at least started. This will reduce a lot the retrying
tentative because the PR is in an unexpected state and mitigate some
races.
> Delay incoming events

- mergify_engine/web.py
- setup.cfg
I have created a simple website to verify `.mergify.yml` configs. It basicly does the same thing, as your CURL Command, but CURL isn't nativly available on Windows and for beginner developers it also may be hard to use. My Website simply offers an input field where you can enter your config and then does a fetch to your domain to verify the config.
The Problem is that all modern browsers are blocking those request. So you need to explicitly allow requests from external domains. I have enabled those CORS Headers in your project for the routes `/validate` ~and `/convert`~ (**Edit:** I saw your pull request removing this feature completly).
I hope you like my work and will be happy to merge it. Otherwise, don't hestiate to close this pull, I've had some fun during development and that's what …
> Validation test ui (CORS changed)

- tools/deploy.sh
When deploying, the output shows:
bash: -c: option requires an argument
This does not prevent the command to be executed. This happened because the
first line is empty, so just remove the \n before the first command to make
this disappear.
> deploy: fix bash error

- mergify_engine/branch_updater.py
- mergify_engine/sub_utils.py
- mergify_engine/tests/functional/base.py
This reverts commit 768dbdc0029b5895cc3c3976939caafab2181e22.
> Revert "Check validity of token in subscription cache"

- mergify_engine/debug.py
- mergify_engine/prom_exporter.py
- mergify_engine/sub_utils.py
- mergify_engine/tasks/engine/__init__.py
- mergify_engine/tasks/github_events.py
- mergify_engine/tests/functional/base.py
This changes the logic of event handling to stop checking subscription at
filtering time. Now the event is processed and the subscription is checked with
a new API that reports the status and the reason behind it, allowing to report
details about why Mergify is active — or not.
This also merges several check report under the name "Status".
> tasks: do not ignore private repositories w/o sub but report them

- mergify_engine/debug.py
Right now it would be printed as soon as one token fails.
Only print it if ALL tokens fail.
> debug: fix no token error

- mergify_engine/__init__.py
- mergify_engine/exception.py
- mergify_engine/mergify_pull.py
- mergify_engine/worker.py
We currently send all exceptions to Sentry even those
that we retry with Celery.
This change ensures that exception that need to be retried
will not send event to sentry before all retries are done.
> Filter some exceptions with sentry

- mergify_engine/actions/merge/helpers.py
- mergify_engine/tasks/engine/__init__.py
That doesn't look logic, but well we have received some events with
this...
Closes: MERGIFY-ENGINE-PP, MERGIFY-ENGINE-PQ
> merged_by can be none event if PR is merged

- mergify_engine/rules/__init__.py
- mergify_engine/rules/filter.py
- mergify_engine/tests/unit/rules/test_filter.py
- mergify_engine/tests/unit/rules/test_rules.py
- mergify_engine/tests/unit/test_config.py
This adds a compile function to the Filter class, making sure we can transform
passed values before evaluating a Filter. This allows to catch invalid regexp.
If a Filter is reused, we can save a little CPU by having the regexp compiled
too — fancy.
We also make sure we catch `filter.InvalidQuery` exceptions when parsing
conditions from the YAML file. That allows better error reporting for invalid
engine configuration.
> rules: add compile function and catch error

- mergify_engine/actions/__init__.py
The `cancelled` conclusion is a red cross mark on GitHub, meaning something's
wrong for users. Actually there's nothing wrong, so using neutral should avoid
having PR marked as "failed" because of something just changed.
Fixes #409
> actions: use neutral as conclusion when canceling action

- mergify_engine/prom_exporter.py
GitHub will return 401 if Mergify does not have access anymore. Just ignore it.
> prom_exporter: ignore 401 status code

- mergify_engine/tasks/engine/__init__.py
Before:
* subscription (post check and stop)
* useless events (just stop)
* configuration changes or created (post check and stop)
* configuration missing (just stop)
* configuration validation (post check and stop)
After:
* useless events (just stop)
* configuration changes or created (post check and stop)
* configuration missing (just stop)
* configuration validation (post check and stop)
* subscription (post check and stop)
Closes: #438
> Reorder events skiping conditions

- mergify_engine/check_api.py
- tox.ini
Github doesn't reset conclusion when status is back to in_progress
and we can't set 'null' ourself (Github returns a 4XX).
So manually set conclusion to None when status is in_progress to ensure
the engine take the right decision.
> Workaround when check go in back in progress

- mergify_engine/actions/request_reviews.py
- mergify_engine/mergify_pull.py
This pull request filters out users who have already submitted a review from the `request_reviews` action.
It looks like the GitHub API happily accepts new review requests for users who have already review. Since Mergify runs whenever a PR is edited, this means that with the recently added `request_reviews` action, if a user reviews a PR, then Mergify will request another review from them within moments. This pull request should prevent that from happening. I don't think there's much more that can be done without more extensive configuration.
> Prevent requesting review from users who have already reviewed

- mergify_engine/actions/merge/action.py
- mergify_engine/actions/merge/queue.py
If MergeAction._merge() is called at the same time as
smart_strict_workflow_periodic_task(), since we just remove the PR from
the queue but not yet merged it, the periodic task will update the next
one.
This changes cleanup the queue just after the merge to avoid this race.
> smart: remove PR from queue only when merge is effective

- mergify_engine/exceptions.py
- mergify_engine/tests/unit/test_prom_exporter.py
- mergify_engine/worker.py
Github issue are never solved in a snap, so be less aggressive in
retrying.
This changes retries from 30, 60, 120 to 60, 180, 540
> Rework retry timeout

- mergify_engine/actions/__init__.py
- mergify_engine/tasks/engine/actions_runner.py
We change merge action to return neutral when cancel
> merge: don't retrigger action on neutral conclusion

- mergify_engine/tasks/github_events.py
Somebody was not awake and f-ed up the f-strings.
> github_events: fix metric names

- mergify_engine/worker.py
This reverts commit c5f804f98ab3448690985e73810541add4bd4f80.
This should not be needed anymore.
> Revert "worker: limit broker pool to 1"

- mergify_engine/worker.py
Hosting tmp dir can be slow, add some times for git stuffs.
> celery: increase tasks timetout

- mergify_engine/actions/merge/action.py
mergeable_state is not reliable, just avoid it and on HTTP 405 wait for
branch protection or repository setting to allow Mergify to merge it.
Fixes #541
> branch protection: avoid using mergeable_state

- doc/source/examples/bots.rst
The config below is what works for me with Greenkeeper:
```
pull_request_rules:
- name: automatic merge for Greenkeeper pull requests
conditions:
- author=greenkeeper[bot]
- status-success=continuous-integration/travis-ci/pr
- status-success=greenkeeper/verify
actions:
merge:
method: merge
```
> Fix Greenkeeper config

- doc/source/conditions.rst
This makes things a little more clear and easier to read.
Examples are removed as they are redundant with the general example in the
wider example page.
> doc: rewrite conditions page

- mergify_engine/rules/filter.py
- mergify_engine/tests/unit/rules/test_filter.py
Using `any` when expanding an array is wrong and the `iterable_op` should be
honored.
This fixes the use case of `author!=@myteam` not working as intended.
It used to match as soon as the author was different of one member, which is
always true (unless your team has only one member which is the author itself).
Now this will check for every member of `myteam` to be different than the
author.
> filter: make value expanded data honor iterable operator

- mergify_engine/worker.py
This should avoid losing events/actions on crash.
> worker: use task_acks_late

- mergify_engine/actions/merge/queue.py
- mergify_engine/config.py
- mergify_engine/utils.py
This would help for debugging
It's interesting, to keep error and critical in the console in
additional to external logger that receive everything.
> Pull request for datadog-tcp

- mergify_engine/tasks/engine/commands_runner.py
- mergify_engine/tests/unit/test_command.py
This fixes the statsd tagging which included arguments rather than just the
command name.
> fix(commands): only report command name without args

- .github/semantic.yml
When Mergify update the PR before merging, it adds merge commit
that not allow by semantic pull requests by default
> fix(ci): allow merge commit

- tox.ini
> ci(tox): remove implicit basepython declarations

- mergify_engine/actions/__init__.py
- mergify_engine/actions/close.py
- mergify_engine/actions/comment.py
- mergify_engine/actions/delete_head_branch.py
- mergify_engine/actions/dismiss_reviews.py
- mergify_engine/tasks/engine/actions_runner.py
When a post comment fails, rather than logging an error on our side, let's
store the failed state in the PR conclusion. That should allow the engine to
retry since the status will be "failure" rather than "sucesss".
We don't post the report to the check API because we don't want to have a
report for some actions like comment. To do that a new flag for Action is
added: "silent_report".
Fixes MERGIFY-ENGINE-ZB
FIxes MERGIFY-ENGINE-12Y
> feat(actions): do not log on error but store failed state in the PR

- mergify_engine/actions/comment.py
- mergify_engine/tasks/engine/actions_runner.py
When an action have failed, people expected Mergify to rerun them with
refresh command, but we don't.
This change allows that.
> feat(refresh): rerun failed action

- mergify_engine/tasks/engine/actions_runner.py
When an action goes into an expected state and next event is receive
we set the conclusion to "success".
This makes refreshing not really working as expected.
> fix(refresh): correct set summary conclusion

- mergify_engine/actions/assign.py
- mergify_engine/actions/close.py
- mergify_engine/actions/delete_head_branch.py
- mergify_engine/actions/dismiss_reviews.py
- mergify_engine/actions/label.py
- mergify_engine/actions/request_reviews.py
- mergify_engine/actions/review.py
- mergify_engine/tasks/engine/actions_runner.py
Every should be clean now, all actions should return a report now.
Fixes: MERGIFY-ENGINE-192
> chore: log an error if report=None

- tox.ini
Line length is handled by black and application-import-names is not used by any
current flake8 plugin.
> chore: remove useless flake8 settings

- mergify_engine/actions/merge/helpers.py
Rather than reporting None which seems to be "In progress" in the GitHub UI,
report a failure so it clears that something needs to happen when looking at
the PR list.
> feat(merge): report failure on conflicts

- mergify_engine/exceptions.py
We should not see retry error due to RateLimited exception as we are
supposed to retry after the reset date.
The remaining retry error we should see is when a task is retry due 3
times during 3 hours. Well it's not supposed to happen and ratelimit
monitoring should have bip before.
Related to MERGIFY-ENGINE-195
> feat: set a minimum timeout for ratelimit retry

- mergify_engine/tasks/github_events.py
We now receive all check-runs since a while, no need to continue to
handle them.
> chore: we only need rerequested check_suite

- mergify_engine/clients/github.py
- mergify_engine/mergify_pull.py
- mergify_engine/tests/functional/base.py
Looks like check-runs pull_requested payload don't even have "state"
attribute, just the number ...
Fixes MERGIFY-ENGINE-1B0
Fixes MERGIFY-ENGINE-1B1
> fix: _ensure_mergeable_state()

- mergify_engine/clients/common.py
- mergify_engine/clients/github.py
- mergify_engine/clients/github_app.py
The httpx mixin class was not working, this change also replace it by
classic inheritance.
> fix: replace httpx mixing by inheritance

- mergify_engine/tests/functional/base.py
- mergify_engine/tests/functional/test_github_client.py
- requirements.txt
- setup.cfg
> Pull request for httpx-testools-drop

- mergify_engine/tasks/engine/__init__.py
check-runs may contains pull request from forked repository.
We don't expected them, so drop them.
Fixes MERGIFY-ENGINE-1BD
> fix: Remove unwanted pull request

- mergify_engine/tasks/engine/__init__.py
httpx url are not string, but a httpx.URL.
Fixes MERGIFY-ENGINE-1BQ
> fix: ensure client.base_url is a string

- mergify_engine/actions/assign.py
- mergify_engine/actions/backport.py
- mergify_engine/actions/close.py
- mergify_engine/actions/comment.py
- mergify_engine/actions/copy.py
- mergify_engine/actions/delete_head_branch.py
- mergify_engine/actions/dismiss_reviews.py
- mergify_engine/actions/label.py
- mergify_engine/actions/merge/action.py
- mergify_engine/actions/merge/helpers.py
- mergify_engine/actions/merge/queue.py
- mergify_engine/actions/refresh.py
- mergify_engine/actions/request_reviews.py
- mergify_engine/actions/review.py
- mergify_engine/branch_updater.py
- mergify_engine/check_api.py
- mergify_engine/debug.py
- mergify_engine/duplicate_pull.py
- mergify_engine/exceptions.py
- mergify_engine/mergify_context.py
- mergify_engine/rules/__init__.py
- mergify_engine/tasks/engine/__init__.py
- mergify_engine/tasks/engine/actions_runner.py
- mergify_engine/tasks/engine/commands_runner.py
- mergify_engine/tests/functional/base.py
- mergify_engine/tests/functional/test_engine.py
- mergify_engine/tests/unit/test_behind.py
- mergify_engine/tests/unit/test_config.py
- mergify_engine/tests/unit/test_duplicate.py
- mergify_engine/web.py
This avoid confusion between `pull["number"]` and sometimes
`pull.data["number"]`.
Now we have `pull["number"]` and `ctxt.pull["number"]`
> chore: rename MergifyPull to MergifyContext

- mergify_engine/tasks/github_events.py
When something is merged in a branch, all `mergeable_state` of all opened
PRs of this branch become `unknown` it takes some times for Github to
reevalute them.
This changes the delay before refreshing all opened PRs on our sides.
To avoid many retry due to all mergeable_state being "unknown", just
after a "push" events.
> fix: take more times before refreshing all PRs

- mergify_engine/tests/functional/base.py
GitHub takes several long seconds before exporting the repo.
> test: wait for longer after forking

- mergify_engine/tasks/github_events.py
When receiving a marketplace event, it should not reload the subscription right
away as the event might not be yet forwarded to the dashboard, which then could
return the old purchase.
Simply retrieve it later, when the dashboard had the chance to clear its own cache.
> fix(github_events): do not reload subscription right away

- mergify_engine/clients/github_app.py
The token renew of github_app.Client() is not threadsafe.
This change return a new github Client per threads.
The new behavior will create a JWT per engine run.
> fix: create on github_app client per threads

- mergify_engine/tasks/github_events.py
In case of refresh, data['installation'] does not exists, so don't use
it.
> fix: check installation instead of data['installation']

- mergify_engine/tasks/github_events.py
Tokens are only needed in one corner case, worst thing, we can run without
them.
> fix(tasks): run even if no token are available

- mergify_engine/actions/merge/queue.py
If a RateLimited error is raised, `ctxt` is undefined so that code should fail.
> fix(queue): always use queue logger on rate limit

- mergify_engine/clients/github_app.py
- mergify_engine/tests/unit/test_clients.py
This permissions are mandatory to allow Mergify to report that other are
missing. So just do nothing in such case.
> feat: don't return the engine, if mandatory perm are missing

- mergify_engine/clients/github.py
- mergify_engine/tests/functional/base.py
retrieving too many token cause Github to return 401 after a while.
This change creates a memory cache of them to avoid that.
> fix: create a memory cache of temporary access token

- requirements.txt
- setup.cfg
python-multipart is now optional dependency of fastapi.
Fixes MERGIFY-ENGINE-1KK
> fix: add python-multipart dep

- .mergify.yml
Automatic fast merge should only by used for hotfixes. Let's make sure we have
the right label and a Sentry entry to make that happen.
> Pull request for mergify-config-update

- mergify_engine/actions/assign.py
- mergify_engine/actions/close.py
- mergify_engine/actions/comment.py
- mergify_engine/actions/copy.py
- mergify_engine/actions/delete_head_branch.py
- mergify_engine/actions/dismiss_reviews.py
- mergify_engine/actions/label.py
- mergify_engine/actions/merge/action.py
- mergify_engine/actions/request_reviews.py
- mergify_engine/branch_updater.py
- mergify_engine/clients/github.py
- mergify_engine/clients/github_app.py
- mergify_engine/clients/http.py
- mergify_engine/context.py
- mergify_engine/debug.py
- mergify_engine/duplicate_pull.py
- mergify_engine/engine/__init__.py
- mergify_engine/engine/commands_runner.py
- mergify_engine/exceptions.py
- mergify_engine/rules/__init__.py
- mergify_engine/sub_utils.py
- mergify_engine/tests/functional/test_github_client.py
- mergify_engine/tests/unit/test_clients.py
- mergify_engine/tests/unit/test_forwards.py
- mergify_engine/tests/unit/test_worker.py
- mergify_engine/web.py
- setup.cfg
httpx exceptions does not inherit from HTTPError anymore.
This may break again in the future...
https://github.com/encode/httpx/issues/949
So this change:
* removes the httpx monkeypatching
* put all http related error in clients/http.py
* adds catch HTTP Connection related Exception again
The rest of the code does not import httpx for caching exception anymore.
Fixes MERGIFY-ENGINE-1KZ MERGIFY-ENGINE-1KY
> fix(httpx): exception handling have changed

- doc/source/faq.rst
- mergify_engine/actions/merge/action.py
- mergify_engine/context.py
This improves the error message with a proper link to the documentation.
It also covers the recent GitHub changes that makes it impossible to modify a
private fork from our app.
> fix(merge): improve error reporting for strict mode and not modifiable branches

- mergify_engine/actions/merge/queue.py
- mergify_engine/actions/refresh.py
- mergify_engine/branch_updater.py
- mergify_engine/clients/github.py
- mergify_engine/clients/github_app.py
- mergify_engine/debug.py
- mergify_engine/engine/__init__.py
- mergify_engine/github_events.py
- mergify_engine/tests/functional/base.py
- mergify_engine/tests/functional/test_engine.py
- mergify_engine/tests/functional/test_github_async_client.py
- mergify_engine/tests/functional/test_github_client.py
- mergify_engine/tests/unit/test_clients.py
- mergify_engine/tests/unit/test_event_to_pull.py
- mergify_engine/tests/unit/test_record_endpoints.py
- mergify_engine/tests/unit/test_web.py
- mergify_engine/tests/unit/test_worker.py
- mergify_engine/web.py
- mergify_engine/worker.py
testing redis may have data from other tests
> Pull request for no-install-id

- setup.cfg
We don't use it directly and gunicorn pulls it from its own usage already.
> build: remove setproctitle dependency

- setup.cfg
We don't use/import it directly.
> build: remove idna dependency

- mergify_engine/actions/merge/queue.py
we log in a row:
* "handling queue"
* "2 pull queued"
Only the second one is useful
> chore: remove useless log message

- mergify_engine/actions/assign.py
- mergify_engine/actions/dismiss_reviews.py
- mergify_engine/actions/request_reviews.py
- mergify_engine/rules/types.py
- mergify_engine/tests/unit/rules/test_types.py
Make sure we validate GitHub login and team names when used in configuration.
For example, the current format name for teams is "@team" or "@org/team" in
conditions, but that does not work in the request reviews action. This makes
sure it now does.
> feat(actions): validate GitHub login and team names

- mergify_engine/actions/merge/helpers.py
Currently, we stop processing the PR until a conditions change.
While in such case we should retry.
To do, so we return cancelled instead of failure.
So next synchronize will retry to merge the PR if all conditions still
match.
> fix: allow retry of merge when branch is dirty

- mergify_engine/worker.py
This reverts commit d10a0d3a03abce90e5c9ff90d798a5cceb603079.
Sentry does not work with asyncio.
> revert: "feat(worker): set user in Sentry"

- mergify_engine/tests/bridge.py
This is not supported by httpx and not needed anymore.
> fix(bridge): remove verify=False for http client

- mergify_engine/context.py
- mergify_engine/rules/__init__.py
- mergify_engine/rules/types.py
- mergify_engine/tests/functional/test_attributes.py
- mergify_engine/tests/unit/rules/test_rules.py
Jinja issue was reported as:
`expected from_list @ dictionary d["pull_request_rules"]`
Now the correct unexpected error is reported.
The added test now raises:
...
mergify_engine/rules/types.py:61: in Jinja2
_DUMMY_PR.render_template(value)
mergify_engine/context.py:454: in render_template
return self.jinja2_env.from_string(template).render()
.tox/py38/lib/python3.8/site-packages/jinja2/environment.py:1090: in render
self.environment.handle_exception()
.tox/py38/lib/python3.8/site-packages/jinja2/environment.py:832: in handle_exception
reraise(*rewrite_traceback_stack(source=source))
.tox/py38/lib/python3.8/site-packages/jinja2/_compat.py:28: in reraise
raise value.with_traceback(tb)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
> fix: don't shallow unexpected jinja issue

- mergify_engine/actions/merge/queue.py
> fix(merge): pass correct pull number and not context when moving base branch

- mergify_engine/worker.py
The current empty return avoid to run the engine code that reports the
subscription issue. Therefore there's no report at all done.
> fix(worker): do not ignore private repo with no sub

- mergify_engine/worker.py
log error when the number of attempts for an installation is too high
> feat(worker): too many stream attempts should at least log an error

- mergify_engine/actions/merge/queue.py
get_subscription() and client.item() may raise 500, timeout, ...
We should just log and ignore those errors.
Fixes MERGIFY-ENGINE-1S5
> fix(merge): handle subscription/pull http retry error

- mergify_engine/debug.py
- mergify_engine/engine/__init__.py
- mergify_engine/rules/__init__.py
- mergify_engine/tests/unit/rules/test_rules.py
Some errors just end up to `expected from_list at ...`.
This change remove the intermediate schema, so a better error is
reported.
Fixes: MRGFY-49
> fix: remove intermediate schema

- mergify_engine/clients/github.py
Since httpx 0.14.3, `aclose` is no more called by `__aexit__()`.
So we have to implement it too.
> fix(http-client): implement __aexit__/__exit__

- mergify_engine/clients/github.py
- mergify_engine/tests/unit/test_clients.py
This makes it possible to authenticate without specifying a repository.
> refactor(auth): make auth repo-free

- tox.ini
No need to install the requirements list.
> ci: disable pre_commands for black/pep8 targets

- doc/source/actions.rst
- mergify_engine/actions/request_reviews.py
- mergify_engine/tests/unit/actions/test_request_reviews.py
Setting more than 15 users is not going to work, so let's try to validate this
a little in the configuration file.
> feat(config): check the length of users/teams for request reviews

- doc/source/actions.rst
- mergify_engine/actions/copy.py
- mergify_engine/tests/unit/test_command.py
This restores the previous behaviour of creating conflicting backport by
default. This is what people seems to be using.
It also fixes a limitation: since commands can't have options, it's impossible
to do a backport via the command in comment when there's a conflict.
This makes it possible and up to the user to close the conflicting backport if
needed.
> fix(action): ignore conflicts by default

- docs/source/_templates/layout.html
This is used by some Bootstrap components that we don't use in docs.
> docs: remove Popper

- mergify_engine/actions/request_reviews.py
- mergify_engine/tests/unit/actions/test_request_reviews.py
When `random_count` is being used, it should be possible to list more than 15
users/teams.
We still do the check at runtime.
> fix(request_reviews): do not limit the number of user/teams

- mergify_engine/actions/copy.py
I discover this because related tests can't be record again.
With this record work again.
> fix: backport error should return failure

- mergify_engine/context.py
This ignore a bug in the cachetools stubs at
https://github.com/python/typeshed/issues/4652
> fix(mypy): update for latest type hints

- requirements.txt
- setup.cfg
Since 0.12.0, many deps are optionnal, but we need them...
https://github.com/encode/uvicorn/commit/5fa99a11d6e07367cd559a4fc8694ce537796558
Dependabot never remove obsolete deps, so we didn't catch the issue
until I regenerate the requirements.txt from scratch.
But even with that we have no test to check this kind of bug.
The bug is only triggered when the Procfile is used.
> fix: add uvicorn extra

- docs/source/examples.rst
"We're delight" -> "We're delighted"
> docs: fixing a typo in Examples

- mergify_engine/branch_updater.py
- mergify_engine/duplicate_pull.py
Git reported message can have some html tag coming from user code.
We must escape them with a `<pre>` tag so Github will not render them.
Close #1529
> fix: decorate git error message with <pre>

- requirements.txt
- tox.ini
until 0.15 is release we need this fix
Fixes MERGIFY-ENGINE-1WQ
> fix: uvloop py39 workaround

- mergify_engine/clients/github.py
- mergify_engine/tests/unit/test_clients.py
This avoid infinite recursive call to /rate_limit
Fixes MERGIFY-ENGINE-1WX
> fix(http): don't handle 403 for ratelimit API

- mergify_engine/clients/github.py
- mergify_engine/exceptions.py
- mergify_engine/tests/unit/test_clients.py
- mergify_engine/worker.py
We only check the value returned by GitHub API when a 403 is returned, without
making another request.
> refactor(clients): do not check /rate_limit each time

- docs/source/actions.rst
This is just a tiny typo fix 
`the that => that`
> chore: Fix typo in rebase section

- mergify_engine/actions/merge.py
Right now if a PR is first in queue it says "0th".
> fix(merge): do not start queue in UI on 0

- datadog/prerun.sh
Some large logs are truncated otherwise.
> fix(datadog): increase log frame_size buffer

- mergify_engine/subscription.py
The log field for the owner is an id and not a login name, making it impossible
to find the log entry anyway. Just remove the log entirely.
> fix(sub): remove spurious log line

- mergify_engine/github_events.py
We was ignoring this state to reduce the load before we was batching
events.
Ignoring this status have a unwanted behavior. If CI fails and user
re-run it, the status goes back to pending from GitHub point of view,
but for us, it's stay failing until we receive success.
In real world, we often received events that make us looks at the status
and user didn't notice it was not updated on time.
> chore: handle status pending

- tox.ini
Right now, for example, the `record` target takes whatever Python tox is
installed with.
> ci(tox): specify basepython

- mergify_engine/config.py
GitHub seems to use KB and not KiB, and MB are advertised in the documentation.
> fix: use KB not KiB

- docs/source/actions.rst
This looks like what a default YAML serializer would write.
> docs: use lower case boolean values

- mergify_engine/worker.py
This is the same result as previous, but now it works.
> Pull request for fix-monitoring-task

- mergify_engine/actions/merge.py
- mergify_engine/context.py
- mergify_engine/rules/__init__.py
- mergify_engine/rules/filter.py
- mergify_engine/tests/unit/rules/test_filter.py
This allows to pass context.PullRequest object directly rather than building an
intermediary dict.
> refactor(rules): pass object to Filter.__call__ rather than dict

- mergify_engine/context.py
- mergify_engine/engine/__init__.py
- mergify_engine/github_events.py
- mergify_engine/github_types.py
- mergify_engine/web/__init__.py
Some GitHub events actually do not have the `action` attribute.
Declare those events and use Literal to handle valid values.
> fix(github_types): only set action field where available

- mergify_engine/context.py
This was to fight against pygithub partial object.
This is not needed anymore with our http client.
> chore: remove useless check

- mergify_engine/engine/__init__.py
- mergify_engine/engine/commands_runner.py
- mergify_engine/github_events.py
- mergify_engine/github_types.py
- mergify_engine/tests/unit/test_web.py
Some GitHubEvent do not have the `repository` field, takes that into account.
That needs a big refactor of the `get_ignore_reason` function. Therefore, this
patch refactors GitHub event handling to cast them only once and handle them
entirely in a single function.
This makes it easier to read the code handling each event type and seeing how
they are processed or ignored.
> fix(github_types): repository is not on every GitHubEvent

- mergify_engine/github_events.py
This should make sure the Mergify summary reappears as in progress as soon as
new commits are pushed.
> fix(github_events): also send initial summary on synchronize events

- mergify_engine/github_events.py
We don't need to cache the fact that this sha is not attach to a pull
request since we don't do API call anymore in this method.
> chore: remove useless code

- mergify_engine/__init__.py
We have many sentry with truncated exc_info, eg:
Traceback (most recent call last):
File "/app/.heroku/python/bin/mergify-engine-worker", line 33, in <module>
sys.exit(load_entry_point('mergify-engine', 'console_scripts', 'mergify-engine-worker')())
File "/app/mergify_engine/worker.py", line 797, in main
return asyncio.run(run_forever())
File "/app/.heroku/python/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/app/.heroku/python/lib/python3.9/asyncio/base_events.py", line 640, in run_un...
This should help to debug them.
> chore(sentry): increase log message size

- mergify_engine/tests/unit/rules/test_filter.py
This avoids the pytest warning:
pytestCollectionWarning: cannot collect test class 'TestDict' because it has a __init__ constructor
> fix(tests): don't use Test word in non-test class

- tox.ini
check-obsolete-fixtures fails entirely if the code fails to load because e.g.
SyntaxError. But it does not report it correctly.
Running it last makes it easier to spot mistakes by having Python tools
reporting the error first.
> ci: run check-obsolete-fixtures at end

- mergify_engine/context.py
- mergify_engine/debug.py
- mergify_engine/engine/__init__.py
- mergify_engine/rules/__init__.py
- mergify_engine/subscription.py
- mergify_engine/tests/unit/rules/test_rules.py
- mergify_engine/utils.py
Everything that run in the engine thread must not share httpx and aredis
client.
They open tcp connection binded to an asyncio loop. loop can't be shared
between async.run() run.
Luckily httpx client reraise the asyncio RuntimeError exception, but
aredis doesn't and assume connection have been reset by the peer.
Which is wrong, the connection stay establish from OS point of view
until OS TCP idle timeout is reach.
This changes opens one connection per loop until we remove the engine
thread and have only one loop forever.
Related to https://github.com/NoneGG/aredis/issues/149
Fixes MERGIFY-ENGINE-1ZT
Fixes MERGIFY-ENGINE-1ZQ
Fixes MERGIFY-ENGINE-1ZW
> fix: don't reuse aredis client yet

- mergify_engine/github_events.py
- mergify_engine/github_types.py
- mergify_engine/queue.py
- mergify_engine/rules/types.py
- mergify_engine/tests/unit/test_context.py
- mergify_engine/tests/unit/test_synchronize.py
- mergify_engine/web/__init__.py
Using typing.cast(GitHubPullRequestNumber, "123") is valid for mypy as
it just trust us.
GitHubPullRequestNumber must be int, so we can use
GitHubPullRequestNumber("123") and got the expected:
Argument 1 to "GitHubPullRequestNumber" has incompatible type "str"; expected "int"
GitHubPullRequestNumber(GitHubIssueNumber(123)) will still works as
there are both int
> chore(github_types): GitHubPullRequestNumber must be int

- docs/source/actions.rst
- mergify_engine/actions/comment.py
- mergify_engine/actions/merge.py
- mergify_engine/actions/rebase.py
- mergify_engine/actions/review.py
This unblocks use cases such as the ability to use the pull request author to
merge a PR.
> feat(actions): allow bot_account to be a Jinja2 template

- mergify_engine/clients/github.py
Since the client is per-context and per-PR anymore, it makes sense to bump it.
> chore: bump GH client threshold

- mergify_engine/exceptions.py
This will make the engine always retry after a redis connection issue
instead of reporting failure to user.
> fix: never ever report redis connection issue in actions

- .github/workflows/ci.yaml
- .github/workflows/docker.yaml
Publish image to Docker Hub instead of GitHub Package.
GitHub Package requires to be authentified to work. We need a
non-authentified public repo to work with heroku.
> feat: publish docker image on docker hub

- mergify_engine/subscription.py
We unfortunately use decode_responses=True for `RedisCache`,
redis.get will returns str instead of bytes.
I wonder how this can have worked...
> fix: subscription decrypt typing

- mergify_engine/subscription.py
- mergify_engine/tests/unit/test_engine.py
- mergify_engine/tests/unit/test_subscription.py
We now cache subscription for 3 days, but check the databases every 1
hours as before.
This allow to keep the last subscription when connectivity issue occurs
on dashboard side.
Fixes MRGFY-318
> feat: rework subscription cache handling

- datadog/conf.d/redisdb.yaml
It's not clear why it doesn't work, maybe https://github.com/andymccurdy/redis-py/pull/1352
So disable it
(pkg/collector/runner/runner.go:292 in work) | Error running check redisdb: [{"message": "sequence item 0: expected a bytes-like object, int found", "traceback": "Traceback (most recent call last):
File \"/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 876, in run
self.check(instance)
File \"/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py\", line 501, in check
self._check_slowlog()
File \"/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py\", line 452, in _check_slowlog
slowlogs = conn.slowlog_get(max_slow_entries)
File …
> fix(datadog): disable redis slowlog monitoring

- mergify_engine/queue/merge_train.py
- mergify_engine/tests/unit/test_train.py
add_pull() must be idempotent like the naive queue one.
No need check priority change as it's already handled upfront.
> fix(queue): don't add pull to train twice

- mergify_engine/actions/copy.py
- mergify_engine/duplicate_pull.py
This change makes explicit all duplicate() errors.
This may raise some Sentry, but this will force us to track all kind of
errors and report a meaningful reason about the failure.
> fix: catch all duplicate silent issue

- mergify_engine/clients/github.py
This should help getting information on GitHub request latency.
> feat(github): add Datadog metric for http client request time

- mergify_engine/config.py
- mergify_engine/utils.py
- mergify_engine/web/__init__.py
The default pool limit is 2**31, this allows to configure it.
> feat(web): allow to limit number of redis connections

- mergify_engine/branch_updater.py
This was needed in the past because exception was not going back to the
Worker() correctly.
The actual code is buggy:
`if isinstance(e, http.HTTPStatusError) and http.HTTPStatusError:`
The right side doesn't make any sense.
> fix(update): don't fast retry via API

- mergify_engine/actions/merge_base.py
- mergify_engine/actions/rebase.py
- mergify_engine/actions/update.py
- mergify_engine/branch_updater.py
- mergify_engine/exceptions.py
After the fast local retry, this exception was report as error or
catched by the catch all worker error handling.
This change makes it correctly handled by exception.need_retry(),
we should not get sentry any more of them.
This will allow to use it in merge_train
> fix: silently retry BranchUpdateNeedRetry

- mergify_engine/worker.py
tenacity hide some informations in sentry when the original exception is
wrapped into a RetryError. So just reraise the original one.
> chore: reraise redis connection errors

- mergify_engine/tests/functional/base.py
- mergify_engine/tests/functional/test_engine.py
- mergify_engine/web/__init__.py
add a second temporary queues route before updating the dashboard part
> refactor(queue API): removing GitHub API call

- requirements.txt
- tox.ini
The stable version of aredis have two annoying issues for us:
* it doesn't handle correctly asyncio.CancelledError in some code path:
(fixed in master: https://github.com/NoneGG/aredis/pull/172, https://github.com/NoneGG/aredis/pull/170)
* it doesn't show the reason of initial connection failure
(https://github.com/NoneGG/aredis/pull/188)
This change uses a custom build until aredis release a version with all
these fixes.
> fix: aredis custom build

- docs/source/actions/merge.rst
- docs/source/actions/queue.rst
- mergify_engine/actions/merge.py
- mergify_engine/actions/merge_base.py
- mergify_engine/actions/queue.py
The current value to disable `rebase_fallback` was the json `null`
value. Since the option is string it's not obvious that you should not
quote `null`. And `null` is not documented.
This changes introduce `none` string, that just a alias to json null.
And it documents it.
Fixes MRGFY-352
> fix: clear option to disable rebase_fallback

- mergify_engine/actions/refresh.py
- mergify_engine/debug.py
- mergify_engine/queue/__init__.py
- mergify_engine/queue/merge_train.py
- mergify_engine/tests/conftest.py
- mergify_engine/tests/functional/actions/test_post_check.py
- mergify_engine/tests/functional/base.py
- mergify_engine/tests/functional/test_engine.py
- mergify_engine/utils.py
- mergify_engine/web/redis.py
- mergify_engine/worker.py
Currently if the redis connection is not working
* The asyncio Worker._run() task exits with a never awaited
`aredis.ConnectionError` exception, and Worker() just waits for
`_shutdown()` to be called.
* The fastapi/starlette  web.root._startup() hook raises a
`aredis.ConnectionError` exception and the web dyno is restarted.
Fixes MRGFY-339
> fix: don't use redis connection on startup

- mergify_engine/tests/functional/base.py
- mergify_engine/tests/unit/test_worker.py
- mergify_engine/worker.py
We don't really need to create a task since no IO occurs during startup
now.
This will ensure that anything unexpected during startup will raise an
exception instantly and not when the worker shutdown.
> fix: ensure errors on startup/shutdown are raised

- docs/source/actions/merge.rst
- docs/source/actions/queue.rst
This relies on the queue documentation a little more to simplify the merge
action.
> docs(merge): simplify documentation

- mergify_engine/actions/refresh.py
- mergify_engine/github_events.py
- mergify_engine/queue/__init__.py
- mergify_engine/queue/merge_train.py
- mergify_engine/utils.py
- mergify_engine/web/root.py
This will avoid most circular import isssues
> chore: move send_refresh out of github_events

- docs/source/actions/close.rst
- docs/source/actions/delete_head_branch.rst
- docs/source/actions/dismiss_reviews.rst
- docs/source/actions/update.rst
- mergify_engine/actions/__init__.py
- mergify_engine/rules/__init__.py
- mergify_engine/tests/unit/rules/test_rules.py
Allow to use null instead of {}, when we have no option to pass.
Fixes MRGFY-378
> feat: allow to use null instead of {} in action config

- mergify_engine/engine/__init__.py
- mergify_engine/engine/actions_runner.py
- mergify_engine/rules/__init__.py
In case of user hasn't defined pull_request_rules we don't need to look
at Summary and throw a ton of useless logs.
> chore: avoid useless logging

- mergify_engine/context.py
- mergify_engine/tests/unit/actions/test_request_reviews.py
- mergify_engine/tests/unit/test_context.py
The team permission endpoint may return 204 with no payload.
This change handles this.
Fixes MERGIFY-ENGINE-25T
> fix(teams): don't deserialize 204

- mergify_engine/subscription.py
- mergify_engine/tests/unit/test_subscription.py
> chore: pass the owner_id in the subscription API call

- .yamllint.yml
- installer/src/App.css
- installer/src/App.jsx
- mergify_engine/web/root.py
This merge the Download config and Install App page.
We set the setup_url in manifest, so after the installation, we got
redirect to the installer and we can display a success message.
This make the new flow has only 5 screens instead of 7:
* Enter the GitHub login, click Create
* Confirm creation on GitHub
* Download the config and click Install
* Confirm installation on GitHub
* Got success message
> chore(installer): reduce number of steps

- mergify_engine/actions/assign.py
- mergify_engine/actions/backport.py
- mergify_engine/actions/close.py
- mergify_engine/actions/comment.py
- mergify_engine/actions/copy.py
- mergify_engine/actions/delete_head_branch.py
- mergify_engine/actions/dismiss_reviews.py
- mergify_engine/actions/label.py
- mergify_engine/actions/merge_base.py
- mergify_engine/actions/post_check.py
- mergify_engine/actions/rebase.py
- mergify_engine/actions/refresh.py
- mergify_engine/actions/request_reviews.py
- mergify_engine/actions/review.py
- mergify_engine/actions/update.py
- mergify_engine/signals.py
- mergify_engine/tests/unit/test_signals.py
- mergify_engine_signals/datadog_signal/__init__.py
- setup.cfg
- setup.py
- tox.ini
This introduce a signal mechanism with an example
plugin for datadog.
The new datadog metric "engine.signals.actions.count"
* "engine.actions.count" count when action is ran by rule but it count
too much thing:
* some actions run on each batch until they unmatch
* some other return PENDING until they can complete and get counter
multiple times.
* the action may run but do nothing (labels already set, pull
already up2date or merged)
* "engine.command.count" count when an action is ran as a command
"engine.signals.actions.count" will track action run by rules and commands
but when they really do something on user pull requests.
> feat: add signaling mechanism

- requirements.txt
- tox.ini
This doesn't play well with heroku-buildpack-python if the project is
located in a subdirectory.
We don't really need to have it editable, it will not be cached anymore
but we don't care.
> fix(requirements): don't use pip editable installation for deps

- mergify_engine/signals.py
- mergify_engine/tests/unit/test_signals.py
- mergify_engine/worker.py
This ensure the logging system is setuped. Otherwise we may not
see errors raise by signal modules.
> fix(signals): postpone module import

- docs/source/actions/rebase.rst
- mergify_engine/actions/rebase.py
This option shouldn't have used by OpenSource plan.
Post a comment to warn people and disable on 1 July
Fixes MRGFY-419
> chore: deprecated bot_account for OpenSource plan

- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yaml
Only docs need a write GITHUB_TOKEN. So mark other as read-all only.
> ci: make github actions read only when possible

- .github/workflows/ci.yaml
This ensures all buildpacks hook are run like heroku does.
> ci(heroku): use heroku profile.d files to load PATH

- mergify_engine/subscription.py
The engine we no longer run if it have been installed without logged
into our dashboard.
> fix: don't run engine if owner in unknown

- .github/workflows/ci.yaml
- requirements.txt
- setup.cfg
- tox.ini
Our requirements are in setup.cfg, while our requirements is more
contraints. To make all of this works for heroku we put "-e ." inside
requirements.txt.
Infortunatly, this make impossible to install the engine with pip
install -e mergify-engine-dir.
This change uses pip contraints instead of requirements. We can now
install mergify-engine with just `pip install -e mergify-engine-dir`.
And if we want strict dependency checking we can still use `pip install
-c mergify-engine-dir/contraints.txt -e mergify-engine-dir`. We keep the
name requirements.txt to please dependabot.
> chore: use pip contraints instead of requirements

- mergify_engine/engine/actions_runner.py
`setuped` isn't a word and standard dictionaries.
This change replaces it with `configured` which is a word
> fix: improve terminology

- mergify_engine/clients/github.py
At first glance, the mean is 25, now.
This will remove some useless logs ~ 0.25%
> chore: increase threshold of logged requests

- .github/workflows/codeql-analysis.yml
It need to write on an GitHub special endpoint for push "master" event:
PUT https://api.github.com/repos/Mergifyio/mergify-engine/code-scanning/analysis/status
> ci: fix codeql workflow permissions

- mergify_engine/actions/comment.py
- mergify_engine/actions/copy.py
- mergify_engine/actions/delete_head_branch.py
- mergify_engine/actions/merge_base.py
- mergify_engine/actions/review.py
- mergify_engine/branch_updater.py
- mergify_engine/check_api.py
- mergify_engine/clients/github.py
- mergify_engine/context.py
- mergify_engine/duplicate_pull.py
- mergify_engine/engine/commands_runner.py
- mergify_engine/github_types.py
- mergify_engine/queue/merge_train.py
- mergify_engine/tests/functional/actions/test_assign.py
- mergify_engine/tests/functional/actions/test_backport.py
- mergify_engine/tests/functional/actions/test_delete_head_branch.py
- mergify_engine/tests/functional/actions/test_request_reviews.py
- mergify_engine/tests/functional/commands/test_backport.py
- mergify_engine/tests/functional/commands/test_copy.py
- mergify_engine/tests/functional/test_engine.py
- mergify_engine/tests/functional/test_github_async_client.py
- mergify_engine/tests/unit/rules/test_rules.py
- mergify_engine/tests/unit/test_clients.py
- mergify_engine/user_tokens.py
The oauth_token format have changed recently. Unfortunatly mypy didn't
catch it as type: ignore was everywhere.
The issue could have been seen only by rerecording a test using
bot_account.
This change fixes all bot_account oauth_access_token and remove all
type: ignore related github Api calls.
> fix: oauth_token format

- mergify_engine/duplicate_pull.py
cherry-pick may failed without creating commits. This change handles
this case to correctly report it to user.
Fixes MRGFY-438
> fix(backport/copy): handle when duplicate fail with no commit

- mergify_engine/actions/dismiss_reviews.py
- mergify_engine/actions/merge.py
- mergify_engine/actions/queue.py
- mergify_engine/context.py
- mergify_engine/engine/__init__.py
- mergify_engine/engine/queue_runner.py
- mergify_engine/github_events.py
If a queued pull request didn't get events for more than 1 month, and
suddenly get a synchronize event we can lose the state of the PR.
This change restore a old mechanism that get the summary sha information
via synchronize event, but use it at fallback only.
> fix(summary): reintroduce getting summary from synchronize event

- docs/source/_static/mergify.css
- docs/source/_static/mergify.js
Sphinx sometimes uses <section> or <div class="section">.
I'm not sure what changes the behaviour, but in doubt, supports both.
> docs: fix section handling

- mergify_engine/context.py
- mergify_engine/github_types.py
This adds a check for author_association on reviews: if it's NONE, there's 0
chance the user has a write permission on the repository, so the request can be
bypassed altogether.
> refactor(context): only check for user permission if it's worth it

- mergify_engine/tests/functional/actions/test_merge.py
- mergify_engine/tests/functional/actions/test_queue.py
Currently for GHE some tests are run with a PAT instead of OAUTH token.
Until we have something to generate oauth_token without the dashboard,
disable tests that can't work with a PAT token.
Fixes MRGFY-460
> fix(tests): skip workflow tests on GHE

- mergify_engine/engine/__init__.py
We only care about the first one so just stop when we find one.
> refactor(engine): do not iterate on all check when getting summary from sha

- mergify_engine/engine/actions_runner.py
The current filter does not seem to be useful: it expect a list of
dictionaries, and from this list it removes a bunch of keys such as "node_id"
or "tree_id".
The current code sends as argument a list of T_PayloadEventSource which does
not contains any of this.
I imagine this was needed when sources were (probably?) directly a list of
GitHubEventType, but it's not the case anymore, and a lot of filtering is
already done before we log.
> refactor(actions_runner): remove log filter

- mergify_engine/context.py
This log the issue instead of failing.
I don't really get how body can be None, I have checked some pull
requests from Sentry and the body is not None, so I'm confused.
Fixes MERGIFY-ENGINE-26S
> fix(depends-on): body may be null

- mergify_engine/context.py
After double checks the new logging output, the body can indeed be
None when freshly fetched from GitHub.
This removes the temporary logging.
Fixes MERGIFY-ENGINE-26T
> fix(depends-on): don't log error when body is None

- mergify_engine/actions/merge_base.py
We must not yet cancel the merge when PUT /merge fail because head
branch change.
Here the sequence of events that lead to a PR dropped from the queue:
* merge run()
* base branch is updated on our side (but not yet on GH side)
* got a label event
* pull[head][sha] is still the old one
* then we check is_behind() and got false (base branch got update on
GH side)
* and try to merge the PR with the old sha
* it fail and set the state to CANCELLED
Since the pull request has been update by us, people doesn't expect the
PR to be unqueued.
This change set the state to PENDING in such case, so decision to drop
or not the PR is postponed to when we will received the synchronize
event of our rebase.
Change-Id: I31a980ff55b5c469f471f5b987140f92f7171b74
> fix: retry merge when head branch change

- mergify_engine/rules/__init__.py
- mergify_engine/tests/unit/rules/test_rules.py
This handles the case where MultipleInvalid contains MultipleInvalid.
Fixes MERGIFY-ENGINE-271
Change-Id: I36773ba024a92733733293063428d26ee44095ee
> fix(conditions): handling of cascaded errors

- mergify_engine/github_events.py
We recently recent the code that strip all url from GitHub events.
We miss one place here that copyi the whole sender data into context
sources.
This fixes that.
Change-Id: Ie01c6e77b12ee82ac3377de583fd0e49aa0fa54b
> chore: don't copy all sender data

- .github/workflows/ci.yaml
- .github/workflows/docs-pr.yaml
Because pull_request workflow run on forked repository doesn't have
access to secret this is done in two steps:
1. docs is uploaded as GitHub artefact
2. a priviledged workflow copy the artefact to gcp
Change-Id: I5dca961bb515876da004631a8890c3549b951a04
> feat: temporary publish docs from pull build on gcp

- mergify_engine/actions/merge_base.py
- mergify_engine/rules/__init__.py
- mergify_engine/rules/filter.py
- mergify_engine/tests/unit/rules/test_filter.py
This makes the Filter class Generic.
The binary implementation is now called FilterBinary
A future implementation will be done to return the more recent
timestamp.
Change-Id: Ice711d1f106d445badf6dc5539fc1b309887b35a
> refactor(filter): make it generic

- .github/workflows/ci-docs.yaml
- .github/workflows/ci.yaml
- .github/workflows/docs-upload-gcp.yaml
- .github/workflows/docs-upload-gh-pages.yaml
This:
* splits out Documentation job from ci.yaml. This allows to upload to
documentation even if other part of the CI fail
* post a check run with the url of the documentation
Cloudfare Worker is used to redirect docs-preview.mergify.io to our
public gcp bucket.
Change-Id: I3890e3c2699e79cb50ab946e5ba1000fc975fb30
> fix(docs): finish upload to gcp

- mergify_engine/config.py
We was generated the list [""] instead of []. And "" is the root Logger
and it got configured to DEBUG level.
This fixes that.
Change-Id: Iae95e26ce671292101fc7d0c8a5a7974857e9232
> fix(logs): don't set root logger to DEBUG

- mergify_engine/web/simulator.py
This uses the same config parser as the engine to handle
defaults.
Change-Id: I0ab5f12168a546cf91802bd00270235039b63626
> fix(simulator): use same config parser as the engine

- mergify_engine/context.py
- mergify_engine/tests/unit/test_worker.py
- mergify_engine/worker.py
This has nothing to do with the Context. And in future work, the stream
name will not be guessable like this and must be read from the "streams"
redis key.
Change-Id: Icc3dcd1c2112b439bf3716f845a6d42f8e8da4d4
> refactor(worker): remove stream_name from Context.Installation

- mergify_engine/engine/__init__.py
Since we cache for the duration of a batch, the sources may not be empty
when we start the engine.
This fixes that, so no event will be seen twice.
Change-Id: I39566487afd974407866bef0977137518ebf050b
> fix: ensure Context.sources is empty on each engine run

- .github/workflows/codeql-analysis.yml
The job takes 10 minutes and we don't require it to merge PR.
So just tests all commits of the main branch.
Change-Id: I72a8ada8f1d2521355332ea212f3b16767bf3eb3
> ci: only check codeQL on push event

- mergify_engine/duplicate_pull.py
We don't support octopus merge commit.
Fixes MERGIFY-ENGINE-280
Fixes MERGIFY-ENGINE-27Y
Change-Id: I4009ca99bf49442d98d736b7631e176784526025
> fix: return failure for unhandled merge commit format

- mergify_engine/actions/close.py
- mergify_engine/actions/delete_head_branch.py
- mergify_engine/actions/merge.py
- mergify_engine/actions/merge_base.py
- mergify_engine/actions/queue.py
- mergify_engine/context.py
- mergify_engine/engine/queue_runner.py
GitHub automerge doesn't always close pull request when it merge them...
This is a known GitHub bug, but GitHub is not in an hurry to fix it.
This is a workaround that consider merged pull request as closed.
Fixes MERGIFY-ENGINE-26Z
Change-Id: Ie2c44ce9c049a6c786290834e6da7614104ab9a2
Change-Id: I82989fb9562ff085c2089ed03a55e3c93f2db610
> fix: workaround to detect closed PR

- mergify_engine/duplicate_pull.py
Correctly retry with a new token if no bot account are provided.
Or report the error to the user if a bot account is used.
Fixes MERGIFY-ENGINE-289
Fixes MERGIFY-ENGINE-281
> fix: duplicate auth error

- mergify_engine/worker.py
We don't proceed push events in a timely fashion, remove them to events
latency metric.
Change-Id: Iee0be6186bd18965b54ca4329c814f447cd6f9ae
> feat(worker): split avg:engine.streams.events.latency metric

- .mergify.yml
This is covered by https://docs.github.com/en/code-security/secret-security/about-secret-scanning
> ci(mergify): disable GitGuardian requirements

- mergify_engine/worker.py
This changes the meaning of buckets.read_size it becomes the number of
pull request processed, the number of events read by pull request become buckets.events.read_size
Change-Id: I7316dd6f65316c7cc47ba027ee3a6bde8a8f4da7
> feat(worker): change meaning of buckets.read_size and introduce buckets.events.read_size

- mergify_engine/engine/__init__.py
- mergify_engine/worker.py
No need to keep all of that in memory.
Change-Id: I4b1ef73eb3d54d1e8b72796d245601d1309bc593
> fix(worker): free Context().sources when engine.run() finish

- .github/workflows/ci-docs.yaml
- .github/workflows/ci.yaml
- .github/workflows/docs-upload-gh-pages.yaml
setup-node doesn't support caching of sub directory
Change-Id: I1cd2e0394af2845c18104e9ad1db33c2ef823369
Change-Id: Ibb66baaaefd4d48dea37c4894fa432a7b7ec79a9
Change-Id: Ieeafdf5a1edd2f03f0ce3379474ab3878fec4cd0
> fix(docs): yarn caching

- mergify_engine/worker.py
All retries (Network, 50X, ...) are 1 minutes except 403 at 3 minutes.
With 3**min(x, 3) * 1 minutes its means we retry at 3, 9, 27, 27, ...
This changes it to 2 ** min(x, 3) * 1 minute  its means we retry at 2, 4, 8, 8, ...
Change-Id: Id73e298b12dac4bc41edd5a1cd7ee7f75c8554d4
> fix(worker): be a bit more aggressive for retry

- mergify_engine/rules/__init__.py
- mergify_engine/tests/unit/rules/test_rules.py
When rule are duplicate we must copy the value_expanders of the filter,
otherwise future evaluation cannot resolve teams.
Change-Id: Ice7005f14f65d8060d02ac505dbafc6bbcf9ab3c
> fix(rules): duplication

- mergify_engine/queue/merge_train.py
- mergify_engine/tests/unit/test_train.py
While it's in theory not possible, a bug make it possible
https://github.com/Mergifyio/mergify-engine/pull/2958
This change cleans up the mess automatically.
Change-Id: I76978db7408e57c9e16372b490bd848734b4b74c
> fix(queue): automatically remove pull queued multiple times

- mergify_engine/queue/merge_train.py
This will naturally drop old data from the payload
Fixes MERGIFY-ENGINE-297
Fixes MERGIFY-ENGINE-298
Change-Id: I9d0346de4b59d10563257e61fdc7a3a12b719767
> fix(queue): use explicit names to deserialize data

- mergify_engine/actions/copy.py
User didn't like the current message "Backport failed." even
we quickly categorize the error when this occurs.
This change reports the reason to users, this make them happy and help
to known if we already correct/categorize that one or not.
Change-Id: I99d163634a717b6e191523500edb2e8caed751b2
> fix(duplicate): report git error even if not categorized

- mergify_engine/actions/merge.py
- mergify_engine/actions/merge_base.py
- mergify_engine/actions/queue.py
- mergify_engine/context.py
- mergify_engine/engine/actions_runner.py
- mergify_engine/engine/queue_runner.py
- mergify_engine/queue/merge_train.py
- mergify_engine/rules/__init__.py
- mergify_engine/rules/live_resolvers.py
- mergify_engine/tests/functional/test_engine.py
- mergify_engine/tests/unit/actions/test_merge.py
- mergify_engine/tests/unit/actions/test_queue.py
- mergify_engine/tests/unit/rules/test_rules.py
- mergify_engine/tests/unit/test_behind.py
- mergify_engine/tests/unit/test_command.py
This updates the rule conditions objects to able multiple
context.PullRequest object at once.
This will be used for check the queue rules with future batch features.
Change-Id: Id33ce6830d92aa49f3f630b3714085bbde47cf19
> refactor(rules): allow to parse multiple pull requests

- mergify_engine/worker.py
This has been dropped during the big streams to buckets migration.
Just reintroduces it.
Change-Id: I80a7e49dd92025f957a2951935f60785000eda10
> chore(http): set the client request ratio

- mergify_engine/tests/functional/actions/test_queue.py
Depending on how fast the record is, the number of commits can be 5 or
6. The rebase of the first PR in queue may has been done or not in the
meantime.
This only occurs during recording.
Change-Id: Iaf02d8c0a0ed1e8860ad68716695190ee6845765
> chore(tests): fix flaky tests

- mergify_engine/actions/merge_base.py
- mergify_engine/engine/commands_runner.py
- mergify_engine/rules/__init__.py
- mergify_engine/tests/functional/actions/test_queue.py
- mergify_engine/tests/unit/actions/test_merge.py
- mergify_engine/tests/unit/rules/test_rules.py
This change the ways we evaluate multiple pull requests.
This permits to keep the evaluated filter tree for each pull request.
This will allows to create a better summary for queue rules with batch.
Change-Id: I76990df1f6e50eb1a30c89a992d85f5f2c577a6e
> fix(conditions): fix evaluation of multiple pull requests

- .github/workflows/releaser.yml
Tools to release `main` branch from a GitHub Workflow
To release a new version use:
* gh workflow run Releaser
Change-Id: Ib37c2df8917e5f711bb8405c89dc5372daa20530
> ci: add releaser GitHub action

- .github/workflows/releaser.yml
The GITHUB_TOKEN is not allow to trigger other workflows.
So the docker image build (workflow triggered with `on: [tag]`) is not
run.
This change uses a Deploy key. So when the workflow uses `git push`,
associated workflow will be ran.
Change-Id: I645f54912c68a3f4d453b8a83b2a869b8611c0bb
> ci(releaser): use ssh key to checkout code

- mergify_engine/tests/unit/test_gitter.py
If the user has a language set to not English, the test will fail because the
error string is translated.
> test: make sure gitter is tested with LANG=C

- mergify_engine/engine/commands_runner.py
- mergify_engine/tests/unit/test_command.py
950753e26 has introduced a regression making mergify anwser to some
comments it shouldn't.
Change-Id: I3d86274118e9017e42384973e53d4c375bc2e567
> fix(command): only react to @mergifyio

- .mergify.yml
If the hotfix rule and the normal rule match, the only the first one
run. So move the hotfix first.
Change-Id: I5ac7bdebd173d90b5af7fd52c0bcad77f3042e45
> ci: move hotfix rule on top

- .github/workflows/releaser.yml
This allows to run the changelog generation without pushing a tag
Change-Id: I0e0ee917eca12f47ba98fdcf160deaef77559f81
> ci(releaser): add dry_run flag

- mergify_engine/gitter.py
As documented https://www.git-scm.com/docs/api-error-handling
128 means git die, so if we didn't handle the git message with a better
exception we must just report the output as fatal.
Related #1654
Change-Id: I4f1131195a767db4981137f4d41b409875a5c411
> fix(gitter): report all git errno 128 error as fatal

- mergify_engine/queue/__init__.py
- mergify_engine/queue/merge_train.py
- mergify_engine/queue/naive.py
- mergify_engine/tests/functional/actions/test_queue.py
- mergify_engine/tests/unit/test_train.py
This is not needed anymore, we always have the last version of the
configuration everywhere now.
Fixes MRGFY-522
Change-Id: I8fe7fe9ad4baf1a4a6b82bfb29052c87247657e5
> chore(queue): don't store queue rule config in redis

- mergify_engine/duplicate_pull.py
If a GitHub outage occurs, temporary auth issue, the cherry-pick command
failed and the git tree has no staged change or new commit. In such case
we assume the change is already part of the branch which is wrong.
This changes reraise all known git issue to ensure their are retried or
reported correctly.
Related #1654
Change-Id: Ib99c4a8354fa0bf2b26740be5a7a682020bae045
> fix(backport/copy): ensure cherry-pick are retried/reported correctly

- mergify_engine/queue/merge_train.py
If the train car has no parent pull requests, we built sentence like:
`The pull request embarked with  and master (6b13c3d) is mergeable`
This change removes the useless ` and`
Change-Id: Ia647f1660a3f6195d68cfaca5d3c8b1d37b916c8
> fix(queue): fix summary title with one ref

- mergify_engine/actions/merge.py
- mergify_engine/actions/merge_base.py
- mergify_engine/actions/queue.py
If merge_base.run() returns failure and on next engine run conditins
unmatch, when we run cancel()if one of the CI is pending we wait it
finish. But since the pull request in not in queue we don't need to
wait, we can cancel the action instantly.
Fixes MERGIFY-ENGINE-1WK
Change-Id: I31c0ed175b2dcdea1a5ddc6ea5bf08739db18c8b
> fix(queue/merge): don't process queue if pull is not queued

- .github/workflows/releaser.yml
We currently install the python lib called pandoc instead
of the pandoc binary.
Change-Id: Iff4943a752156af32b25aa821ddba7085e06aabf
> ci(releaser): install pandoc correctly

- mergify_engine/count_seats.py
- mergify_engine/tests/functional/test_count_seats.py
- mergify_engine/tests/unit/test_count_seats.py
- mergify_engine/web/root.py
It doesn't make sense to return all organizations as we select one.
This change returns only the list of repositories.
Related MERGIFYIO-14F
Change-Id: I21608bf0b524af882f7866e75aa769be3b42ea6f
> feat(seats): rework dashboard api

- mergify_engine/gitter.py
Unfortunatly, there is case where valid cherry-pick failure return 128
So we can only rely on the message.
Fixes MERGIFY-ENGINE-2A9
Change-Id: Ibe359f7ff689cc5c0db25c040daac87d781313c3
> fix(gitter): don't rely on return code

- mergify_engine/actions/__init__.py
- mergify_engine/actions/assign.py
- mergify_engine/actions/backport.py
- mergify_engine/actions/close.py
- mergify_engine/actions/comment.py
- mergify_engine/actions/copy.py
- mergify_engine/actions/delete_head_branch.py
- mergify_engine/actions/dismiss_reviews.py
- mergify_engine/actions/label.py
- mergify_engine/actions/merge_base.py
- mergify_engine/actions/post_check.py
- mergify_engine/actions/rebase.py
- mergify_engine/actions/refresh.py
- mergify_engine/actions/request_reviews.py
- mergify_engine/actions/review.py
- mergify_engine/actions/squash.py
- mergify_engine/actions/update.py
- mergify_engine/engine/actions_runner.py
- mergify_engine/engine/commands_runner.py
Relying on boolean shared with a baseclass is confusing, we don't really
known how the action behave.
This change uses enum.Flag instead of boolean to track the behavior of
an action in an explicit fashion.
Change-Id: Icc63fc95c4177349dfdd4c0e7e3211de816192ee
> refactor(action): make all action flags explicit

- mergify_engine/context.py
- mergify_engine/date.py
- mergify_engine/rules/filter.py
- mergify_engine/rules/parser.py
- mergify_engine/tests/unit/rules/test_filter.py
- mergify_engine/tests/unit/rules/test_parser.py
- mergify_engine/tests/unit/test_date.py
datetime.time can't be compared if the tzinfo differ.
This patch creates a intermediate representation to build a
datetime.datetime for the comparison.
Fixes MERGIFY-ENGINE-2AE
Change-Id: I5f32c42d2a0b203577f0c934cdc7c308385dd97c
> fix(timezone): comparison of current-time

- mergify_engine/context.py
- mergify_engine/tests/functional/test_attributes.py
- mergify_engine/tests/unit/test_context.py
This was creating useless update of the summary just because the set was
not always have the same order.
Change-Id: I5a80a40d0396468975c999430154b4d4512b992a
> fix(depends-on): make the order predictable

- mergify_engine/tests/functional/base.py
Otherwise preemption doesn't occur at the same moment during record and
replay. Making some tests working during record and failing during
replay.
Change-Id: Ife97bc0a4a14d189c9b5393ce677e4453fe7c515
> fix(tests): don't preempted bucket consumption

- mergify_engine/date.py
date.Time(8, 5) means today at 8:05:00.0, so we must set second
and microsecond to 0 otherwise we got those from utcnow() method.
Change-Id: Ib552a51ed12553330ccad71e94abba8c3dc9a17c
> fix(schedule): drop second and microsecond from date.Time()

- mergify_engine/clients/github.py
- mergify_engine/clients/http.py
- mergify_engine/debug.py
- mergify_engine/web/auth.py
The dashboard HTTP client uses the default httpx timeout (5 sec) instead
of our custom timeout settings (5 sec for connect and 10 sec for read).
This change moves the default headers/timeout into our AsyncClient base
class so any instantiation will have the correct values.
Fixes MRGFY-589
Change-Id: I5effc27a982fc6d23eea3a4ce34980ab34dae798
> fix(http): use same timeout everywhere

- mergify_engine/engine/__init__.py
Clearing redis when pull request is closed is useless, as we
recreate it at the end of the engine run.
This change removes the manual deletion, redis is already cleaned
automatically after 30 days of inactivity.
Change-Id: I4ec11c4f01c52e49f28e5549a1dec0178e3f22d6
> chore(summary): don't manually clear summary sha one cached from redis

- tox.ini
Some tests (batch tests) timeout when getting recorded, we should extend the timeout delay to be able to record them fully.
> fix(record): extend record timeout delay to avoid timeout on specific batch tests

- mergify_engine/rules/conditions.py
`#review-requested=0` is not a perfect match for CODEOWNERS.
Users are more annoyed by the strict meaning of our version (pull
request not queued, because non CODEOWNERS review are requested) than
seeing the benefice of the issue we are trying to solve.
Change-Id: Ib9e9a61586d4d7683f7a7fe4f23722a274ae1fc9
> fix(branch-protection): remove support for code-owners

- mergify_engine/context.py
This can be used by e.g. the tracer, so let keep it simple.
> refactor(context): simplify __str__

- .github/workflows/ci-record-fixtures.yaml
Don't yet run it every day, just add a manual trigger for now.
Change-Id: Icf3514a00820532b4433d76e41afeb6f48d60c2e
> ci(record): add job test fixture generation

- docs/source/spelling_wordlist.txt
Aspell and Hunspell have some conflicts regarding some words spelling. It causes different versions of Os to find new words being 'misspelled'.
Fixes MRGFY-667
> fix(dictionnary): adding all words not recognized by fedora 34

- mergify_engine/tests/functional/actions/test_queue.py
- mergify_engine/tests/functional/api/test_auth.py
- mergify_engine/web/api/root.py
- mergify_engine/web/root.py
The final url looks better.
We don't need to rewrite url, just the domain.
It's good practice to have major api version in the url path.
> feat(api): put version in API url

- mergify_engine/actions/delete_head_branch.py
I remember some 422 are like 404, but not all. Since we didn't put the
detail, return an error in case of 422.
For example, protected branch may return a 422, and this should be
reported to the used.
> fix(delete_head_branch): don't catch 422

- mergify_engine/worker.py
This change ensures we will process an organization within the same
worker even if its login change.
> fix(worker): hash the owner id instead of the bucket name

- mergify_engine/queue/merge_train.py
- mergify_engine/tests/unit/test_worker.py
- mergify_engine/web/api/queues.py
- mergify_engine/web/legacy_queue.py
- mergify_engine/worker.py
- mergify_engine/worker_lua.py
- releasenotes/notes/queue-storage-change-4f8d1b26eaf9e266.yaml
Instead of having one key per trains, this change uses a hash per
organization and then one key per repo_id/ref.
Since we use iter_trains() more often than before this should load train
faster that before.
Also compared to SCAN, HSCAN also load values, so we also remove one
round-trip to retrieve the data.
Fixes MRGFY-714
> fix(queue): use hash to store trains

- mergify_engine/queue/merge_train.py
- mergify_engine/worker.py
Now during the merge trains refresh if a repository is missing we delete
the trains.
This will stop blocking the merge-queue when a repository is no more
accessible and the merge-queue exists.
This will stop to report this repository in merge queue API.
Fixes MRGFY-531
> fix(queue): don't fail to iter trains when repo is missing

- mergify_engine/exceptions.py
yaaredis.exceptions.ResponseError was reported as failure in some
actions instead of been retried.
For queue action, this has marked the merge as failure, but because of
the OOM, the train was not updated...
This change will be retried like when Redis is down, to not report false
status on actions.
> fix(action-runner): retry event on redis OOM

- mergify_engine/worker.py
This makes workers unit tests failing randomly a lot.
> fix(worker): stop workers correctly

- mergify_engine/web/api/queues.py
This state only stay one second before we remove the pull request from
the queue but exists, so, we must handle it.
Fixes MERGIFY-ENGINE-2ER
Change-Id: Ibed78646b3e0c3dad8acb80f42ebb4738650fd80
> fix(api): handle case where car creation failed

- .github/dependabot.yml
production type does not work for some reason, so try direct mode.
Change-Id: I81881a76399da11f52e53569f75de3aa91d8e9d0
> chore(deps): mark react-scripts has direct deps only

- .github/workflows/semantic-pull-request.yaml
`**` in branches-ignore does not catch `/`, so we add the merge-queue
target branch to only catch pull requests numbers.
Change-Id: I81ba671d81f6380888c6871540e8c4adffdcbad6
> ci(semantic-pr): don't run it on merge queue

- mergify_engine/clients/github.py
> refactor(clients): remove http.client.request.time metric

- mergify_engine/actions/utils.py
- mergify_engine/context.py
- mergify_engine/tests/unit/test_context.py
- mergify_engine/tests/unit/test_utils.py
- mergify_engine/utils.py
This data is not going to change often we can keep it for the life time
of a context (maximum 30s).
Fixes MRGFY-750
Change-Id: Id3dabe978c4a826d1eb8fc7e6589ecc4b9a2cfba
> feat(context): cache user/teams permissions

- mergify_engine/actions/merge_base.py
- mergify_engine/rules/conditions.py
- mergify_engine/rules/filter.py
- mergify_engine/tests/unit/rules/test_get_rule_checks_status.py
Instead of the heuristic that looks only for `check-success=XXX`.
This creates a Filter that introduces a new possible result
`IncompleteCheck`.
The filter has a different meaning for or/and when boolean are combined
with IncompleteCheck:
* or cannot return false if at least one is IncompleteCheck
* and cannot return false if at least one is IncompleteCheck
To compute if a check conditions is final or not, this change adds an
hook in Filter before the evaluation of the condition to return IncompleteCheck
if need instead of the real evaluation outcome.
Fixes MRGFY-729
Fixes MRGFY-730
Fixes MRGFY-731
Fixes MRGFY-736
Change-Id: I1ce946161bc1acafbc23fbfa00fb88e5baf30875
> fix(queue/rules): use a Filter to found pending/final checks

- mergify_engine/rules/filter.py
- mergify_engine/tests/unit/rules/test_get_rule_checks_status.py
IncompleteChecksFilter use binary_op in the reverse way.
It works for all ops except regex that need to have the regex as second
argument.
This fixes that.
Fixes MERGIFY-ENGINE-2FJ
Change-Id: I37eb167ab80178e0e70d8a192d42826b93987d9c
> fix(rules): fix regex conditions

- mergify_engine/tests/functional/test_count_seats.py
On GHES, the order differs.
Change-Id: Idb3f26ffac4f51f26bccd3b5a50aa7b906396259
> fix(tests): sort some data before comparaison

- mergify_engine/rules/filter.py
- mergify_engine/tests/unit/rules/test_filter.py
The current refresh date for `RelativeDatetime()` was wrong. As it's
relative to now (e.g.: XX days ago), the refresh date should always be
the attribute date + XX days
Fixes MRGFY-776
Change-Id: I5d2e4fd7f13cac492672df744978b84adc628cea
> fix(delayed-refresh): relative datetime calculated refresh date

- setup.cfg
0.920 has been released, but pydantic.mypy plugin is not compatible
cap mypy until pydantic get updated.
https://github.com/samuelcolvin/pydantic/pull/3175
Change-Id: Idd714099c176a26db873ed4cfc0187f443ddfb2e
> chore(deps): cap mypy

- mergify_engine/queue/merge_train.py
If user asks to always have a draft PR, just do it even if this looks
useless.
Change-Id: Icdd1a4fa0150c98d12f83c657086dc04db1d92ac
> fix(queue): don't try to be smart about inplace behavior

- mergify_engine/clients/github.py
- mergify_engine/config.py
- mergify_engine/debug.py
- mergify_engine/github_events.py
- mergify_engine/logs.py
- mergify_engine/tests/conftest.py
- mergify_engine/tests/functional/test_count_seats.py
- mergify_engine/tests/unit/test_clients.py
- mergify_engine/tests/unit/test_github_events.py
- mergify_engine/web/auth.py
- releasenotes/notes/api-url-change-fccbdb37e6085a39.yaml
The graphql endpoint of GHES is /api/graphql instead of /graphql.
This introduce new environment variables to configure it.
Fixes MRGFY-788
Change-Id: I084cfe2631180fabd4609a26effe050c3fda5f4a
> fix(ghes): make graphql call working

- mergify_engine/actions/review.py
Currently when bot_account is used, reviews are posted in loop.
Add some debug to understand why.
Change-Id: I9dafd056725229f91eb36951fb1a8bdf342c12bb
> chore(review): bot_account debug

- mergify_engine/context.py
- mergify_engine/rules/filter.py
- mergify_engine/tests/unit/rules/test_filter.py
The current code was using quirk on a Context side when the value
of an attribute was unknown or None.
This change implements None correctly in filter operators. So we can
return None from context, then evaluation and near datetime works as
expected.
Fixes MRGFY-780
Change-Id: I4dfa76477f61ea0b17ed8d386d662244d4c256e1
> fix(filter): handle None value

- mergify_engine/tests/unit/test_worker.py
- mergify_engine/worker.py
- mergify_engine/worker_lua.py
This change will allow dropping repo_name and owner_login from Redis
keys without losing logging/tracing information.
Depends-On: #3821
Change-Id: I84189a340e6f458adad09bafade40f6c8ed06717
> refactor(worker): Don't use login/repo from Redis key for tracing/logging

- mergify_engine/migrations/__init__.py
- mergify_engine/redis_utils.py
- mergify_engine/tests/conftest.py
- mergify_engine/web/redis.py
- mergify_engine/worker.py
Since we use pipeline with redis script, if script loading may fail as
the ScriptError is not raise when we use evalsha(), but a generic error
is raise during the pipeline execution.
Instead, this change loads script on startup.
Depends-On: #3821
Change-Id: Id47d234cbb0447d94b4d54c3fc6268122dfae1f9
> fix(redis): load redis script on startup

- mergify_engine/context.py
- mergify_engine/queue/merge_train.py
- mergify_engine/tests/unit/test_context.py
GitHub has changed the eol character in the UI, yes you correctly read it!
Body edited with UI has \r\n. Via API it have exactly was you sent.
Looks at body on old PR #3237, then on new PR #3821.
Since this breaks our multiline regex assumptions, this change replaces
all \r\n to \n.
Change-Id: I0b8bbc4d2acbb215626cc03d58fdf19deaa3554c
> fix(depends-on): support when body has CRLF instead LF eol

- mergify_engine/github_events.py
- mergify_engine/migrations/cache/0002_remove_pull_request_sha_number_cache.redis
- mergify_engine/tests/unit/test_github_events.py
- mergify_engine/tests/unit/test_migrations.py
- mergify_engine/worker.py
Since we always get the list of open pull requests, storing
the mapping between sha and number is useless.
Change-Id: Ie004f4007cd37d665e08e7897b8b57dc0fde2d57
> chore(github-events): remove useless cache

- docs/source/configuration.rst
Without the final `/` it tries to redirect.
> docs: fix endpoint for config validation

- mergify_engine/tests/unit/test_worker.py
- mergify_engine/worker.py
- mergify_engine/worker_lua.py
In the road to remove login/name from Redis keys.
This change will allow supporting old and new bucket names.
Related MRGFY-697
Change-Id: Idad39880651a5da832a1fe7430e0a0f06295c23e
> refactor(worker): don't use owner/repo to cleanup buckets

- docs/source/actions/queue.rst
- mergify_engine/actions/merge.py
- mergify_engine/delayed_refresh.py
- mergify_engine/queue/merge_train.py
- mergify_engine/queue/naive.py
- mergify_engine/rules/__init__.py
- mergify_engine/tests/functional/actions/test_queue.py
- mergify_engine/tests/unit/test_train.py
- mergify_engine/web/api/queues.py
- releasenotes/notes/batch_max_wait_time-362c3db513f48cb2.yaml
This change introduces a new queue_rule option `batch_max_wait_time`.
If set, the construction of the temporary pull request is postponed.
This leverages the delayed-refresh mechanism to retrigger the engine
when we waited enought time to proceed the batch.
Fixes MRGFY-781
Change-Id: I58166215b417043096baea446366553ab497d255
> feat(queue): add batch_max_wait_time

- mergify_engine/queue/merge_train.py
GitHub may returns None for these attributes
We previously displayed "None" in the checks list.
The new code raises an error.
Fixes MERGIFY-ENGINE-2H3
> fix(queue): statuses information may be None

- mergify_engine/actions/queue.py
After we rebase pull requests in-place if something gets merged manually
at a particular timing, the queue can be stuck has Mergify didn't check
one last time before merging the pull request that the pull request is
up-to-date, it blindly trusts the QUEUE_SUMMARY generated for the previous
base sha.
This change adds new control of is_behind, and the pull request will
be rebased one more time.
Fixes MRGFY-822
> fix(queue): control is_behind one last time before merging a pull request

- mergify_engine/engine/actions_runner.py
- mergify_engine/tests/unit/engine/test_action_runner.py
This change improves the rule removal cleanup to handle the case
where the pull request has been synchronised (no more check-runs).
The old code was using check_runs from GitHub, the new code only rely
on the diff between the current and the previous state.
Fixes MRGFY-836
Change-Id: I1c7f8a5e718262d5c210a33e405e905071775b2a
> fix: improve rule removal cleanup

- mergify_engine/worker.py
running xlen on all opened PRs doesn't scale.
Fixes MRGFY-841
Change-Id: Ia8d00e1665487f839180331bd9eae1311efc8a4b
> chore(worker): remove engine.buckets.events.count metric

- installer/package-lock.json
- installer/package.json
It's deprecated, use eslint-plugin-import order rule instead.
Fixes MRGFY-852
Change-Id: I7fab956f15346d3b6918119ad07f688735444227
> chore(deps): drop eslint-plugin-import-order-alphabetical

- mergify_engine/date.py
- mergify_engine/tests/unit/test_date.py
The current code doesn't prepare date with correct offset.
It was only working if the offset endup the same day, not if it
resulting date should be the next day.
Fixes MRGFY-869
Change-Id: I916c6cc353f11d0f524ee67569db7f294f3dd21d
> fix(timezone): compute correct the current-time with TZ

- mergify_engine/worker.py
When the repository is archived, we ignore new events from GitHub
webhook, but we might have some events on the worker side waiting to be
proceed.
This change drops them.
Fixes MERGIFY-ENGINE-2J0
Change-Id: I63bc2b0ee30cf6cb888cacc459b1e0201ca21c41
> fix(worker): ignore pull request on archived repo

- mergify_engine/tests/functional/base.py
- mergify_engine/tests/unit/test_worker.py
- mergify_engine/worker.py
This will allow spawning dedicated tasks and shared tasks in different workers/processes.
Fixes MRGFY-887
Change-Id: I855cec767da4bcbe93b02635c0d83327eb14c755
> refactor(worker): allow to separate dedicated worker

- tox.ini
removing "--pyargs mergify_engine" in tox.ini pytest requests
Fixes MRGFY-895
> fix(test): remove arguments from pytest requests

- mergify_engine/actions/queue.py
This should avoid merging PR if summary is out of date.
Fixes MRGFY-902
Change-Id: Ia3f97a5db2da24dc5323f9a34c122d17ded82e54
> fix(queue): don't rely on GitHub Check-runs to merge PR

- mergify_engine/tests/unit/api/test_exceptions.py
- mergify_engine/tests/unit/conftest.py
- mergify_engine/web/api/root.py
- mergify_engine/web/config_validator.py
- mergify_engine/web/legacy_badges.py
- mergify_engine/web/root.py
- mergify_engine/web/simulator.py
The Github rate limit exception was raised by the engine but unhandled by the REST API thus
sending back a code 500. This fix now handles the exception and sends back a 403
code and an error message. 
Fixes MRGFY-882
> fix(api): return 403 error when github rate limit exception raised

- mergify_engine/tests/unit/api/test_exceptions.py
- mergify_engine/web/config_validator.py
- mergify_engine/web/legacy_badges.py
- mergify_engine/web/root.py
- mergify_engine/web/simulator.py
We used one app per sub directories just to not expose CORS everywhere.
It's really useful, so just merge all of them.
Related MRGFY-906
Change-Id: Ia9fa5fac4d8f6889a93f192eb0ac11e902e4a3ed
> refactor(web): use only one FastAPI app

- mergify_engine/web/api/root.py
- mergify_engine/web/root.py
- mergify_engine/web/utils.py
This adds the Redis exception handler on the FastAPI API app.
Change-Id: I3db3f8529438e1d25a9cf913fd553a9c978ad000
> fix(web): use Redis exception handler on API

- mergify_engine/tests/functional/base.py
`FunctionalTestBase.protected_branches` is not used anymore and cause
some issues during teardown.
This change removes it.
Change-Id: Idf6fcaa8a03431254d51956396139fb1245edaa5
> chore(tests): remove dead code

- mergify_engine/logs.py
This attributes are missing in datadog logs.
Change-Id: Iee17592bdc504d9523ee2e6c24b7ca77f3dd6fff
> fix(logs): add missing dyno/dynotype to datadog records

- mergify_engine/tests/functional/base.py
- mergify_engine/tests/unit/test_worker.py
- mergify_engine/worker.py
The set DEDICATED_WORKERS_KEY can change only every 1 minute. And it
doesn't change so often in reality.
This change creates an in memory cache of this list in all processes and
sync it from Redis every 30s.
Fixes MRGFY-917
Change-Id: Ic44bfea7bfecafd3b55813c6920a7c78711bdd0a
> refactor(worker): avoid calling sismembers too many times

- mergify_engine/tests/unit/test_worker.py
- mergify_engine/worker.py
Our worker can use any hash method to shared the load. We don't really
care about the collision, but alot of tooling complain about using md5 for
good reason.
So, I have done a quick and dirty bench to select the new one
and pick blake256 as it's as fast as md5 and tooling will not complain
anymore.
Fixes MRGFY-924
```
import hashlib
import timeit
def t(method):
for i in range(0, 1000000):
f = getattr(hashlib, method)
hashed = f(str(i).encode())
shared_id = int(hashed.hexdigest(), 16) % 60
return f"shared-{shared_id}"
def do(method):
elapsed = timeit.timeit(f"t('{method}')", globals=globals())
print(f"{method}: {elapsed}s")
do("md5")
do("sha256")
do("sha3_256")
do("sha512")
do("sha3_512")
do("blake2s") # blake256
do("blake2b") # blake512
```
md5: 1.5114598810032476s
sha256: …
> fix(worker): use blake512 for hashing

- mergify_engine/queue/merge_train.py
We must reraise the original exception, to propage the right exception
above.
Fixes MERGIFY-ENGINE-2HC
Change-Id: Iac786170691da60fb20ee94cac57c85d30641da3
> fix(queue): reporting of base not found error

- mergify_engine/engine/actions_runner.py
The summary changes/unchanges logging start to become big on certain
users and the log got truncated.
This changes split in in two logs lines.
Change-Id: If502668b1348ef14ebe32ef517c7c4fcaf61fc49
> refactor(action_runners): split summary logging

- Dockerfile
- tox.ini
This fixes semgrep rule generic.ci.security.use-frozen-lockfile.use-frozen-lockfile-pip
Change-Id: I4ce5952921fc05a1530fa85bbc7d6143c1930fe0
> ci(semgrep): disable pipenv warning

- Dockerfile
Fixes semgrep generic.ci.security.use-frozen-lockfile.use-frozen-lockfile-npm
Change-Id: I885b26cdcff7bd6757fb57b7aa0cde131ad3ba6f
> fix(installer): use npm ci, instead of npm install

- mergify_engine/rules/conditions.py
In GitHub branch protection "required_pull_request_reviews" may not
exists or, exist and set 0. It depends of if we get the branch protection from
branch endpoint or branch/protection endpoint.
This change handles the later.
Fixes MRGFY-928
Change-Id: I3c4a1eceeda235d661cd8567b66d1ee367dbf444
> fix(branch-protection): don't wrongly inject required_pull_request_reviews

- mergify_engine/worker.py
Since we have merge Train MergeableStateUnknown can be raised outside
the context of the engine run (bucket_sources_key is not set).
MergeableStateUnknown we should not raise OrgBucketRetry but PullRetry.
OrgBucketRetry has a huge backoff, while PullRetry does not.
This exception is raised often on big repositories and slowdown a lot the events processing.
Fixes MERGIFY-ENGINE-2JQ
> fix(worker): always raise PullRetry on MergeableStateUnknown

- mergify_engine/context.py
- mergify_engine/rules/types.py
- mergify_engine/tests/functional/base.py
- mergify_engine/worker.py
Currently, we use repository.get_pull_request_context() to load context
of pull requests in queue. This method ensures GitHub has finished to
background processing. The background processing is required by
Mergify only for queue/merge actions code and conflict detector, not to
generate the fancy summary of the merge queue.
Waiting on GitHub background processing may fail, Mergify raises
MergeableStateUnknown in such case. When we refresh the train this has a
unwanted side effect:
* We create a draft PR
* fail to generate the merge-queue summary and raise the exception
* Train state is not saved as we fail the creation of the TrainCar.
* The events maybe kept in queue because the worker retry when it sees MergeableStateUnknown
* This Exception land in OrgBucketRetry, so the backoff is …
> fix(queue): don't wait for mergeable_state to compute the status

- mergify_engine/rules/conditions.py
We old branch API to get branch protection strict key is missing.
Fixes MERGIFY-ENGINE-2JV
> fix(merge): handle when branch protection come from old API

- mergify_engine/context.py
- mergify_engine/tests/unit/test_context.py
We need to raise a Jinja exception to get the error reported
correctly.
Fixes MERGIFY-ENGINE-2JW
Fixes MRGFY-945
Change-Id: Icdbd6f11931db107a731ec31c8c77675769bc10e
> fix(template): raise correct exception

- mergify_engine/rules/__init__.py
The queue already has code to ensure we are up2date whatever the state
of branch protection.
Injecting #commits-behind=0 may not work when you use batch +
speculative checks as when the first batch is merged, the second because
out of date from GitHub point of view as all sha1 are not the same.
This has not been catched by tests because, this need a certain timing to have #commits-behind=0 evaluated to false before the seconds TrainCar has finished to be tested but before the first one has been merged or half merged.
This change drops this useless restriction.
Change-Id: I1c8153c5729000e57940bcb5e9e5e78ce0fede64
> fix(queue): don't enforce strict mode for merge-queue

- .github/workflows/updatecli.yaml
/tmp may got cleaned up during the job run... GitHub workflow must use
runner.temp instead.
Change-Id: Id94db43c3bbe49c97dd92824a2d0e89d92087a30
> ci(updatecli): GitHub workflow must use runner.temp instead of /tmp

- tox.ini
GITHUB_ACTIONS must be passed to pytest to get annotations generated.
Change-Id: I68ca73924851bfec56a3e974ffde49ecc33c7b61
> ci(tox): enable pytest github actions annotations

- mergify_engine/rules/__init__.py
Sometimes, YAML.safe_load() takes too long to resolve.
In order to monitor which client is impacted, we need to
trace back the runtime of the function by decorating it
with a tracer span.
Fixes MRGFY-922
> feat(datadog): add tracer for YAML safe_load

- mergify_engine/queue/merge_train.py
- mergify_engine/tests/unit/test_train.py
This allows different allow_checks_interrupt per queue.
Fixes MRGFY-950
Change-Id: I8bf500347f33e23253fd26d42fa1c6b677944517
> fix(queue): fix interruption with high priority queue allow it

- mergify_engine/queue/merge_train.py
Old Redis data must be updated to migrate from allow_checks_interruption
to disallow_checks_interruption_from_queue.
Fixes MERGIFY-ENGINE-2K7
Change-Id: I84e3c7cd6a697c47c55a97c82a2ac322a9fb29e3
> fix(queue): backward compat of compat allow_checks_interruption

- mergify_engine/date.py
- mergify_engine/tests/unit/test_date.py
This allows things like "30s" which are quite natural.
This allows to use mins? for minutes too.
> fix(date): allow for no space between number and units

- mergify_engine/tests/functional/test_attributes.py
As GHES is slower than GitHub.com, we need to wait for the background
processing of mergeable_state for this test.
Change-Id: I65f159d0814802b5cb4308f16113a5f0632db802
> fix(ghes): is_behind need to wait against background processing

- mergify_engine/context.py
The code was already there for slug only team, but not for fully
qualified teams.
Fixes MRGFY-997
Change-Id: Id33fd3d68b68fc57f9bd905feb998b7b5d7b0077
> fix(request-reviewers): support long team names

- mergify_engine/config.py
- mergify_engine/crypto.py
- mergify_engine/tests/unit/test_crypto.py
Crypto in engine is only for encryting data dashboard cached. We can
just temporary try to decode the data with an old key for the rotation.
The whole cache is re-validated every 3600 and the retention is 3 days.
So we just have to wait 3 days and we are sure all encrypted data are
encrypted with the new key.
Fixes MRGFY-956
> feat(crypto): Add mechanism to rotate oauth tokens SECRET

- mergify_engine/tests/functional/api/test_queue_freeze.py
- mergify_engine/web/api/queues.py
The endpoint was a bit confusing, mentioning `DELETE /unfreeze` where
it should be `DELETE /freeze`.
Fixes MRGFY-1000
> refactor(api): change endpoint url for queue freeze deletion

- mergify_engine/web/api/queues.py
The endpoint was returning None, because by default FastAPI uses JSONResponse,
the value None was converted to `b'null'` and thus raising an error because no content
was expected.
Fixes MRGFY-999
Fixes MERGIFY-ENGINE-2KN
> fix(api): queue_freeze delete request with response's content size error

- mergify_engine/queue/merge_train.py
- mergify_engine/tests/unit/test_train.py
We must cleanup all trains when we remove a pull request from the queue.
In case of the base branch changed while the PR is in queue.
Fixes MRGFY-885
Change-Id: I01970d655f5564c8b09f3a1d8c25759941e784b1
> fix(queue): ensure queue is not in another train

- mergify_engine/duplicate_pull.py
If a backport already exists and the main branch move.
The git complain because update of backport branch is not fast foward.
In such case we should report the backport already exists instead of
retrying for ever.
Fixes MERGIFY-ENGINE-2KJ
> fix(duplicate): don't retry non-fast-forward update

- mergify_engine/queue/merge_train.py
- mergify_engine/web/api/queues.py
- mergify_engine/web/api/security.py
This change uses the security.get_repository_context() helper in /queues
endpoint.
Change-Id: I769de9454769ff06fe941bc963be25e921fa4b5a
> refactor(api): uses get_repository_context helper in /queues too

- installer/package-lock.json
Fix https://github.com/Mergifyio/mergify-engine/security/dependabot/15
> fix(security): upgrade minimist

- docs/source/actions/queue.rst
There is no need to repeat the CI there, so don't do it to keep things
simpler.
> docs(queue): simplify conditions in queue_rules

- mergify_engine/tests/functional/test_attributes.py
These tests are a bit flaky on GHES during record. Waiting for
mergeable_state to be computed by GitHub fixes the issue.
Fixes MRGFY-1027
Change-Id: I8470ef3628242836bca67129ec111661bd0526a0
> fix(tests): make is_behind tests reproducible

- mergify_engine/queue/merge_train.py
if a traincar has been created and serialized before we
queue_pull_request on all traincar, we must set it manually.
Fixes MERGIFY-ENGINE-2M5
Fixes MERGIFY-ENGINE-2M6
Change-Id: Iac7fe64b94592f176484fb19f0d74e66adb99148
> fix(queue): add traincar deserialization compat

- mergify_engine/tests/functional/actions/test_queue.py
In the past, we was asserting on 5 or 6 depends on if the draft PR has
been created before or after the first PR in queue has been updated.
On github.com, this has become stable become events always arrive in
same order now. But on old GHES, the events ordering that lead to this
can still happen, so we should allow 5 commits again.
Change-Id: I6a28b57d12a6e2b6eadb685a5e29debd902baf20
> fix(tests): be more flexible about number of commit in draft PR

- mergify_engine/tests/functional/actions/test_queue.py
- mergify_engine/tests/functional/actions/test_rebase.py
- mergify_engine/tests/functional/base.py
- mergify_engine/tests/unit/test_worker.py
Instead of just sleeping and looking at Redis content to know if the
engine works, this change track when StreamProcessor.consume run().
This allow to reduce a lot all sleep timing when the engine ran.
test_worker for example takes 15s instead of 24s on my machine.
> chore(tests): change how we track the engine works

- mergify_engine/tests/unit/test_clients.py
- setup.cfg
httpserver starts a real http server that is very slow.
respx mock the heart of httpx make tests ran a lot faster.
test_clients takes now ~3s instead of 20s
Change-Id: I376c36c55a30f066b41bc394c210eaea367fde1f
> chore(tests): start replacing pytest-httpserver by respx

- mergify_engine/queue/merge_train.py
That's not a huge issue as head_branch is not used when
`create_state != "created"`, but it's better to set it correctly.
Change-Id: Icc2c85467a0be077956888449da10eb5cf79b7db
> fix(queue): deserialization head_branch

- mergify_engine/queue/merge_train.py
This adds to much latency, this code has run in production during some
hours, so the previously craps has been cleaned now.
If a bug occurs when TrainCar PR is created or deleted, we still have
_prepare_empty_draft_pr_branch() to ensure the merge-queue will not be
blocked.
Change-Id: I73e150b5787d259b8bebf62634454a8857322605
> fix(queue): remove pull requests cleanup

- mergify_engine/context.py
- mergify_engine/debug.py
- mergify_engine/engine/__init__.py
- mergify_engine/queue/__init__.py
- mergify_engine/queue/merge_train.py
- mergify_engine/rules/__init__.py
- mergify_engine/rules/live_resolvers.py
- mergify_engine/tests/unit/rules/test_rules.py
- mergify_engine/tests/unit/test_train.py
Loading the yaml and parsing it with voluptuous is slow.
This change cache the configuration in Repository context.
Since Repository context is recreated each 30s, the cached configuration will
stay valid for 30s.
Fixes MRGFY-1071
Change-Id: Ib81251e0f182feb6e31e9e0698cf22e1c0a32014
> feat(config): cache loaded config in Repository context

- mergify_engine/check_api.py
- mergify_engine/tests/unit/test_utils.py
- mergify_engine/utils.py
The current code was checking the number of char instead bytes length,
before truncating the string.
This change ensures everything is done in bytes.
Fixes MERGIFY-ENGINE-2MQ
Fixes MERGIFY-ENGINE-2J8
Fixes MRGFY-1082
> fix(summary): truncate summary correctly

- mergify_engine/tests/unit/test_worker.py
- mergify_engine/worker.py
This directly depends on GitHub "mergeable_state" background
computation. Usually it's matter of seconds, but sometimes it could be
more that 3 minutes.
Change-Id: Ie501c70383e8cb0cd7b6eceddeaec39a77ff86c6
> fix(worker): keep PR in queue more times

- docs/source/configuration.rst
This is now barely useful as its uses an old endpoint.
If we need again we should make it on the API.
> docs(config): remove validation endpoint

- mergify_engine/utils.py
In case of CTRL+C during pytest run, get_coro() may returns an
Generator[Future] instead of an awaitable and they don't have a
__qualname__.
> test: fix Redis connection shutdown

- setup.cfg
This reverts commit d0f087c68c5f906971de1331b2bac4a9da63850e.
This doesn't work as expected, it measures the cpu time, but since we
use asynio we want the wall time of our coroutine, not the cpu time.
> revert: "test: install pytest-profiling (#4547)"

- mergify_engine/tests/functional/conftest.py
We can leverage the pyvcr before_record_request to filter out the
requests with access_tokens as there are not reused during replay.
This avoids the need to deserialize all response payloads.
> test: change the way we hide access_tokens from fixtures

- tox.ini
This saves between 0 and 2 second each time a test teardown.
> test: close idle Redis connections faster

- mergify_engine/tests/functional/api/test_queue_freeze.py
- mergify_engine/web/api/queues.py
- mergify_engine/web/utils.py
We should not play with how fastapi handle errors.
For example, "value_error.missing" type can be raise for a
fastapi.Path() or fastapi.QueryString(), not only fastapi.Body(). Making
our error message misleading.
We also convert some 422 to 400, while openapi said we only have 422
errors. So just always keep the original 422.
Until the fastapi bug with dataclasses is fixed we should use
pydantic.BaseModel for Body() to have a correct error reported.
Change-Id: I0d2f1d7fca0822f53171eca43eafe3be599e8d22
> fix(api): don't return 400 but 422

- .github/workflows/docs-upload-gcp-prod.yaml
- .github/workflows/docs-upload-gcp.yaml
Looks like it brokes content-type 
Reverts Mergifyio/mergify-engine#4572
> revert: "chore(deps): bump google-github-actions/upload-cloud-storage from 0.9.0 to 0.10.0"

- mergify_engine/actions/delete_head_branch.py
- mergify_engine/check_api.py
- mergify_engine/clients/http.py
- mergify_engine/duplicate_pull.py
- mergify_engine/engine/__init__.py
- mergify_engine/queue/merge_train.py
- mergify_engine/tests/unit/test_clients.py
It seems like the list of errors in the payload sent from GitHub does only contain
the error's string. Github added new payload format that needs to be handled. 
Fixes MRGFY-1112
Fixes MERGIFY-ENGINE-2N4
> fix(http): adapt ClientSideError payload format changes

- pyproject.toml
- setup.cfg
This is the new recommended ways because of:
Usage of setup.cfg is not recommended unless for very simple use cases.
.cfg files use a different parser than pytest.ini and tox.ini which
might cause hard to track down problems. When possible, it is
recommended to use the latter files, or pyproject.toml, to hold your
pytest configuration.
Change-Id: I923aa6a6f54bfd05a25fea7dd4b831e6a496ae1d
> test(pytest): move configuration to pyproject.toml

- mergify_engine/context.py
App using old statuses API usually spam GitHub with pending state. So we
may need more page to get a full state.
Change-Id: Ic266378dbd82a999f7f6e465bf1cc11659895d20
> fix(statuses): raise page limit to 10

- mergify_engine/actions/queue.py
The test_queue tests don't passed anymore since this change, the
reported summary is empty.
This reverts commit 7dd9ead2e701aab8ddd8aa7c9bce58a905286f66.
> revert: "fix(queue): report cancelled reason (#4625)"

- mergify_engine/tests/functional/base.py
GHES owner ids are differents and don't goes through shared-0.
This change changes the worker configuration to ensure everything goes to
shared-0 worker.
Fixes MRGFY-1133
> test: configure only one shared worker

- mergify_engine/actions/merge_base.py
- mergify_engine/actions/queue.py
- mergify_engine/engine/queue_runner.py
- mergify_engine/queue/merge_train.py
- mergify_engine/rules/checks_status.py
- mergify_engine/tests/unit/actions/test_queue.py
- mergify_engine/tests/unit/rules/test_get_rule_checks_status.py
This method does not belong in merge_base.py as it's not used in merge
action anymore.
Since it's just conditions manipulations and assertions, I created a new
module in rules/, the tests was already in unit/rules/.
This also changes to returned type to a more precise one.
> refactor(queue): get_rule_checks_status

- mergify_engine/engine/actions_runner.py
Some users have a huge config file and the summary may be too big to log.
This change split it over each action logs.
> chore(engine): split summary logging in each action

- mergify_engine/tests/functional/test_attributes.py
Serialized summary is on top now, we can't use startswith() anymore.
> test(ghes): fix assertion

- .env
- docker-compose.yml
- run-tests.sh
- tox.ini
This allows to run multiple dashboard and engine tests in //.
> test(tox): use random redis port

- mergify_engine/debug.py
- mergify_engine/tests/functional/test_debug.py
It doesn't make sense to test repository access with a random oauth
token.
Repository is accessed just after with the app and will return 404, if
Mergify is not installed, it's enought to debug.
Fixes MRGFY-1138
> chore(debug): remove useless checks

- mergify_engine/actions/assign.py
- mergify_engine/signals.py
The action does not return error to engine, so error was just ignored.
Signal was unconditionnally send even if the action was doing nothing.
Related MRGFY-1142
> fix(assign): signal and error handling

- .github/dependabot.yml
We now have a schedule to merge this when we want so we can create them
early so we have a chance to prepare the batch before the regular queue
opens.
> ci(dependabot): create PR earlier in the day

- mergify_engine/actions/dismiss_reviews.py
Only when reviews are dismiss is interresting.
Change-Id: I6ee30e230ea87970b2c0e5401a1b5206483cacfe
> chore(dismiss_reviews): remove useless log

- mergify_engine/check_api.py
This code is obsolete, logs show we didn't fall into that case anymore.
But this doesn't fix the root cause of MRGFY-1128 as the logs show
Context.pull_engine_check_runs have duplicate check-run ids. More
logs are added to try to understand how this can happen.
Fixes MRGFY-1128
> fix(check-runs): never cancel a check-run

- docs/source/actions/queue.rst
- mergify_engine/actions/queue.py
batch_size and speculative_checks requires branch protection strict mode
to be disabled.
> fix(queue): add message when branch protection is misconfigured

- setup.cfg
This tags sphinx libs with last known working version.
Sphinx 5.0.0 breaks and complains about missing meta that existing in
the files.
> fix(docs): handle sphinx upgrade with dependabot

- mergify_engine/clients/http.py
- mergify_engine/service.py
- mergify_engine/tests/unit/test_logging.py
This must be passed as an environment variable to have the version set.
This removes the dependency on Heroku and leverage something more useful
such as the sha1.
Fixes MRGFY-1206
> refactor(service): use MERGIFYENGINE_VERSION to detect version

- mergify_engine/actions/request_reviews.py
- mergify_engine/tests/unit/actions/test_request_reviews.py
This makes the engine retrying the action until the error is fixed.
Fixes MRGFY-1212
Change-Id: I2c3a7cb433d1d7472f64d53e59711cf04a5bda51
> fix(request-reviewers): return ACTION_REQUIRED on team errors

- mergify_engine/clients/github_app.py
- mergify_engine/tests/__init__.py
Currently, the solution using `__init__.py` works only for `tox -e py310/record`.
This makes it also works for `tox -e test`
Fixes MRGFY-1218
Change-Id: I3e401369ed9f49c347e39f901cbe823e0f793cb8
> fix(tests): change the ways we add additional permissions of testing app

- mergify_engine/actions/merge_base.py
We should not return FAILURE, as it means it's fatal for the rule
engine.
This allows the merge to be retried in case of the pull request is
requeued.
Fixes MRGFY-1220
Change-Id: I9561e1bbb145f26d3f4306948d20bf98a7129e08
> fix(merge/queue): never report merge failure as failure

- mergify_engine/tests/functional/actions/test_queue.py
- mergify_engine/tests/unit/actions/test_merge.py
The exception variable used in the `as` should be used outside of the
`with` scope.
> fix(tests): Fix incorrect `pytest.raises(...) as` usage

- mergify_engine/tests/unit/actions/test_merge.py
They were removed by mistake by ac1c10fc291c530745b28a37d452ac6bc14bbc06
> fix(tests): Re-add trailing whitespace for test_merge_commit_message

- mergify_engine/tests/unit/test_worker.py
Some tests was not closing redis connections, making their teardown
flaky.
This change fixes them.
Fixes MRGFY-1216
Change-Id: I40d407ee7068d8198a099730c9ef498882a27ed1
> fix(tests): close redis connections

- .github/workflows/docs-upload-gcp-temp.yaml
aa61f01287 has changed the name of the job and break this.
This change uses the new name.
Fixes MRGFY-1213
> ci(docs): fix tmp doc upload trigger

- mergify_engine/actions/queue.py
- mergify_engine/actions/unqueue.py
- mergify_engine/engine/actions_runner.py
- mergify_engine/eventlogs.py
- mergify_engine/queue/__init__.py
- mergify_engine/queue/merge_train.py
- mergify_engine/signals.py
- mergify_engine/tests/functional/actions/test_queue.py
- mergify_engine/tests/unit/test_train.py
This adds queue.check_start, queue.check_end, queue.enter and queue.leave.
Fixes MRGFY-1258
Fixes MRGFY-1239
Change-Id: Ie59c15ca292dc8e99be210b4fc2ba7270c83cfe8
> feat(signals): track more queue events

- mergify_engine/delayed_refresh.py
- mergify_engine/tests/unit/test_worker.py
- mergify_engine/worker.py
Currently when a time conditions will change its status, we will refresh
all opened pull refresh to reflect that in the Summary.
This meantime that at certain hours Mergify may looks laggy.
Delayed refresh doesn't really need to be on time, we already
document that delayed-refresh can be 5 minutes late, so.
This introduces a new level of priority: medium. By default GitHub events
stay high as before. delayed-refresh are now medium. And pull request
refresh due to push events stay low.
Fixes MRGFY-1234
> fix(delayed-refresh): decrease priority of delayed-refresh

- mergify_engine/clients/github.py
GitHub returns reset date in the past sometimes making the engine
retrying shorly instead of waiting a bit.
I'm not even sure we have to wait in this case...
For now, just log more details when it happen.
Fixes MRGFY-1264
Change-Id: Ib8288e6ca157073aab85e958e23a9f0bebe08abc
> chore(rate-limit): log when rate limit reset date is in the past

- mergify_engine/redis_utils.py
- mergify_engine/tests/conftest.py
- mergify_engine/web/redis.py
- mergify_engine/worker.py
To ensure the good loading of redis scripts all along the engine workflow, at any time,
and avoid worker failures, we needed to setup a way of loading them dynamically.
These changes have also lead to the removing of all migrations scripts and tests.
Fixes MRGFY-1259
> feat(worker): preload/reload redis scripts dynamically on client connection

- mergify_engine/signals.py
All recorded events may not have all fields we currently have in the
code.
This change makes all of them optional.
Fixes MERGIFY-ENGINE-2R1
> fix(eventlogs): Don't enforce that all fields should be there

- mergify_engine/actions/merge_base.py
- mergify_engine/context.py
If GitHub is laggy, the next /pull/XXX after a PR get merged may not be
marked as merged. Since the merge queue code relies on this to known if
something unexpectedly merged in meantimes, we must wait the attributes
merged change.
Fixes MRGFY-1272
Change-Id: I9acf4a82732fa28a0aa2c9dc1fd4b123167ec23e
> fix(merge/queue): ensure context is updated on merged PR

- .mergify.yml
Now that there more regular contributors, there's no need to keep
approval for ever. We can re-request a review.
This should prevent issues where wrong push could be merged by
mistake.
> chore(mergify): remove approval on new commits

- README.md
> fix: typo in documentation links
