Mergifyio/mergify

mergify_engine/actions/rebase.py, mergify_engine/branch_updater.py, mergify_engine/duplicate_pull.py, mergify_engine/gitter.py
Change-Id: Icb8b1445caea92aef6297f915337ff761b6d771b
=> refactor: move some Git error logic to Gitter()

mergify_engine/branch_updater.py, mergify_engine/user_tokens.py
Change-Id: I106d71188c783385690d6f8238f85f383cd64ee2
=> refactor: move UserTokensUser selection to UserTokens class

mergify_engine/context.py
Change-Id: I2f438230441a10b1ed25ede6568a71593855de89
=> chore: add note about github automerge

mergify_engine/gitter.py
=> fix(gitter): add a new connection error case

mergify_engine/actions/copy.py, mergify_engine/duplicate_pull.py
We don't support copying pull request with merge commit, so report it
correctly.
Fixes MERGIFY-ENGINE-27X
Fixes MERGIFY-ENGINE-27W
Fixes MERGIFY-ENGINE-287
Fixes MERGIFY-ENGINE-288
=> fix(backport/copy): correctly report issue with merge commit

mergify_engine/queue/merge_train.py
Change-Id: I7ab4c5895fb3f4b92a616b60722a6d98dd3d81bf
=> chore(queue): avoid useless pull body edit

mergify_engine/duplicate_pull.py
=> fix(duplicate_pull): use correct exception output

mergify_engine/worker.py
Change-Id: I70e32d82e34639c0f93b2463da3401980bb66db5
=> fix(woker-status): display owner login instead of id

mergify_engine/worker.py
Change-Id: I1bf7e623554a39a634d8cdd1ad62bd97dc2100fe
=> feat(worker): add metric for high prio backlog

mergify_engine/worker.py
Change-Id: I011d5e3196dcb039b21c8dd27b82bed4f48008e9
=> fix(worker): metric for high prio backlog

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py, mergify_engine/worker_lua.py
Change-Id: I1455de8c2e7ff3c7703c749ea5cd71dbe8e30cfe
=> chore(worker): change stream wording to org bucket wording

mergify_engine/worker.py
Change-Id: Iae17e51d984fd2779747b3e34a1312a5d5c7dbb7
=> refactor(worker): consume_pulls() -> consume_pull()

mergify_engine/worker.py
Change-Id: I32e24eee72b5314246365c7659b02cc0787674d2
=> fix(worker): add some missing engine.buckets.read_size push

mergify_engine/config.py, mergify_engine/worker.py
=> refactor(worker): remove BUCKET_PROCESSING_MAX_PULLS

mergify_engine/queue/merge_train.py
Change-Id: Iaa0818768f5ab8e4260825438d27130c08b4aecf
=> chore(queue): remove unused code

mergify_engine/worker.py
Change-Id: I2a0d3a0769863dcfeeeca291a5b26700fc4d4266
Change-Id: Id782e6d8e545514505c8f302557d002383fbff33
=> feat(worker): count the number of times we got preempted processing buckets

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker_lua.py
Fixes MERGIFY-ENGINE-28J
Change-Id: Id42e290e8e431367cf73d39a814a366fdd6bdbd0
=> fix(worker): correctly call DROP_BUCKET lua script

Dockerfile
Change-Id: Iaf81bdd84e0c66a9f3e9bb7ad249c401dd2b8030
=> fix(docker): install source directory

Dockerfile, entrypoint.sh
Change-Id: Iece1c5817e4b9170f97321b123c1ee10b1e08f94
=> fix(docker): fix default entrypoint target

Dockerfile, entrypoint.sh, mergify_engine/worker.py
Change-Id: I4ceadb3b46769ab8f8d5f59175666c2cc5ada8bd
Depends-On: #2926
=> fix(worker): add missing logging param

Dockerfile, entrypoint.sh, mergify_engine/logs.py, mergify_engine/worker.py
Change-Id: I11aa7f161e47ffce652eefe2a4bbdcfa43e79fa6
Depends-On: #2927
=> fix(logs): hide subscription token

run-tests.sh
Change-Id: Ie7f6edc3c2838bd60f06bf8a32ff86a04fcf8d72
=> fix(tests): use -z instead of -w1 to detect open port

run-tests.sh
Change-Id: Ia6e74761df2d17a56bad7cf1d35f8a85678d6595
=> fix(tests): don't use nc

mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/test_train.py
Change-Id: I77052c71639b754c11df492e59919e1b4d15252e
=> fix(queue): correctly cleanup queue when speculative_checks decrease

mergify_engine/queue/merge_train.py
Change-Id: I9ca0063b0794320f502e3e1e92db51ec2bdf38b0
=> fix(queue): preserve order when train is shrunk

mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
Change-Id: I339827543ad790f9cfb1090e1d0d0a9c3d269aa7
=> fix(rules): duplicate queue rules detection

mergify_engine/actions/queue.py, mergify_engine/rules/__init__.py
Change-Id: Ida624bfab115548cf2c0b5dc8fa31aedda62cb78
=> chore(rules): add type to QueueRules

mergify_engine/user_tokens.py
Change-Id: I79b8e47dd1c41d376e45922f1014becbce9ced8b
=> fix(branch_update): add missing dataclasses

docs/source/actions/queue.rst, mergify_engine/actions/queue.py
This sync the type with the merge action.
Change-Id: I3ca8ee880451b0052cb97a090382d7b99ed36e50
=> fix(queue): improve the type of merge_bot_account

mergify_engine/queue/merge_train.py, mergify_engine/rules/__init__.py, mergify_engine/tests/unit/test_train.py
Related MRGFY-522
Change-Id: I59cae5899bfa9922774f997b54eddf9d961a5b81
=> feat(queue): sync configuration of queued PR

mergify_engine/queue/merge_train.py
Change-Id: Icd632143826053027aa3fbe3f955a94582789bd5
=> fix(queue): don't print None in check-runs list

mergify_engine/actions/copy.py, mergify_engine/duplicate_pull.py
Change-Id: Iab9484261e59119f753d135efd209ebc66af60cf
=> chore(duplicate): fixup some error messages

mergify_engine/duplicate_pull.py
Fixes MERGIFY-ENGINE-299
Change-Id: I69f8e9495f0c57fb74b9b5a24bcf6cd36b37e117
=> fix(duplicate): catch error when destination branch vanish

mergify_engine/debug.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/test_user_tokens.py, mergify_engine/user_tokens.py
On on-premise setup, we should not query the dashboard.
Change-Id: Ic66e046455a59f711dcb8e58438b58fc149313e0
=> fix(onpremise): user_tokens setup

Procfile, mergify_engine/clients/github.py, mergify_engine/count_seats.py, mergify_engine/logs.py, mergify_engine/tests/unit/test_seats_count.py
Fixes MRGFY-527
Change-Id: I95a45a514b14ec50df7484c806444acbc0e17ea7
=> feat(onpremise): report seats number

mergify_engine/context.py, mergify_engine/github_types.py
Change-Id: Ifaaadfc580d4579afdbd0559ce75365f9f9c36ad
=> chore(context): add missing definition type

mergify_engine/worker.py
Change-Id: I51a6f2ac361d546514a95fae81f5dd964139ce28
=> chore(worker): add missing definition type

.github/workflows/releaser.yml
Change-Id: Iab7b8da1f21dc25db8d63f5d1491a45bf7cad08a
=> ci: change output format of release note

mergify_engine/rules/parser.py
Change-Id: I8da7ea1fecb16500fa2a425b26adeba41e145347
=> chore(parser): add missing typing definition

mergify_engine/engine/commands_runner.py, mergify_engine/rules/__init__.py, mergify_engine/rules/conditions.py, mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/tests/unit/actions/test_merge.py, mergify_engine/tests/unit/rules/test_rules.py
Change-Id: I64a48b2cd810d5d1e14ee03eec308d3def9279a5
=> chore(rules): split __init__.py

mergify_engine/engine/commands_runner.py, mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
Change-Id: Idce0ce73e8132d2837a7ac2a652379964fff0ef6
=> chore(rules): rename Rule -> PullRequestRule

mergify_engine/actions/dismiss_reviews.py, mergify_engine/actions/merge.py, mergify_engine/actions/queue.py, mergify_engine/context.py, mergify_engine/engine/queue_runner.py
Change-Id: I3f35a881f47b1e130f31cddf8a3b4e4a8f9855f7
=> fix(update): fix detection of synchronized event done by Mergify

mergify_engine/engine/commands_runner.py, mergify_engine/tests/unit/test_command.py
Fixes MERGIFY-ENGINE-29T
Change-Id: I3f35a881f47b1e130f31cddf8a3b4e4a8f9855f7
=> fix(command): report invalid command arguments

mergify_engine/web/root.py
Fixes MERGIFY-ENGINE-29V
Change-Id: I56cb36b3fd845d4b46f029aa329578cdc74dbdaa
=> fix(queue): load json serializer in web app

.mergify.yml
Change-Id: Ibddea27e119f0f71a8fa26f52b08b1be9ca258ec
=> ci: batch dependabot pull request merge

docs/source/conditions.rst
Change-Id: Id98ef7a82deede38db3b5821493a0ea79f571f93
=> fix(docs): add missing dash on second and/or example

.github/workflows/docs-upload-gcp-prod.yaml
This push the documentation to GCP
Change-Id: I7653008a76aeec4d71d2bee66cc5e064f7ae8191
=> ci: push docs to gcp

.github/workflows/releaser.yml
The changelog uploaded is GitHub release is empty, so add some debugging
to understand why.
Change-Id: I826992a2981f72c92fe60c57630625d28ae6d7ac
=> ci(releaser): add debug information

mergify_engine/count_seats.py, mergify_engine/tests/functional/test_count_seats.py, mergify_engine/tests/unit/test_count_seats.py
returns None instead of an empty list when active_users or write_users
are not computed.
Change-Id: I05a8dce6742110e52554cf08edee52d247d9c766
=> chore(count-seats): improve json output

mergify_engine/actions/queue.py
Change-Id: Ibca5e2de7fb4095a9ce3574f68e5254efa03e890
=> feat(queue): signal new configuration options

.github/workflows/releaser.yml
Change-Id: I4e9bf6c75532b88e38507e8df9afa51f4efad00b
=> ci(releaser): tag version before running reno

mergify_engine/debug.py
Fixes MERGIFY-ENGINE-2A1
Change-Id: Ieccb08f4b5b07ac37a43a1a0f19030e79c1e3059
=> fix(debug): catch KeyboardError

mergify_engine/gitter.py
Fixes MERGIFY-ENGINE-2A3
Change-Id: I21b4a6b014f12c82e634fe707df79651a946dbd2
=> fix(git): handle a new git 401 error

mergify_engine/count_seats.py, mergify_engine/github_types.py, mergify_engine/tests/unit/events/pull_request.json, mergify_engine/tests/unit/test_count_seats.py
Change-Id: I3b0c91e436736bd6edf569557dee02b6b767fa13
Change-Id: I5ea1ae9f9f82ab96010db02f1ecfb7e935887e5a
=> Pull request for track-other-than-sender-id

.github/workflows/releaser.yml
Change-Id: Ie439271333b702bd937e7bb693cb0348d64ff391
=> ci(releaser): use sudo for apt

.github/workflows/releaser.yml
Change-Id: I16eb539ee9da0ceec5a4cf9ae335df78d09ae3de
=> ci(releaser): install pandoc with tarball instead of apt

.github/workflows/releaser.yml
Change-Id: I0d5805d6c17f9d162a16be98fe4025095f27637f
=> ci(releaser): remove debuging information

docs/source/actions/queue.rst
Otherwise the title appear in the sidebar.
Change-Id: I4836ee0d384533c06b6d3bc566cc6e74ecba72fb
=> fix(docs): fix a title level

mergify_engine/count_seats.py, mergify_engine/tests/unit/test_count_seats.py, mergify_engine/web/root.py
Change-Id: I16eb539ee9da0ceec5a4cf9ae335df78d09ae3de
=> fix(seats): filter returned seats via API correctly by owner_id

mergify_engine/actions/__init__.py, mergify_engine/actions/merge_base.py
Change-Id: Ia2bf12ae8c949bcf2915ad945a246eb69faa9655
=> chore(action): move usage of abc to merge/queue action

mergify_engine/actions/rebase.py, mergify_engine/actions/squash.py, mergify_engine/actions/update.py
Change-Id: Idb6e4b7b9a943ebea452c61c32abbb4b8b1a221e
=> feat(rebase/update/squash): it doesn't make sense to do them twice

mergify_engine/actions/utils.py
Change-Id: I815c677691bab0a8b9bd082961b4ce9412c73e4d
=> chore(bot-account): subscription feature is now required everywhere

mergify_engine/actions/review.py
Change-Id: I718e2f98230e3f979663753dc9338984e5d41b36
=> chore(review): remove obsolete comment

mergify_engine/actions/__init__.py
Change-Id: Ib77d50f6f35da3fb35f3fea6523c0fc68b8a0f23
=> chore(action): mark run has abstract method

mergify_engine/actions/__init__.py, mergify_engine/actions/assign.py, mergify_engine/actions/copy.py, mergify_engine/actions/label.py, mergify_engine/actions/request_reviews.py
Change-Id: Ieb72e158c193ab09ee7f217dc1a7ce42d36d55ce
=> chore(action): validator must use callable to build mutable object

mergify_engine/rules/types.py
Change-Id: I9891231c4eaa912516a4821c81fa3cc5fedba225
=> chore(rules): remove obsolete todo

.mergify.yml
This reverts commit 7b1f9335c15e4ab7f1eea73134718c75c786056b.
=> revert: "ci(mergify): use timezone for schedule"

.mergify.yml
Change-Id: Icf49f6df84c06d611d41713117dcc1052fad9fef
=> ci(mergify): use squash first-commit by default

mergify_engine/engine/actions_runner.py
Change-Id: Ib402f16cf54866141017f8c874d387d539ce4b63
=> chore(action_runner): rewrote comment

mergify_engine/utils.py
This will help to debug case where we have un-ending loop of refresh
event.
Change-Id: I57ef84f01da17fed2accca070a3dda25cee90cff
=> feat(refresh): log when/where refresh are send

mergify_engine/actions/queue.py, mergify_engine/actions/refresh.py, mergify_engine/github_types.py, mergify_engine/queue/__init__.py, mergify_engine/queue/merge_train.py, mergify_engine/queue/naive.py, mergify_engine/tests/unit/test_utils.py, mergify_engine/utils.py, mergify_engine/web/root.py
Change-Id: I129dda6572fdc2fb8231917bcac6bcefd133fc91
=> feat(refresh): log the source of the refresh

.mergify.yml
This reverts commit b503903205d94d6505477dd82906985f80b65e22.
=> ci(mergify): use timezone for schedule

mergify_engine/subscription.py, mergify_engine/tests/unit/test_subscription.py
It's not send anymore by the dashboard.
=> chore(subs): remove large_repository feature

mergify_engine/actions/delete_head_branch.py
Report a different message if the head branch has been deleted by
something else.
Change-Id: I094affe9faa0185a19b5d7cf7288bb7219dcc2d8
=> feat(delete_head_branch): improve reporting

mergify_engine/github_events.py
This allows to track where the refresh event come from.
Change-Id: I2be1940a58d14d4d01480c2dc6f9d5737f8da47e
=> feat(refresh): forward the source to the engine

mergify_engine/tests/bridge.py
Change-Id: Ic5951ca2161f34301130d0210edb5bbbd3cf6d87
=> fix(tests): use new event forwarder url in bridge tool

mergify_engine/actions/label.py, mergify_engine/context.py
Change-Id: I1c30619ac4bfba980007d73f3710f4ae62070a43
=> fix(label): cache only label name

mergify_engine/delayed_refresh.py
Change-Id: I24a8093edebcfcbb7c9be4474dcfb62216599606
=> chore(delayed-refresh): add some debugging/logging

mergify_engine/web/asgi.py, mergify_engine/worker.py
Change-Id: I154744aa37920655648c579744ad98cbebb04384
=> feat(datadog): add service tag to statsd

mergify_engine/actions/label.py, mergify_engine/context.py
If multiple rules delete/add labels, the action doesn't work as expected
as the pull cache is not updated.
Change-Id: I50a5d39661cbbd3beaf6b294fcd3aa81c5e12bb9
=> fix(label): don't try to remove a label already deleted

mergify_engine/__init__.py
=> fix(ddtrace): set version

mergify_engine/logs.py
Change-Id: I42639e6771ce4a1499238a1be799f80b4828c544
=> fix(tests): hide more environment variables from logs

mergify_engine/tests/unit/rules/test_rules.py
Change-Id: I304565747694d84897e8944ea91de3c4d7042526
=> chore(rules): add merge_base.get_rule_checks_status() test

mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_date.py
This change adds two tests of schedule with another context.
Change-Id: I4f8ee557b80a026853643d61a970c7e23f6247af
=> chore(schedule): add more tests

mergify_engine/clients/github.py, mergify_engine/clients/http.py, mergify_engine/debug.py, mergify_engine/web/auth.py
This reverts commit 219edcb7170425535e9e89584ab165bafa0ea5c7.
=> revert: "fix(http): use same timeout everywhere"

docs/source/actions/queue.rst
Change-Id: I79bd1fe345f6e44d95ec5e4b8d425f5f8402e81f
=> docs(queue): add § about batch_size and timing

mergify_engine/date.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_date.py
Change-Id: I5be40f2135d17cb675af9613afdafce093243dfb
=> fix(date): parsing of day of week long format

mergify_engine/engine/__init__.py
Change-Id: Id605668d20c66c50325fc8928a45ad8ac0bbe8a9
=> chore(summary): rework logging when we sync summary

mergify_engine/engine/__init__.py
Change-Id: I99c6109d611fd87d7f7d993dcf9f6daaa87da2f9
=> feat(subscription): add reason to logging

mergify_engine/actions/queue.py, mergify_engine/context.py, mergify_engine/engine/queue_runner.py, mergify_engine/queue/merge_train.py, mergify_engine/rules/__init__.py
This logs some details about `schedule` condition.
Change-Id: I2fae6bc5a3017b39cfdb93e7b8c878971bdbaf05
=> chore(delayed-refresh): add logging to delayed refresh

releasenotes/notes/workflow-permissions-63481b0a386507fa.yaml
Change-Id: Idd66bd038665e3e629808a35b221ca87c2ff94ce
=> chore(releasenotes): fix some typos

releasenotes/notes/administration-perm-34f1efb5ec952c8a.yaml
Change-Id: I4e11e4de558f1bb54e3d9aa91977220ab42aa7b1
=> chore(releasenotes): add missing admin permission upgrade note

.github/workflows/syncer.yaml
Change-Id: I90cc241e783f64c9757ae789714da2c8d1f0ebaf
=> fix(ci): github-script@v5 requires to use the API workspace

mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/test_train.py
No need to browse all repositories to force remove a pull request.
Change-Id: I2364c10815908dc9f171174f85cab0fd5ec13bcb
Fixes MRGFY-454
Change-Id: I354d0f9cca591655ace84b2931468f629a9ce458
=> Pull request for base-branch-change

mergify_engine/delayed_refresh.py
Change-Id: Iee423fe063ce43d9f08fb1764f2570a509825698
=> chore(delayed-refresh): more logs

docs/source/conditions.rst
Related MRGFY-605
Change-Id: Ibe4de612c18e4f652e9b43bc2070bac4d0618959
=> docs(conflict): write down it doesn't work on draft

mergify_engine/actions/request_reviews.py
Change-Id: I2ccf34bc2eae21d562c27a6edaa047f02c7b8b2f
=> refactor(request_reviews): inject weight with voluptuous

.github/workflows/docker-upload-dockerhub.yaml, Dockerfile, mergify_engine/config.py, mergify_engine/count_seats.py, mergify_engine/tests/unit/test_count_seats.py
This change adds engine version to the docker image and report it to the
dashboard.
Fixes #MRGFY-557
Change-Id: I4af8fde046cd9b8003d10a6dd200cd3a196e4f34
=> feat: add VERSION to the built docker image

mergify_engine/config.py, mergify_engine/tests/functional/base.py
Change-Id: I6a1d30100b05ecf76ef5d7220c0ac93c98937937
=> test(ghe): allow to configure users ID

tox.ini
Change-Id: I6db1e1112c9834d5bc879b83015c63ee06939435
=> fix(docs): remove linkcheck plugin

.github/workflows/docs-upload-gcp.yaml
Change-Id: Idbb30e211301c765ca971168f8376115bdf24c54
=> ci(docs): fix documentation workflow name

.github/workflows/docs-upload-gcp.yaml
Change-Id: I1f202e66589cbea96d26fea1253cc5026a10a408
=> ci(docs): fix script for actions/github-script@v5

setup.cfg
https://pypi.org/project/pytest-github-actions-annotate-failures/
Change-Id: I13c4362bf8836e1b05cf42a9cae0e61200a7626f
=> ci(tests): add pytest github actions annotation plugin

mergify_engine/context.py
=> chore(logs): track when commit_message template from body is used

docs/source/conditions.rst, docs/source/configuration.rst, mergify_engine/context.py, mergify_engine/rules/parser.py, mergify_engine/tests/functional/test_attributes.py, mergify_engine/tests/functional/test_debug.py, mergify_engine/tests/unit/test_context.py, releasenotes/notes/jinja-filters-338b314e9cdf0179.yaml, requirements.txt, setup.cfg
* markdownify
* get_section("### Commit message")
Fixes MRGFY-635
=> feat(template): add new jinja filters

.github/workflows/ci-heroku.yaml, mergify_engine/import_check.py, setup.cfg, tox.ini
This change makes import checker closer to the production environment.
=> fix(tests): improve import checker

mergify_engine/dashboard/subscription.py
This logging appears only during the feature flags removal process.
This is important for the SAAS to log it as error. But for onpremise
this is just informational, as Ops cannot fix it, the log will stay
until we can remove it from the dashboard. So just log it as info.
=> fix(subscription): log on premise missing feature as info

mergify_engine/dashboard/application.py, mergify_engine/tests/unit/test_applications.py, mergify_engine/web/dashboard.py
=> feat(application): add dashboard api endpoint for cache invalidation

mergify_engine/config.py, mergify_engine/dashboard/application.py, mergify_engine/tests/functional/api/test_application.py, mergify_engine/tests/functional/conftest.py, mergify_engine/tests/unit/test_applications.py, mergify_engine/web/api/applications.py, mergify_engine/web/api/root.py, mergify_engine/web/api/security.py
=> feat(application): add support for account scope

.github/workflows/semantic-pull-request.yaml
=> ci(semantic-pr): don't run it on merge queue

mergify_engine/engine/actions_runner.py
chore: Modification of a variable name from Camel Case to Snake Case.
Fixes MRGFY-642
=> chore: Deprecation commit_message option

mergify_engine/engine/queue_runner.py
=> chore(doc): document base/sha usage

mergify_engine/github_events.py, mergify_engine/utils.py
This will allows to refresh a repository without disrupting ongoing
works.
=> feat(refresh): make repo/branch refresh low prio

mergify_engine/worker.py
=> feat(monitoring): trace and tag push events

mergify_engine/worker.py
Each worker main task need to handle exception and stopping code the
same way.
This extract this logic into a dedicated method.
=> refactor(worker): make the loop forever generic

mergify_engine/admin.py, mergify_engine/tests/functional/test_admin_cli.py, mergify_engine/tests/unit/test_admin.py, setup.cfg, zfixtures/cassettes/test_admin_cli/test_suspended/config.json, zfixtures/cassettes/test_admin_cli/test_suspended/http.json
=> feat(admin): add tool to suspend installation

mergify_engine/dashboard/subscription.py, mergify_engine/logs.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
This changes move organization to a dedicated worker task if they have
the feature "dedicated-workers".
Both path are tested during fonctionnal tests as all tests that require
subscription will automatically spawn a dedicated worker.
Fixes MRGFY-581
=> feat(worker): add dedicated worker

mergify_engine/tests/unit/rules/test_rules.py
Change-Id: I70395cdc19c60e1f7ace9136d261ee0e089cfc4d
=> chore(rules): add more get_rule_checks_status() tests

mergify_engine/dashboard/subscription.py, mergify_engine/worker.py
Change-Id: Ief6665d27f161f701084ade646684d6dc4c87b40
=> feat(monitoring): make engine.buckets.backlog per worker

mergify_engine/worker.py
This will allows to graph how many events are pending for people with
dedicated worker.
Fixes MRGFY-717
Change-Id: I48a7bce18f2fca00646eb392d1e245f056d21880
=> feat(monitoring): add engine.buckets.events.count

mergify_engine/web/api/queues.py
Fixes MERGIFY-ENGINE-2EQ
Change-Id: Iaf801368c8fd77041e8884f46285746411199e48
=> chore(api): remove useless logging

docs/source/actions/merge.rst, docs/source/configuration.rst, mergify_engine/context.py, mergify_engine/tests/unit/test_context.py
This allows to use get_section() and fallback to default is the section
doesn't exists.
Change-Id: I0a993820cd74135337e8e282922b4edf734015f6
=> fix(commit_message): allow fallback to default

mergify_engine/context.py, mergify_engine/tests/unit/test_context.py
Interpret the string retrieved with get_section() has template.
Change-Id: I0db496d01fc2a36bd9ab9ddbb73f3a04fe0f6553
=> feat(template): allow templating in get_section()

docs/source/conditions.rst, mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
Fixes MRGFY-713
Change-Id: Id63c98257a02ae6bf63d7585925012567a8d1554
=> feat(rules): increase and/or conditions depth

mergify_engine/dashboard/application.py
Fixes MRGFY-733
Change-Id: If3ae6475ae30d4ff46b1d5e7585044cf4fe547b4
=> fix(application): use new token validation endpoint

.mergify.yml
Change-Id: I6a4da9b9e7a9f43eea078953a97458f24bd8167a
=> ci(mergify): remove deprecated commit_message

.mergify.yml
Change-Id: I3fc785133e682cb3e6f267907ab00a8604f86c78
=> ci(mergify): automatically fix dependabot conflict

mergify_engine/rules/types.py, mergify_engine/tests/unit/rules/test_rules.py
Change-Id: Id1ac9e13bbcda60215fd0a557279261b726729bc
=> fix(template): add missing filters from Jinja2 voluptuous type

mergify_engine/clients/github.py, mergify_engine/duplicate_pull.py
Ensure duplicate_pull can get the access token
Fixes MRGFY-734
Fixes MERGIFY-ENGINE-2B7
Change-Id: I30293a7683a359d7ed0752fb05a893d9e166eebc
=> fix(duplicate): ensure get_access_token() always return a token

mergify_engine/clients/github.py, mergify_engine/context.py, mergify_engine/debug.py, mergify_engine/engine/__init__.py, mergify_engine/tests/unit/actions/test_request_reviews.py, mergify_engine/tests/unit/test_clients.py, mergify_engine/tests/unit/test_command.py
Change-Id: I30b37f24b9b63e339508c731c87ae1b7c98e554e
=> chore(clients): remove installation attribute

mergify_engine/clients/github.py, mergify_engine/clients/github_app.py, mergify_engine/clients/http.py, mergify_engine/context.py, mergify_engine/delayed_refresh.py, mergify_engine/github_events.py, mergify_engine/queue/__init__.py, mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/actions/test_merge.py, mergify_engine/tests/unit/actions/test_request_reviews.py, mergify_engine/tests/unit/test_behind.py, mergify_engine/utils.py, mergify_engine/web/github.py, mergify_engine/worker.py
Partial-Fixes MRGFY-697
Change-Id: I7d16bec7d285d07a867f5287a070f4429ce99e50
=> feat(logs): use ids instead of login/name in logging

mergify_engine/delayed_refresh.py, mergify_engine/queue/__init__.py, mergify_engine/worker.py
Fixes MRGFY-746
Change-Id: If174845d9b9e3186e21ed471d9df37a8257215fa
=> fix(refresh): use pipeline on multiple refresh

mergify_engine/queue/merge_train.py, mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/web/api/queues.py
Partial-Fix: MRGFY-640
Change-Id: I62594694da0355d3402a6876a4c42534db650e31
=> fix: track when speculative check start

mergify_engine/context.py
Change-Id: I024c87cda246360a2b01e3b8fbe77f7a5389b1d4
=> fix: ignore configuration file too big

mergify_engine/migrations/__init__.py, mergify_engine/migrations/cache/0001_merge_trains_to_hash.redis, mergify_engine/redis_utils.py, mergify_engine/tests/unit/test_migrations.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py, mergify_engine/worker_lua.py
This move out from the worker the migration system.
It changes how we stamps the fact we have done the migration script.
Change-Id: I8daeec7e29207ecba657929bbeedbe6b72473c18
=> feat(redis): add a generic migrations system

.github/workflows/semantic-pull-request.yaml
Change-Id: I3008dc78cd385420568c49830114405b6a8043d6
=> ci(semantic): skip it for merge queue

.github/workflows/semantic-pull-request.yaml
This seems to not work...
Change-Id: I8a51825babd6283708c586a2e58de39937a1ebc9
=> ci(semantic): remove merge-queue filter (again)

.github/workflows/semantic-pull-request.yaml
Change-Id: I4af6fe540f10d87a091a8d0f03716350c9483a84
=> ci(semantic): fixup condition quotes

mergify_engine/worker.py
Change-Id: I6e213254c25483a34abc22db28006ec48f6eb690
=> feat(worker): trace background tasks

mergify_engine/worker.py
Change-Id: I0e798392fe088cf317c3cc9c1c85508521974a85
=> fix(worker): remove space is tracer name

mergify_engine/actions/merge_base.py, mergify_engine/rules/conditions.py, mergify_engine/rules/filter.py, mergify_engine/tests/unit/rules/test_get_rule_checks_status.py
This reverts commit 5a6cf73b957a62b2b063cee2d862e2d33dba2855.
Change-Id: Ie2f2fd106fee6795827f5ff45280684330656092
=> revert: "fix(queue/rules): use a Filter to found pending/final checks (#3678)"

mergify_engine/context.py
GitHub returns a list of errors, not just one error.
Change-Id: I1455683a9775a0303cb1907d53b59b398ed7d15d
=> fix: too_large error handling

mergify_engine/worker_lua.py
Change-Id: I79d092cc4afc803669d1f48e488ba7c83ee9af7c
=> feat(worker): add a tracer span per lua script

mergify_engine/actions/utils.py, mergify_engine/context.py, mergify_engine/tests/unit/test_context.py, mergify_engine/tests/unit/test_utils.py, mergify_engine/utils.py
This reverts commit e78c0e6c5ec2acc4749d32fe2f031c9308caabe4.
=> revert: "feat(context): cache user/teams permissions (#3703)"

mergify_engine/clients/github.py, mergify_engine/clients/github_app.py, mergify_engine/clients/http.py, mergify_engine/context.py, mergify_engine/delayed_refresh.py, mergify_engine/github_events.py, mergify_engine/queue/__init__.py, mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/actions/test_merge.py, mergify_engine/tests/unit/actions/test_request_reviews.py, mergify_engine/tests/unit/test_behind.py, mergify_engine/utils.py, mergify_engine/web/github.py, mergify_engine/worker.py
This reverts commit c1ebabe613c773f304d2797f305fe47686ca10a6.
=> revert: "feat(logs): use ids instead of login/name in logging (#3694)"

mergify_engine/web/api/security.py
Fixes MERGIFY-ENGINE-2G9
Change-Id: I30b90761cf18f7e2aa121480e6c3d7e25c5bfd9d
=> fix(api): handle mergify uninstalled

mergify_engine/tests/unit/rules/test_parser.py
Change-Id: I59bcfa041041d38bb5051b038501437c1ccbaaaa
=> feat(parser): add more tests

.gitignore
Remove doublon and old entries.
=> chore: clean out .gitignore

mergify_engine/dashboard/application.py, mergify_engine/dashboard/subscription.py, mergify_engine/dashboard/user_tokens.py, mergify_engine/worker.py
Change-Id: I823b4e0e649505b8c8cd199de6f98f88500ac384
=> chore(black): upgrade to 21.12b0 codestyle

mergify_engine/actions/merge.py
Fixes MERGIFY-ENGINE-2GA 
Change-Id: Ibcfab6e9e3c1075925f30afa07cadb94aa55208a
=> fix(strict-mode): use enum, not boolean

.mergify.yml
Change-Id: Ic1b877162ace06df84d912b58d880b7dbbb4c342
=> ci(mergify): use mergify-ci-bot to comment dependabot pr

mergify_engine/context.py, mergify_engine/tests/unit/actions/test_merge.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_train.py
Change-Id: I6a99c07262dfdf33c4f52cf4144bafab6b161b51
=> chore(context): make RepositoryCache more solid

mergify_engine/context.py, mergify_engine/github_types.py
Fixes MRGFY-761
Change-Id: Ibeac162184bcb5d27ee0e6eaaf91671069145f41
=> feat(context): store less data in files cache

mergify_engine/actions/squash.py, mergify_engine/context.py, mergify_engine/duplicate_pull.py, mergify_engine/github_types.py, mergify_engine/tests/functional/actions/test_squash.py, mergify_engine/tests/functional/commands/test_squash.py, mergify_engine/tests/unit/test_behind.py, mergify_engine/tests/unit/test_duplicate.py
Fixes MRGFY-762
Change-Id: Id58bd0ace82b8c69ebe1c8dd6c3dcee57442dea6
=> feat(context): store less data in commits cache

mergify_engine/date.py, mergify_engine/rules/conditions.py, mergify_engine/rules/parser.py, mergify_engine/tests/unit/rules/test_filter.py, mergify_engine/tests/unit/rules/test_parser.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_date.py, setup.cfg
This change uses a simple parser instead of pyparsing.
It's ~10x faster.
The reported errors are far better than before.
Change-Id: I65c39ec533dbcf11e50e3764053bd5ad8b09511a
=> feat(conditions): remove pyparsing

mergify_engine/rules/__init__.py
The number of reported faulty rules is wrong. This fixes it.
Change-Id: I4d17bd4665cb0e403df0b16d38a0d31cf0765551
=> fix(rules): counting of faulty rules

mergify_engine/cache.py, mergify_engine/context.py, mergify_engine/tests/unit/dashboard/test_cache.py, mergify_engine/tests/unit/test_cache.py, mergify_engine/tests/unit/test_context.py
This change uses the same technique as other cached thing.
Fixes MRGFY-750
Change-Id: Idc27c44614edf6cfcda8109a54f6c73bf10d9ed8
=> feat(context): cache user/teams permissions v2

mergify_engine/cache.py, mergify_engine/context.py, mergify_engine/tests/functional/test_engine.py, mergify_engine/tests/unit/actions/test_merge.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_cache.py, mergify_engine/tests/unit/test_context.py, mergify_engine/tests/unit/test_train.py
Change-Id: Iadaaafa22d03d9a161604275c94a131f096f455c
=> chore(caches): use cache module for ReposityCaches/ContextCaches

mergify_engine/queue/merge_train.py
The base branch may take a while to be created on certain repository.
This change retries the merge as we just created the branch and we known
it exists.
Fixes MRGFY-768
Change-Id: Ie6b8ff009be0677f0daa845ac26185a5d448308b
=> fix(queue): retry merge queue temporary branch creation

mergify_engine/actions/merge_base.py, mergify_engine/tests/unit/rules/test_get_rule_checks_status.py
This adds all check attributes
Change-Id: I945ed82bfb5b6ad3fe34002d0b0d1da6a4148691
=> chore(queue/rules): add logs to get_rule_checks_status()

mergify_engine/context.py
Fixes MERGIFY-ENGINE-2GD
Change-Id: I31394b540d6d1e8b29f749662f1204e6aca274b3
=> fix(logging): filename is reserved keyword

mergify_engine/actions/merge_base.py, mergify_engine/tests/unit/rules/test_get_rule_checks_status.py
Change-Id: I83990854727d7b88196b5bb3cdf473dcf8c34ada
=> fix(queue/rules): typo in logging

mergify_engine/tests/functional/test_engine.py
Change-Id: I84b7962a5b77c0d27d82777c83b7904bd6915425
=> fix(tests): commit_message deprecation message for ghes

docs/source/actions/request_reviews.rst, mergify_engine/actions/request_reviews.py, releasenotes/notes/request-review-bot-account-d4b6bb033e9b45c9.yaml
Fixes MRGFY-767
Change-Id: I3c30b2a4cd6b0c853c83db28866f73f06ae7176a
=> feat(request-review): allow bot_account

mergify_engine/actions/delete_head_branch.py
Change-Id: I4b3206ae12cd57d8422ff5df02b0c4e4d85f9b3a
=> fix(delete_head_branch): deleting none existing branch can returns a 422

mergify_engine/context.py, mergify_engine/date.py, mergify_engine/tests/unit/test_date.py
Change-Id: Icfc741eae0c0cdec0f7f6acf1480456fee3c3c21
=> fix(conditions): RelativeDatetime must be timezone aware

mergify_engine/actions/merge.py, mergify_engine/actions/merge_base.py, mergify_engine/actions/queue.py, mergify_engine/delayed_refresh.py, mergify_engine/engine/queue_runner.py, mergify_engine/rules/__init__.py, mergify_engine/rules/live_resolvers.py, mergify_engine/tests/unit/actions/test_queue.py, mergify_engine/tests/unit/rules/test_get_rule_checks_status.py
The value expanders of the DatetimeFitler/IncompleteFilter was not set
making teams resolution failing.
Change-Id: Ia039edd718d2c7881c65310920c50ceb959fad2a
=> fix(rules): always resolves teams in filters

mergify_engine/delayed_refresh.py
Fixes MERGIFY-ENGINE-2GJ
Change-Id: Ib05e9590c08b55519486ea567a8b2e2437dd7816
=> fix(delayed-refresh): don't fail to refresh on team resolution failure

mergify_engine/actions/review.py
If the bot_account is set, we must filter review by bot_account instead
of Mergify bot.
Fixes MRGFY-778
Change-Id: I02dfd44d5cf0cf825769e89e6d1a769b04d5f06d
=> fix(review): use bot_account to filter review

mergify_engine/context.py
Fixes: https://github.com/Mergifyio/mergify-engine/security/code-scanning/1
Change-Id: I7c1cd8b016f528ae7c424a24bfb3fc4724839356
=> fix(context): body with multiline comments

mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/test_train.py
Fixes MRGFY-756
Change-Id: Ibe2dd0d5f00a3b7ce63bad7f9fca5507e2d3aac2
=> fix(queue): requeue when priority changes

docs/source/conditions.rst, mergify_engine/context.py, mergify_engine/rules/parser.py, mergify_engine/tests/unit/rules/test_parser.py, releasenotes/notes/queued-at-6c3b086c1425d3f2.yaml
Change-Id: I98fc0c2e6887c416586386eb8988125880aa41e7
=> feat(conditions): add queued-at

docs/source/actions/queue.rst, mergify_engine/actions/merge.py, mergify_engine/queue/__init__.py, mergify_engine/queue/merge_train.py, mergify_engine/queue/naive.py, mergify_engine/rules/__init__.py, mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/tests/unit/test_train.py, mergify_engine/web/api/queues.py, releasenotes/notes/queue-allow_speculative_checks_interruption-1a971a0cd3dc0720.yaml
Fixes MRGFY-772
Change-Id: I20b319747a2858709ea9dad54cbbf44df233be5a
=> feat(queue): allow to never interrupt speculative checks

.mergify.yml
Change-Id: I04c78a95807fd61f66235ba5d2a550eb3c0936b6
=> ci(mergify): add a release note check

mergify_engine/actions/__init__.py, mergify_engine/actions/assign.py, mergify_engine/actions/copy.py
Change-Id: Ia9aa08084c6a554208b49b4bcb36b3ffd6ce5387
=> fix(assign): don't assign already assigned people

mergify_engine/actions/merge_base.py
We still log the old one for a while just in case.
Fixes MRGFY-729
Fixes MRGFY-730
Fixes MRGFY-731
Fixes MRGFY-736
Fixes MRGFY-752
Change-Id: I79116d109640be813b99abe30669777745ea77c5
=> fix(queue): enable new get_rule_checks_status()

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
Change-Id: Id30bc7da6f98bba6d90c41bbda921224f082102d
=> fix(worker): show dedicated in mergify-worker-status

mergify_engine/actions/review.py
Change-Id: Ifc139a64d5c73f94d6ec8a3bc8de2755911da8a4
=> chore(review): compute the final reviews list to be able to log it

.github/workflows/semantic-pull-request.yaml
Change-Id: I4dfa76477f61ea0b17ed8d386d662244d4c256e1
=> ci(semantic): enable head branch filter

mergify_engine/context.py
Change-Id: Ia8c5abad4bb3d833da88e1da1a8145ba5bc1af58
=> refactor(context): remove useless if

mergify_engine/context.py, mergify_engine/github_graphql_types.py
Change-Id: I53bc7d650c278fb300c6e9b6ab70e292e69f4e52
=> chore(context): cache review threads

mergify_engine/worker.py
Related MRGFY-697
Change-Id: I92b4b021845d180127ec92cb4422b3c7ef263d33
=> chore(worker): remove useless variable

.github/workflows/ci-docker.yaml, .github/workflows/docker-upload-dockerhub.yaml, .github/workflows/docs-upload-gcp-prod.yaml, .github/workflows/docs-upload-gcp.yaml, .github/workflows/semantic-pull-request.yaml, .github/workflows/syncer.yaml
Change-Id: I4248b7dc866a31381fdd8de6c4957441e775202e
=> ci(workflow): set a timeout for all workflows

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
Change-Id: I08825170d71e55286735b3a04a1190cc866e5ab3
=> refactor(worker): don't use owner_login from bucket key

mergify_engine/migrations/cache/0003_drop_legacy_attempts.redis, mergify_engine/tests/unit/test_migrations.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
Related MRGFY-697
Change-Id: I0176621057c0e9ee105ea0a27c9c3e2f7374108b
=> refactor(worker): don't use repo_name in attempts key

mergify_engine/worker.py, mergify_engine/worker_lua.py
Related MRGFY-697
Change-Id: Ibcd948521c7dfcb7a210a5a9ad69da130846c56b
=> refactor(worker): use bucket Redis key for push()

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
Change-Id: I10878b3cf7d34471a0269b0ae7ea6949c3b4bbb6
=> refactor(worker): don't use owner_login in scheduler tools

mergify_engine/worker.py
Change-Id: Ia75eee4dc44ee95ae3e41950f29426e5c5ed6f91
=> refactor(worker): use owner_id in worker-status tool

mergify_engine/delayed_refresh.py, mergify_engine/github_events.py, mergify_engine/tests/unit/test_utils.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
Change-Id: I6e4f8995a7f5239efa9d11581a2d338bee9b5c6a
=> refactor(worker): remove usage of login/name in redis keys

.github/workflows/ci-pep8.yaml, setup.cfg, tox.ini
Change-Id: I4a1131cc4c1cef5d591b7c7aac2bf7c1119a5028
=> ci(releasenotes): lint reno files

.mergify.yml
Change-Id: I3a07251b8533e4709e52f74637c71347a8618377
=> ci(mergify): improve feature requirement check

mergify_engine/tests/unit/actions/test_merge.py, mergify_engine/tests/unit/actions/test_queue.py, mergify_engine/tests/unit/actions/test_request_reviews.py, mergify_engine/tests/unit/conftest.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_behind.py, mergify_engine/tests/unit/test_command.py, mergify_engine/tests/unit/test_duplicate.py, mergify_engine/tests/unit/test_signals.py, mergify_engine/tests/unit/test_synchronize.py, mergify_engine/tests/unit/test_train.py
Many tests use the same technique to create a fake context.
This updates them to use a pytest fixtures
Change-Id: I5175c7ca7479fadb95b1b61288bdedf42f459c55
=> refactor(tests): create a fixture for fake context

.mergify.yml
Change-Id: Ib3b337c8bf8439e90d2c658a99f050444d6f0c7f
=> ci(mergify): fix typo in documentation path

.mergify.yml
Change-Id: I461f19a6620b3bbcf864a7a286ac863c25ac8bd1
=> ci(mergify): fix typo ticket template

mergify_engine/rules/parser.py, mergify_engine/tests/unit/rules/test_parser.py
Fixes MRGFY-815
Fixes MERGIFY-ENGINE-2H0
=> fix(parser): issue when matching with an empty value

mergify_engine/json.py
Fixes MERGIFY-ENGINE-2H7
Change-Id: I1d03ee3eafd994cc00b1146df435291fc5f2016d
=> fix: readd StrictMergeParameter enum

docs/source/actions/queue.rst, docs/source/spelling_wordlist.txt
Change-Id: I8ecff82a7e63755b61189bb86f6d23b6e9a84c08
=> docs(queue): add example to get notification

mergify_engine/engine/queue_runner.py
Change-Id: If61a0a3f1b11922fad5bb0ed398afca1a559050d
=> chore(queue): log draft pull request unexpected event

mergify_engine/engine/queue_runner.py
pull.base.sha is really unreliable, it can now changes even after the
pull request has been created.
To detect if the draft pull request has been changed, just relies on
events.
Fixes MRGFY-847
Change-Id: I57ff248fc2afe620f3031739085c1be0d11a46a4
=> fix(queue): don't rely on base/sha

requirements.txt
Change-Id: Ic7e4947976fd49bf539d8136d89bacb1086ee1f2
=> chore(deps): bump fastapi 0.71.0 and starlette 0.17.1

mergify_engine/queue/merge_train.py
This method may create a draft PR or rebase inplace the original PR.
As this mark when we start checking the pull requests for mergeability.
_start_checking_car() works better.
Fixes MRGFY-849
Change-Id: I0420d0c00718a31d4c82799c7d02358b0e81cd12
=> chore(queue): rename _create_car -> _start_checking_car

mergify_engine/web/api/queues.py
Change-Id: Ie3bfef2e93cc7812b3941676e8cebd20eef5d6f1
=> fix(api): handling train car in pending creation_state

mergify_engine/queue/merge_train.py
Change-Id: Id865973f6a98d6e397d0012a2cc60424cffe70ba
=> chore(queue): typo in pull request number

mergify_engine/actions/merge_base.py, mergify_engine/context.py, mergify_engine/gitter.py, mergify_engine/rules/__init__.py, mergify_engine/signals.py, mergify_engine/tests/functional/base.py, mergify_engine/utils.py, setup.cfg
Change-Id: I6897fd90933a85dc04648fcf10cac3c910875805
=> chore(deps): unpin mypy

installer/package-lock.json
Fixes MRGFY-852
Change-Id: I1037da8b3c0270c4f5abbac473452b87ec3dba76
=> chore(deps): upgrade all install js deps

.github/workflows/ci-test.yaml, .mergify.yml
Use test instead of py310 and remove useless rules.
Fixes MRGFY-864
Change-Id: Ie1929a6fa786b614e06d127b27a824169db3f8fc
=> ci(mergify): sync configuration with dashboard

mergify_engine/exceptions.py
This ignores these repositories.
Fixes MERGIFY-ENGINE-2GZ
Change-Id: I578ee57a26acb7290b43dace2cabe995253af73c
=> fix(engine): handle correctly dmca restricted repo

mergify_engine/exceptions.py
Fixes MERGIFY-ENGINE-2HM
Change-Id: I5a307744462264c26703154070d22d7f53f510d3
=> fix(exception): handle client side error without reason

mergify_engine/engine/commands_runner.py
Fixes MERGIFY-ENGINE-2HW
Change-Id: Ic398f271eb0573dea7de47fb2c4b1e1a3d4912e8
=> fix(command): restriction conditions must be copied

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
As we use a new StreamProcessor each worker task we need
to store accounts mapping in Worker itself.
Fixes MRGFY-881
Change-Id: I203069146556274848b444af976faf93be289763
=> fix(worker): dd_tracer resource name

mergify_engine/duplicate_pull.py
Fixes MERGIFY-ENGINE-2J1
Change-Id: I4d5bf8fb7432f7be995fb35d1aaa45fc59417cfb
=> fix(duplicate-pull): handle race when pull request already exists

mergify_engine/github_events.py
Even if these attributes are not used by the engine. It
usefull to have it in logs.
Change-Id: I910276a9b763a96f2df0472f57456f4be13f57e0
=> chore(events): add more checks info

mergify_engine/queue/merge_train.py
Change-Id: I67db65c69050095ba9114234e4636d883c33b368
=> fix(queue): improve message when pull requests ahead in queue is removed

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
This change allows to select services to start within a worker.
Fixes MRGFY-888
Change-Id: Ida1997c0ad02434e280118cc24e9157f2d55fb97
=> feat(worker): allow to select service to start

mergify_engine/actions/queue.py
Change-Id: I3ef2e2e384ed6e9f1330d682bbc75156e6dbb328
=> chore: remove dead code

mergify_engine/queue/merge_train.py
Change-Id: Ib8b24e744506bb2eaef4430b20af373fb50fdc15
=> chore(queue): add queues in some logging

mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/test_train.py
When the car ahead in the queue has been checked, we should never
unqueue it until all PR of the car has been merged.
Fixes MRGFY-902
Change-Id: Ib8d7837d100168e979c998494e0dfaaa83f85748
=> fix(queue): never interrupt a checked car

.github/workflows/ci-test.yaml
Change-Id: I6b7b0e5ef07095a1f419d30e243d17f1a8ff9860
=> ci(python-version): run test with python3.10

mergify_engine/web/config_validator.py, mergify_engine/worker.py, setup.cfg, tox.ini
Depends-On: #4061
Depends-On: #4062
Fixes MRGFY-827
=> ci: replace bandit by semgrep

.mergify.yml
This error is reported by yamllint and got introduced by #4070
Change-Id: Ifc1744dc156eeedb16ed9792ff827d2211c97fa1
=> ci(mergify): fix configuration indentation

.mergify.yml
Change-Id: I83d980962ef5ae3d95dfa0dc966977ad182b21e5
=> ci(mergify): allow revert keyword for hotfix

tox.ini
Change-Id: I1e5307d7ec25d7c4b4194740d3c5c8fee6e1a474
=> ci(tox): ensure tox don't fallback when python version is wrong

mergify_engine/tests/unit/test_logging.py
Add a test on our log formatter
Change-Id: I41bba1d564f191cc4204342c6d7b9f035eaa403f
=> test(logging): add formatter test

docs/source/_templates/navbar.html
This is reported by semgrep strict mode.
Change-Id: Ibc726a5f8671f19caa86f86ecd458efd4fe46866
=> fix(docs): add rel="noreferrer"

run-tests.sh, tools/check-obsolete-fixtures.sh
Change-Id: Ib54babf425317cb4aaf04d72f3fa50ec7145c530
=> ci(semgrep): fix all bash issues

mergify_engine/redis_utils.py, mergify_engine/web/config_validator.py
Change-Id: Ia3ee48d6c3ab50fe6262203180ae774db2ab063a
=> ci(semgrep): ignore sha1 warning

entrypoint.sh
Change-Id: I2768ba9ea0d6497db115b454077fa224c9410da0
=> ci(semgrep): escape some bash variables

.github/get-latest-python-version.py, .github/updatecli.yml, .github/workflows/updatecli.yaml
Change-Id: I20fdfac958766cd8b92824ebf2ae6bf598166cf3
=> ci(updatecli): Add tools to automatically update python version

mergify_engine/tests/unit/test_admin.py
Change-Id: I69a22b7817fb92de98830f8e7edf9bd383fa9279
=> fix(semgrep): no subprocess shell=True

docs/source/_extra/api/index.html, docs/source/_templates/layout.html
Fixes semgrep html.security.audit.missing-integrity.missing-integrity
Change-Id: I279a4fe9e6d47bec743c8e931e794b1d1fe713ef
=> ci(docs): add some html integrity tag

mergify_engine/gitter.py
Fixes python.lang.security.audit.dangerous-asyncio-create-exec.dangerous-asyncio-create-exec
Change-Id: Ie53126bdc7024c715cdcf273bd26788d7b3beef2
=> ci(semgrep): track create_subprocess_exec potential issues

mergify_engine/web/config_validator.py
md5 -> sha1
Change-Id: I71ea9dc2278da08a181761cce2b4c828d801df82
=> ci(semgrep): fix typo in rule name

mergify_engine/signals.py
Change-Id: I4885fadf67692dd89a256569c3a61c5da8c76010
=> ci(semgrep): ignore python.lang.security.audit.non-literal-import.non-literal-import

mergify_engine/queue/merge_train.py
If for some reason the draft pull request branch is not deleted
correctly. The next time we create it, we should first delete the old
one and create the new one.
The current code was deleting the old one, but miss to recreate it and
then when we tried to merge the TrainCar PRs inside it was failing.
It's still unclearer how the draft pull request branch does not get
delete initially.
This change ensures we will recover correctly if this occurs.
=> fix(queue): fix deletion of draft pull request

mergify_engine/queue/merge_train.py
TrainCar can be associated to only 1 queue so add a helper.
Change-Id: Idce1d1d84d574c207a10405ba91327271d2c283c
=> refactor(queue): add help to get TrainCar queue name

mergify_engine/queue/merge_train.py
Since we fix the root bug, we can remove that.
=> chore(queue): remove useless retry

setup.cfg, tox.ini
Change-Id: I2704b49a514ccd6c31102d28f1a79ec506f66249
=> ci(tox): don't install semgrep on macos

docs/source/configuration.rst
Change-Id: Ib7067b3cb00d71d0b346822520be00d51e5d399c
=> docs(template): add example to split body

mergify_engine/config.py, mergify_engine/context.py, mergify_engine/debug.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/conftest.py, mergify_engine/tests/unit/test_context.py, mergify_engine/tests/unit/test_engine.py, mergify_engine/tests/unit/test_github_events.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/utils.py, mergify_engine/web/api/queues.py, mergify_engine/web/redis.py, mergify_engine/web/simulator.py, mergify_engine/worker.py
In order to implement the QueuePause feature, we
introduce the new RedisQueue database that will store
operating datas about Trains/Queues during engine running
Fixes MRGFY-946
=> feat(queue): added RedisQueue database

mergify_engine/tests/unit/test_count_seats.py, mergify_engine/usage/last_seen.py, mergify_engine/web/dashboard.py, mergify_engine_signals/usage/__init__.py, setup.cfg
This tracks the last time we automate something for someone.
Fixes MRGFY-932
Change-Id: Ife478bffaef868e0830144efca864de280eeab81
=> feat(signals): store last seen action

setup.cfg
Change-Id: I34b376707a955471a1aebbe381b7e2177159d345
=> chore(tox): pin all development libs

mergify_engine/worker.py
Change-Id: I62f64326597e9b1902d0eafe6a85b5010773c44b
=> chore(queue): make StreamProcessor redis_queue mandatory

mergify_engine/clients/github.py, mergify_engine/clients/github_app.py, mergify_engine/clients/http.py
Change-Id: I81162c8a0aac7e9d02b9ea665e9de7562896cf87
=> chore(mypy): add missing typing to clients/

mergify_engine/config.py, mergify_engine/tests/bridge.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/dashboard/test_cache.py, mergify_engine/tests/unit/test_count_seats.py, mergify_engine/tests/unit/test_forwards.py, mergify_engine/tests/unit/test_web.py, mergify_engine/utils.py, mergify_engine/web/auth.py
This will allow to rotate webhook secret
Fixes MRGFY-948
Change-Id: Iaadc443b8fb33452e5c8887c86c4bb2fb8aa8c39
=> feat(webhook): allow a second webhook secret

docs/source/configuration.rst
Just tell we support it with one example.
Fixes MRGFY-912
Change-Id: Iecbc71993ee838f2ab18a08d456d4c402657e008
=> docs(yaml): add section about yaml anchor

mergify_engine/tests/unit/test_train.py
This improves readability of some tests to have speculative check,
batch_size, prio-level and allow_check_interruption is names.
Change-Id: If824f5ed340bdfa374395b757465e61cb479c291
=> chore(queue): rename queue names used in tests

mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/test_train.py
Change-Id: I347ffb62753e20d3cb7a38c09b7c3d15531284b1
=> fix(queue): always break speculative checks between queues

mergify_engine/check_api.py
Fixes MERGIFY-ENGINE-2K5
Change-Id: I1a13441d445034834fc9cf7f940e300d64de20b6
=> fix(checks): handle check-runs 422 when commit has been deleted

mergify_engine/worker.py, setup.cfg
Since msgpack 1.0.0 this is the default.
Change-Id: Idd31588c720a0dbd676201ea1b4590b2fba7e61e
=> chore(msgpack): don't use use_bin_type

mergify_engine/queue/merge_train.py
Fixes MRGFY-971
Change-Id: Idbc4cf743f9c6f21748156a60289ffbb08bd2730
=> fix(draft_bot_account): also impersonate the branch and commits creator

docs/source/actions/queue.rst
=> docs(queue): add missing premium tag on disallow_checks_interruption_from_queues

mergify_engine/queue/merge_train.py
Change-Id: I4a30314ffa79163908c4a36392547846d68bd785
=> chore(queue): add some logs

mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
=> fix(rules): cast InvalidDatetime exception

mergify_engine/count_seats.py
On GHES, if an org uninstall Mergify app, when should just ignore it
from users counts.
Fixes MRGFY-987
=> fix(ghes): handle when Mergify got uninstalled from an org

docs/source/actions/queue.rst
Change-Id: I8a6f4840d6417f59e9bb5f9a19e1666f3b8f86fb
=> docs(queue): add note for Slack notification

mergify_engine/constants.py, mergify_engine/engine/__init__.py, mergify_engine/tests/unit/test_engine.py
This code can be run only when the pull request is opened or
synchronized.
Depends-On: #4271
Fixes MRGFY-986
Change-Id: I43b29cae06bfc25a8d51758586e71e2307b3fcbf
=> fix(config): don't always run configuration detector

requirements.txt
Change-Id: I476420ac7ae4b56dc7cf76bfaa56784dec070e3d
=> chore(deps): bump httptools and uvicorn

mergify_engine/worker.py
Fixes MRGFY-998
Change-Id: Iffb79a488dac58928bef757c5bb672d1f8b15403
=> feat(sentry): set gh_owner in worker

mergify_engine/rules/conditions.py, mergify_engine/tests/unit/rules/test_rules.py
Description of RuleConditionGroup is not display in QueueRuleConditions
summary.
Fixes MRGFY-1013
Change-Id: I4dcfd0ae24094072b41015960124a8453d698861
=> fix(conditions): display description in conditions group

mergify_engine/engine/__init__.py
Fixes MRGFY-1010
Change-Id: Id9a7cfb5195442bb5bd5c83cac90af95fcb90e5d
=> chore(config): log allow_inplace_checks usage

mergify_engine/queue/merge_train.py, mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/tests/unit/test_train.py
Change-Id: I8103968f4e185e8e15d5d9b65bd90a2092cf7198
=> chore(queue): use dataclasses for EmbarkedPull

mergify_engine/web/api/security.py
Fixes MRGFY-998
Change-Id: Idc9597aa59dd09f01346ceaaf29c9c733d7746bc
=> fix(sentry): add tags to queues API

mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/test_train.py
Fixes MERGIFY-ENGINE-2KS
Change-Id: If23908243451dceb6ee5be3f077d3e593425df8c
=> fix(queue): deserialization of old EmbarkedPull format

.github/workflows/docs-upload-gcp-prod.yaml
Branches has been renamed, we must use version instead.
Change-Id: I7143fa48dc3490c57bc0588a43e7727d248a15e5
=> ci(docs): set version of google-github-actions

mergify_engine/web/api/security.py, mergify_engine/worker.py
Change-Id: Ie2a8dde636d32a5e51a5f43768b730432eb91faa
=> chore(sentry): use org login as sentry user

mergify_engine/queue/__init__.py, mergify_engine/queue/freeze.py, mergify_engine/queue/merge_train.py
Change-Id: I5b129d577c387c29bdeb24cd5f8d56816a38fab4
=> chore(queue): remove useless param of refresh_pulls()

mergify_engine/tests/unit/actions/test_merge.py
Change-Id: I33a2690605630d9d5a1a3fa02ffa60e72cd1781c
=> test(commit-message): add more

mergify_engine/github_events.py
No need to look for @mergifyio, the commands_runner.on_each_event already
does it.
Related MRGFY-1024
Change-Id: Idbe6ea4ff9749fc0b7effccc751a582ebd090d1b
=> chore(command): remove useless check

mergify_engine/engine/__init__.py
Current implementation looks at the option in pull request rules instead
of queue rules.
This fixes that.
Change-Id: If331fa1bc799e4b55d9e51424871732d5bae2682
=> fix(queue): logging of allow_inplace_checks

docs/source/actions/queue.rst
There are some paragraphs that are under the Example section but do not
belong here. Move them up.
=> docs(queue): fix section ordering

mergify_engine/json.py
This is not used anymore and all PR using it should have been merged by now.
=> refactor(json): remove StrictMergeParameter

.github/workflows/ci.yaml
Change-Id: I43c1631f5beba8484dfe5ecc4aa4f3ed3361f570
=> chore(heroku): bump buildpacks/pack to 0.24.1

installer/src/App.jsx
Change-Id: Ib3cf1751b3a0d5a44df0496f027eace49ebdd00f
=> fix(installer): add missing permissions

mergify_engine/actions/edit.py, mergify_engine/tests/functional/actions/test_edit.py
Change-Id: Iac2936b7140c19e9f9bd750b751a57d064c5cf06
=> fix(edit): requires GHES >= 3.2

installer/src/App.jsx
Change-Id: I57d9c88882990691f6e03053dca5acde543cf631
=> fix(installer): bootstrap 5 compat

mergify_engine/tests/functional/actions/test_merge.py
Change-Id: I2846a252000cfe509f5be2c62668988d65fa7ae3
=> fix(tests): skip required_conversation_resolution tests on GHES

mergify_engine/web/root.py
=> chore(fastapi): add some notes about CORS configuration

mergify_engine/tests/conftest.py, mergify_engine/tests/unit/test_engine.py
test_engine takes 1s instead of 3s.
pytest-httpserver check_assertions() was clearly missing some uncalled
mock...
Depends-On: #4415
Change-Id: I00f9159f6d7ba9a067613901c9dfd4cd472b3944
=> chore(tests): replacing pytest-httpserver by respx part 2

mergify_engine/queue/merge_train.py
Related MRGFY-1061
Change-Id: I685d7a2838eb813336e4376ebcd414edf92d2719
=> chore(queue): add logging to merge-queue pr creation

mergify_engine/engine/actions_runner.py
Change-Id: Ifd1a3a432541d4784eebb00b0c9d8604c88f9085
=> chore(engine): don't log the documentation

mergify_engine/queue/merge_train.py
Change-Id: I7f675d77a5e1914caa3b0de551c9d89e88e842e3
=> chore(queue): add logging to _clean_unsused_merge_queue_branches

mergify_engine/branch_updater.py, mergify_engine/github_types.py, mergify_engine/queue/merge_train.py, mergify_engine/squash_pull.py
Fixes: MERGIFY-ENGINE-2MC
Change-Id: I2de9aaa8396b9f7138f85dc0178990fa3ec6fd9d
=> fix: handle when forked repository is deleted

mergify_engine/tests/unit/test_clients.py
This test is flaky, so...
Change-Id: I60b88dba2560423d53809f9984c4b5a48ff1ea5d
=> fix(tests): increase tolerance of http after-at timing tests

mergify_engine/queue/merge_train.py
This moves the check later in the process so it will be used only when
really needed.
Change-Id: Idffdf529299f3930b1561063d031ea5bf3a03118
=> refactor(queue): move existence check of draft pull request

mergify_engine/actions/dismiss_reviews.py
Change-Id: Ia66389b6e0993191d979d561522fe39d934d8759
=> fix(dismiss_reviews): don't track when the action does nothing

mergify_engine/worker.py
Change-Id: Id9c9fc4487e98776ce39c1d14f80b3bb2049a994
=> chore(worker): tag latency per worker

mergify_engine/context.py
get_mergify_config() and ensure_complete()
Change-Id: Ic9e81facb27a70960f79ac070f2328a466a06982
=> chore(config): trace some context method

mergify_engine/worker.py
Change-Id: Iaf2f3988b0855875aa0844a526eff29fcd34f00e
=> chore(worker): track the time it takes for do pull request look up

mergify_engine/queue/merge_train.py
Change-Id: Ia01a62241f1c5b9dd064e4d4a60d4d7c6c6e5576
=> chore(queue): trace some merge-queue methods

mergify_engine/queue/merge_train.py
Fixes MERGIFY-ENGINE-2MJ
Change-Id: If1fa37f3f6635ee44ddef6e622bbcd6e689ebdf1
=> fix(queue): add missing import

mergify_engine/check_api.py, mergify_engine/clients/github.py, mergify_engine/exceptions.py, mergify_engine/worker.py
=> fix(engine): don't handle pull request with more than 500 check-runs

mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
=> fix(rules): add string check for batch_max_wait_time

mergify_engine/actions/edit.py
=> fix(edit): error handling of bot_account

mergify_engine/context.py
=> fix(context): handle huge PR gracefully

mergify_engine/actions/copy.py, mergify_engine/actions/delete_head_branch.py, mergify_engine/check_api.py, mergify_engine/clients/github.py, mergify_engine/context.py, mergify_engine/count_seats.py, mergify_engine/debug.py, mergify_engine/duplicate_pull.py, mergify_engine/engine/commands_runner.py, mergify_engine/queue/merge_train.py, mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/functional/commands/test_backport.py, mergify_engine/tests/functional/commands/test_copy.py, mergify_engine/tests/functional/test_configuration.py, mergify_engine/tests/functional/test_engine.py, mergify_engine/tests/functional/test_github_async_client.py, mergify_engine/tests/unit/test_duplicate.py, mergify_engine/worker.py
Not all api calls need a page limit of 100, so make it mandatory.
This also allows to report page limit to user everywhere.
=> fix(github): set a page_limit everywhere

mergify_engine/context.py
=> fix(labels): increase a bit number of page for labels

mergify_engine/engine/actions_runner.py
=> fix(engine): ensure UnprocessablePullRequest go back to worker

mergify_engine/engine/commands_runner.py
Fixes MRGFY-1024
Fixes MRGFY-1054
=> chore(command): remove useless code

mergify_engine/duplicate_pull.py
Change-Id: If4bff07d46c279103b6755f3459fe486109ee4ec
=> fix(ghes): set api version for some endpoint

mergify_engine/engine/commands_runner.py, mergify_engine/tests/unit/test_command.py
Fixes #4495
Change-Id: If2ef050ab4fe6895377c3de1f1634cbf85c8be5f
=> fix(command): do permission check after command lookup

mergify_engine/tests/unit/test_signals.py, mergify_engine_signals/_datadog/__init__.py, setup.cfg
Fixes MRGFY-1087
Change-Id: Ib531ed95ecd2910ba94a070b82b94d2fcd8d214f
=> refactor(signals): move back datadog signals

mergify_engine/tests/unit/test_clients.py
Change-Id: I5cab5a1376427a0e541f63947e4b405c0fa2a344
=> ci(ghes): fix test_client_installation_HTTP_301

setup.cfg
Change-Id: Ie12ca15273d268ae97570ecdc8d5102cbef0d599
=> fix(ddtrace): remove capping

mergify_engine/worker.py
Change-Id: Ic3fb26d09f9f5b7490b38ee38a269280a2375787
=> chore(worker): name all asyncio tasks

.github/updatecli.yml
Change-Id: I0f98ef6ce60e0211acf9388e3b8ef6c868218d46
=> fix(updatecli): fix location of some jobs

mergify_engine/actions/delete_head_branch.py, mergify_engine/check_api.py, mergify_engine/clients/http.py, mergify_engine/duplicate_pull.py, mergify_engine/engine/__init__.py, mergify_engine/queue/merge_train.py
Some old plans of GitHub are not able to handle draft PR. We
needed to handle this case properly when train tries to create
a draft PR
Fixes MRGFY-1085
=> fix(train): handle error when draft PR is not supported by user

.github/workflows/semantic-pull-request.yaml, .semgrepignore, mergify_engine/tests/bridge.py, mergify_engine/tests/functional/test_engine.py
Change-Id: I537cf17b0a191ec42998548589927b19d3bb0b2f
=> fix(semgrep): fix new rules

mergify_engine/dashboard/application.py, mergify_engine/tests/functional/api/test_auth.py, mergify_engine/web/api/security.py, zfixtures/cassettes/api/test_auth/test_api_auth_scoped/config.json, zfixtures/cassettes/api/test_auth/test_api_auth_scoped/http.json
=> fix(api): make scope case insensitive

mergify_engine/context.py
Change-Id: I8b04281d758a0c2c6168b9150cd8a6edf9a771dc
=> fix(context): increase page limit for files api

setup.cfg
This adds the --profile option for pytest.
=> test: install pytest-profiling

tox.ini
Change-Id: I0f0b128f7b67e768f4ead1a6893a4fdf5f259463
=> test(tox): fix honcho port syntax

mergify_engine/tests/bridge.py
Change-Id: I4e264f5b8d460c2118952d04071a1b883eafb0e9
=> test(bridge): add missing await

mergify_engine/context.py, mergify_engine/rules/filter.py, mergify_engine/rules/types.py, mergify_engine/tests/functional/test_attributes.py, mergify_engine/tests/functional/test_debug.py, mergify_engine/tests/unit/rules/test_filter.py, mergify_engine/tests/unit/rules/test_get_rule_checks_status.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_context.py
In case of #commits or #files is used, this avoid doing any http
requests to get the number.
Change-Id: I9a8d3882b6fa99689bb31f8a83128ae4f8cff935
=> refactor(context): add len attribute optimisation

mergify_engine/actions/queue.py
Fixes MRGFY-1128
Change-Id: If1e36116cbe3717f7c7095c30ccb75e300cf5868
=> fix(queue): report cancelled reason

mergify_engine/context.py
pipeline was declared but not used
=> refactor(redis): use pipeline instead of direct redis call

mergify_engine/worker.py
If a pull request returns an HTTP 500 we retry only the pull request
instead of the whole streams.
Change-Id: Ic3841d9a2fd1874e9af4b62cd9c9cf977b42731b
=> fix: retry only pull request on HTTP 500

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
If task.cancel() was called during a work sleep, this one was ignoring
the cancellation, instead of quitting the loop.
Fixes MRGFY-1139
Change-Id: Idf48d35d3821af6227e6c3dc426f4762a2e3567e
=> fix(worker): worker task cancellation during sleeping

mergify_engine/exceptions.py
Fixes MERGIFY-ENGINE-2NF
Change-Id: Ieb8c46167040005ccdfc956a42ff0baefe6b30e2
=> fix(worker): ignore new `too many files changed` error

mergify_engine/github_events.py
Change-Id: I44db691b7bd4bb37885371b2a885f94452e0be6a
=> chore(github-events): log more check-runs info

mergify_engine/queue/merge_train.py
Related MERGIFY-ENGINE-2NJ
Change-Id: I46e24eb29c5c499192bc95323ecc709e5d3d8e00
=> chore(queue): improve logging when merge-queue pr creation failed

mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/tests/functional/commands/test_unqueue.py
Change-Id: I142360f3e746edd7850d76460c5da80dd706e319
=> chore(mypy): add type to test_unqueue

mergify_engine/check_api.py
Change-Id: I11c913424136b92b7bae2699014a7d0dedea3725
=> chore(check_runs): add some logging

mergify_engine/config.py, mergify_engine/web/redis.py
We should be able to configure each kind of Redis clients with different
configuration.
=> chore(redis): add REDIS_QUEUE_WEB_MAX_CONNECTION

mergify_engine/context.py
Change-Id: I05f3457433c5d744af3afe81e25ac3e16f32867c
=> chore(context): log when we reach the Pulls commits API limit

mergify_engine/actions/assign.py, mergify_engine/actions/backport.py, mergify_engine/actions/close.py, mergify_engine/actions/comment.py, mergify_engine/actions/copy.py, mergify_engine/actions/delete_head_branch.py, mergify_engine/actions/dismiss_reviews.py, mergify_engine/actions/label.py, mergify_engine/actions/merge.py, mergify_engine/actions/post_check.py, mergify_engine/actions/queue.py, mergify_engine/actions/rebase.py, mergify_engine/actions/refresh.py, mergify_engine/actions/request_reviews.py, mergify_engine/actions/requeue.py, mergify_engine/actions/review.py, mergify_engine/actions/squash.py, mergify_engine/actions/unqueue.py, mergify_engine/actions/update.py, mergify_engine/signals.py, mergify_engine/tests/unit/test_count_seats.py, mergify_engine/tests/unit/test_signals.py, mergify_engine/usage/last_seen.py, mergify_engine_signals/_datadog/__init__.py, mergify_engine_signals/noop/__init__.py, mergify_engine_signals/usage/__init__.py
This should helps to type event logs subsystem
Fixes #4691
=> refactor(signals): rework signal interface

mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/test_train.py
Fixes MRGFY-1084
Change-Id: I05c913964da778532a91eff9efb71a088ca7c918
=> fix(queue): re-embarked sentence when pr is unqueued

mergify_engine/queue/merge_train.py, mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/tests/unit/test_train.py
Name it for what is mean for the merge queue instead of what it does.
Change-Id: I3774ead8eeb54e519f9113bd2b3ddc2382706eaf
=> refactor(queue): rename some methods

mergify_engine/queue/merge_train.py
Change-Id: I8cdcd967fe67d34ba14542ab26b7b221b268d5c8
=> fix(queue): fix an ending emoji

mergify_engine/engine/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
Change-Id: I4183085263798de24773a958f4eee6dc6ded6077
=> chore(config): remove unused logs

docs/source/actions/queue.rst, mergify_engine/actions/queue.py
This reverts commit e872a981f969a97f90555cdb42b6c412f06d72eb.
Fixes MERGIFY-ENGINE-2P0
=> revert: "fix(queue): add message when branch protection is misconfigured (#4748)"

mergify_engine/context.py
This allows to replay the configuration changes to debug it.
=> chore(context): log the merge_commit_sha

requirements.txt, setup.cfg
Change-Id: If420a6db68b77dd1ac7937392249b5ba54d9b944
=> chore(deps): upgrade ddtrace

mergify_engine/context.py, mergify_engine/count_seats.py, mergify_engine/debug.py, mergify_engine/delayed_refresh.py, mergify_engine/exceptions.py, mergify_engine/migrations/__init__.py, mergify_engine/queue/merge_train.py, mergify_engine/redis_utils.py, mergify_engine/service.py, mergify_engine/tests/conftest.py, mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/functional/test_web_cli.py, mergify_engine/tests/unit/test_github_events.py, mergify_engine/usage/last_seen.py, mergify_engine/web/redis.py, mergify_engine/web/utils.py, mergify_engine/worker.py, requirements.txt, run-tests.sh, setup.cfg, tox.ini
The change also makes mypy discovers some un-catched typing issue.
=> refactor(redis): switch to redis-py

mergify_engine/__init__.py
Workaround for https://github.com/DataDog/dd-trace-py/pull/3793
Change-Id: Ibd8ce535be54bd186825127173007f2746f29a2a
=> fix(ddtrace): workaround for missing ddtrace pinning

mergify_engine/redis_utils.py
=> feat(redis): override service name

mergify_engine/config.py, mergify_engine/tests/unit/test_config.py
This refactor the config.py to be able to test it.
Change-Id: I592d5b869a3fa3e74efafaf9dbe22b2c758c9334
=> refactor(config): make it testable

mergify_engine/config.py, mergify_engine/context.py, mergify_engine/github_events.py, mergify_engine/logs.py, mergify_engine/redis_utils.py, mergify_engine/tests/conftest.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/test_config.py, mergify_engine/tests/unit/test_context.py, run-tests.sh
Fixes MRGFY-1197
Change-Id: I81625d6afe22da5a89ea6e53973155a15e944ea0
=> refactor(redis): split team/user permissions/members cache

mergify_engine/engine/commands_runner.py, mergify_engine/tests/unit/test_command.py
=> feat(engine): allow mergify app to be pinged with its url

mergify_engine/actions/queue.py
When the merge in cancelled because of GitHub issue (branch protection,
...) we cancel the rule.
This change also cancel the queue summary to allow the pull request to
be requeued.
Fixes MRGFY-1222
Change-Id: I909c48e81a0034b7fec6164a200f5d42f81007a6
=> fix(queue): cancel merge queue summary on merge cancellation

mergify_engine/count_seats.py
Fixes MRGFY-1216
Change-Id: I54bdf8bb01c5bf35980a985f56fe60754af72ced
=> fix(count-seats): properly close the redis connections

fake.env, installer/src/App.jsx, mergify_engine/config.py
Fixes MRGFY-1224
Change-Id: I7524db5ba00fc78b700b201e59db94576970290f
=> fix(subscription): change default url

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
=> fix(worker): replace retry an error by a metric

mergify_engine/actions/dismiss_reviews.py, mergify_engine/eventlogs.py, mergify_engine/signals.py, mergify_engine/tests/conftest.py, mergify_engine/web/api/eventlogs.py
Fixes MRGFY-1143
Change-Id: I0284285a6215877385bfff9a99c596596ebd233d
=> feat(eventlogs): add all signaled events

mergify_engine/worker.py
Fixes MRGFY-233
Fixes MERGIFY-ENGINE-2PW
=> fix(worker): handle too big pull request

mergify_engine/web/github.py
Change-Id: I0975617014791c6602e0eb64ae4c6841ef2ad9e4
=> fix(events): Never report error to GitHub on dashboard failure

.github/workflows/clifus.yaml
=> fix(github-workflow): Setup the correct python version before launching clifus script

mergify_engine/_datadog.py, mergify_engine/actions/assign.py, mergify_engine/actions/close.py, mergify_engine/actions/comment.py, mergify_engine/actions/copy.py, mergify_engine/actions/delete_head_branch.py, mergify_engine/actions/dismiss_reviews.py, mergify_engine/actions/label.py, mergify_engine/actions/merge.py, mergify_engine/actions/merge_base.py, mergify_engine/actions/post_check.py, mergify_engine/actions/queue.py, mergify_engine/actions/rebase.py, mergify_engine/actions/refresh.py, mergify_engine/actions/request_reviews.py, mergify_engine/actions/requeue.py, mergify_engine/actions/review.py, mergify_engine/actions/squash.py, mergify_engine/actions/unqueue.py, mergify_engine/actions/update.py, mergify_engine/engine/commands_runner.py, mergify_engine/eventlogs.py, mergify_engine/rules/__init__.py, mergify_engine/signals.py, mergify_engine/tests/functional/actions/test_dismiss_review.py, mergify_engine/tests/functional/actions/test_label.py, mergify_engine/tests/unit/test_count_seats.py, mergify_engine/tests/unit/test_signals.py, mergify_engine/usage/last_seen.py
This tracks and restitute what has triggered the action.
Fixes MRGFY-1241
Change-Id: I0f484d8f6fc2866134e0c1e3c4af687b1f2231bb
=> feat(eventlogs): add what trigger the action

mergify_engine/config.py, mergify_engine/count_seats.py, mergify_engine/github_events.py, mergify_engine/redis_utils.py, mergify_engine/tests/functional/test_count_seats.py, mergify_engine/tests/unit/test_count_seats.py, mergify_engine/web/dashboard.py
Fixes MRGFY-819
Change-Id: Ided4b76e680140b57d1c0afb772c4253922676ed
=> fix(seats-count): allow to use a dedicated db

mergify_engine/config.py, mergify_engine/tests/functional/conftest.py, mergify_engine/tests/functional/test_debug.py
Change-Id: I5b1c6f8f80213a65a1846caf4e06ae0f072c3aec
=> chore: remove unused testing token

mergify_engine/tests/bridge.py
Change-Id: Ia420b1e8505b25dcf6adc408d79130d3b3341fff
=> chore(tests): replace a .io to .com

mergify_engine/tests/unit/test_worker.py
To ensure good typing and avoid bugs, we added
typing on every worker tests
Fixes MRGFY-1255
=> fix(worker): add typing to tests

mergify_engine/actions/utils.py, mergify_engine/duplicate_pull.py
Since we validate bot_account ealier in the process, user see
a generic error message instead of the proposal to log into the
dashboard.
This fixes this.
Fixes MRGFY-1267
=> fix(bot-account): improve error message

mergify_engine/actions/merge.py, mergify_engine/actions/merge_base.py, mergify_engine/actions/queue.py
Change-Id: Ia3aede35a3b466c45aa7674aa7d6b3dd53ce3b4f
=> chore(merge-base): use generic instead of casting

mergify_engine/actions/queue.py, mergify_engine/actions/unqueue.py, mergify_engine/context.py, mergify_engine/debug.py, mergify_engine/queue/__init__.py, mergify_engine/queue/merge_train.py
Change-Id: Idd7f9b7d1449b789fe08e73fcde5115461992a70
Depends-On: #4969
=> refactor(queue): remove unused base class

mergify_engine/queue/merge_train.py, mergify_engine/signals.py
Fixes MERGIFY-ENGINE-2R1
Change-Id: Id35248ff2f4c63e1b1e3d1da96f8ffee24821555
=> fix(queue): ensure signal emit a valid checks_conclusion

mergify_engine/actions/copy.py, mergify_engine/actions/merge.py, mergify_engine/actions/queue.py, mergify_engine/actions/rebase.py, mergify_engine/actions/review.py, mergify_engine/actions/utils.py
The wording is a bit strange and not always clear.
This also fixes a few name that were wrong.
=> chore(actions): rephrase unavailable feature

mergify_engine/queue/merge_train.py
Change-Id: Ic00339f6a25b62ba1d8c76563330877b3c575e55
=> fix(signal): emit for QueueCheckEnd for the whole batch

poetry.lock, pyproject.toml
This will allow to partially run the test suite.
This should help to re-record all fixtures every days.
Change-Id: If3f5e432ec3df4964698d173ffb44cb43b124eec
=> ci: add pytest-chunks

mergify_engine/tests/unit/rules/test_rules.py
This test file was only partialy typed and needed
to be in its entierity.
Fixes MRGFY-1294
=> fix(tests): add typing to test_rules
