default_rule.yml, mergify_engine/rules.py
Do not enable force_admins by default
Allow null for enforce_admins
=> Pull request for enforce_admin-false

default_rule.yml, mergify_engine/gh_branch.py, mergify_engine/rules.py, mergify_engine/tests/test_config.py
ensure branch protection json is valid
Fix config default
Add branch configuration logging
=> Pull request for master

mergify_engine/engine.py, mergify_engine/tests/test_engine.py, mergify_engine/utils.py, mergify_engine/web.py, mergify_engine/worker.py
Don't return private repo to UI
Separate redis for rq and cache
Enable private repo for subscribed install
=> Pull request for sileht/subscription

mergify_engine/engine.py, mergify_engine/gh_pr.py, mergify_engine/gh_pr_fullifier.py, mergify_engine/static/controllers.js, mergify_engine/static/table.html, mergify_engine/web.py, mergify_engine/worker.py
move event filter on API side
Remove travis code from engine
Don't process installation created event
Better ratelimit log
=> Pull request for sileht/remove-travis

mergify_engine/utils.py, mergify_engine/web.py
Set the expiration to 1 hour. And
allow to clear it via API.
=> Subscription cache expiration

fake.yml, mergify_engine/backports.py, mergify_engine/initial_configuration.py, mergify_engine/web.py, mergify_engine/worker.py
Propose an initial configuration on new repos
Use baseurl for status check long message
=> Pull request for pullrequest-creation

mergify_engine/engine.py
This change adds some check to ensure the selected pull request to
proceed is still valid.
=> Fix the selection of the pr to merge

tox.ini
tox: specify python3.6 for py36
tox: remove Python 3.5 from env list
=> Pull request for fix-tox

mergify_engine/rules.py, mergify_engine/tests/test_config.py
=> rules: fix restrictions parsing

doc/source/configuration.rst, doc/source/getting-started.rst
=> doc: explain how to remove reviewers

mergify_engine/engine.py, mergify_engine/tests/test_engine.py, setup.cfg
This splits the logic between the engine and a processor.
Fixes #91
=> engine: split into two components

mergify_engine/branch_updater.py, mergify_engine/engine.py, mergify_engine/mergify_pull.py, mergify_engine/utils.py, mergify_engine/web.py, mergify_engine/worker.py, mergify_engine/wsgi.py
On merge/update error, don't retry the same PR
Capture some exceptions with sentry
=> On merge/update error, don't retry the same PR

mergify_engine/rules.py
This reverts commit 2832d194224370d96f24023b8e0a4bec1ef04c6c.
=> Revert "rules: factorize default config merge"

mergify_engine/mergify_pull.py, mergify_engine/rules/__init__.py, mergify_engine/rules/convert.py, mergify_engine/rules/filter.py, mergify_engine/rules/parser.py, mergify_engine/tests/unit/rules/test_convert.py, mergify_engine/tests/unit/rules/test_filter.py, mergify_engine/tests/unit/rules/test_parser.py, mergify_engine/tests/unit/test_config.py, setup.cfg
rules: add support for pull request rules
rules: add a parser to compile to our filter AST
rules: add filter engine
rules: declare UserConfigurationSchema as a schema
Move mergify_engine.rules to a submodule
=> Pull request for filtering

mergify_engine/rules/__init__.py, mergify_engine/rules/filter.py, mergify_engine/tests/unit/rules/test_filter.py, mergify_engine/tests/unit/test_config.py
rules: enhance next rules reporting
rules: remove or/and conditions support
=> Pull request for remove-or

mergify_engine/actions/__init__.py, mergify_engine/actions/backport.py, mergify_engine/actions/close.py, mergify_engine/actions/delete_head_branch.py, mergify_engine/actions/dismiss_reviews.py, mergify_engine/actions/label.py, mergify_engine/actions/merge.py, mergify_engine/tasks/engine/v2.py
Make action cancel like action run.
=> Rework way to cancel action.

mergify_engine/refresher.py
Rather than refreshing everything
=> refresher: print help() by default

doc/source/actions.rst, mergify_engine/actions/delete_head_branch.py, mergify_engine/tests/functional/test_engine_v2.py
=> Fix documentation for delete_head_branch

mergify_engine/actions/backport.py, mergify_engine/backports.py
Cleanly report when branch does not exists and more logging information.
=> backport: report not existing branch

mergify_engine/actions/merge.py
Github sometimes report mergeable_state == blocked for authentified
requests, but in reality the state is unstable or clean (that can be
check with anonymous request).
This change does the same workaround as engine v1 was doing. We assume
"blocked" state in a ready state and try to merge the PR, if the PR is
really blocked, Github will return a 405 and we can inform the user that
his branch protection system is conflicting with us.
=> v2: workaround for wrongly reported mergeable_state = blocked

mergify_engine/actions/backport.py
This change fixes the reporting issue in case of backport already done
but not yet recorded in GitHub Check API.
=> backport: fix reported status

mergify_engine/actions/__init__.py, mergify_engine/actions/close.py, mergify_engine/actions/delete_head_branch.py, mergify_engine/actions/merge.py, mergify_engine/tasks/engine/v2.py
=> Don't run two merge actions in one evaluation

mergify_engine/branch_updater.py
When "git" fails with "unrelated history" error, retries with
a full git clone.
=> branch_updater: Fallback to unshallowed clone

mergify_engine/tasks/github_events.py
https://developer.github.com/changes/2019-04-18-new-webhook-events-and-actions/
Two new events just appear, we can should use them.
=> Trigger mergify on two new Github events

mergify_engine/branch_updater.py, mergify_engine/debug.py, mergify_engine/sub_utils.py, mergify_engine/tasks/github_events.py, mergify_engine/tests/functional/base.py
This allows to retry the branch update with all tokens available.
=> Handle new tokens format from website

mergify_engine/debug.py
=> debug: print the number of cached tokens and catch auth GithubException

mergify_engine/actions/merge/action.py
message is forbidden for logging extra.
=> Don't use message as log extra

mergify_engine/mergify_pull.py, mergify_engine/tests/unit/test_config.py
=> rules: fix condition evaluation when using team attribute and regexp

mergify_engine/branch_updater.py
branch_update: really unshallow git clone
branch_update: Catch some new git issues
=> branch_update: fix some git issues

mergify_engine/prom_exporter.py, mergify_engine/tests/unit/test_prom_exporter.py
It will now retry for each installation.
=> Make prom_exporter more robust when a request fails

doc/source/actions.rst
This change adds some configuration example with its git commands equivalent.
=> doc: Add some git workflow equivalence

doc/source/actions.rst, mergify_engine/actions/assign.py, setup.cfg
This pull request adds an `assign` action. I have no clue how to test this out, so I suspect that there are issues, but hopefully this gets the ball rolling. This should address #450.
=> actions: Add assign action

mergify_engine/rules/parser.py
=> Add milestone into the search

mergify_engine/rules/__init__.py, mergify_engine/tests/functional/test_simulator.py, mergify_engine/tests/unit/test_config.py
tests: predictable errors order
Report more detailed errors
=> Pull request for more-errors

mergify_engine/actions/label.py, mergify_engine/utils.py
=> Ignore label creation error

mergify_engine/prom_exporter.py
=> prom: fix issue when mergify configuration is invalid

mergify_engine/backports.py
=> Don't fail if backport is already done

mergify_engine/branch_updater.py
=> branch_update: catch ssl timeout

mergify_engine/backports.py
=> backport: Ignore useless error

doc/source/conditions.rst, mergify_engine/mergify_pull.py, mergify_engine/rules/parser.py, mergify_engine/tests/unit/rules/test_parser.py
=> pr attribute: add conflict boolean

doc/source/conditions.rst
=> doc: fix typo on status success

mergify_engine/debug.py
=> debug: add repo parameter to installation id retrieval

mergify_engine/actions/merge/action.py
merge: fix race when another PR is merge in the meantime
Refactor merge action
=> Pull request for base-branch-changed

mergify_engine/tasks/engine/commands_runner.py, mergify_engine/tasks/github_events.py, mergify_engine/tests/unit/test_command.py
Our GitHub accounts is actually `@Mergifyio` and GitHub fixes the case
automatically.
=> commands: be case insensitive

mergify_engine/actions/merge/action.py
=> action/merge: merge error handling when GitHub returns 500

mergify_engine/tests/unit/test_forwards.py, mergify_engine/web.py
=> Fix content-type for forwarded marketplace event

mergify_engine/actions/request_reviews.py
This field avoid re-requesting already request reviews.
=> review_request check `review-requested` field

doc/source/_static/mergify.css, doc/source/_templates/layout.html, doc/source/_templates/navbar.html
=> Pull request for collapse-sidebar

mergify_engine/worker.py
This reverts commit 606884a3a76ee7a9c728145f0bc9b4ab6f3571ac.
=> Revert "statsd: send runtime"

mergify_engine/tasks/engine/commands_runner.py
It's weird to have a user talking with `we`.
=> commands: change wording when to use `I`

Procfile, mergify_engine/utils.py
Ensure cache use only one redis connection
Remove unused variable
=> Pull request for one-worker

mergify_engine/actions/merge/action.py, mergify_engine/actions/merge/helpers.py, mergify_engine/actions/merge/queue.py
merge: add missing merge queue cleanup
merge: simplify merge report
=> Pull request for simply-merge-report

.circleci/config.yml, .mergify.yml, pyproject.toml, setup.cfg, tox.ini
=> Migrate CI to Python 3.8

mergify_engine/branch_updater.py, mergify_engine/duplicate_pull.py
=> duplicate-pr: retry network error

mergify_engine/actions/merge/queue.py, mergify_engine/tasks/engine/__init__.py, mergify_engine/tasks/github_events.py, mergify_engine/tasks/mergify_events.py, mergify_engine/utils.py
This normalizes some logging messages to match those that use the
PullRequest logger.
=> Add more logging extra tag

doc/source/_static/mergify.css, doc/source/_templates/breadcrumb.html, doc/source/_templates/layout.html, doc/source/_templates/navbar.html
=> Documentation design enhancements

doc/source/_static/mergify.js
This works better for more complex scenarios.
=> doc: enhance jQuery match for navbar link fix

mergify_engine/actions/request_reviews.py
=> Don't request review of author

mergify_engine/debug.py
=> debug: handle mergify config missing

doc/source/_static/mergify.css, doc/source/actions.rst
=> Pull request for doc/title-for-squash-commit-message

Procfile, requirements.txt, setup.cfg, tox.ini
This reverts commit 7524554cdc353dac5f52d3638e89d283b0052251.
=> Revert "Use gevent by default"

doc/source/conditions.rst, doc/source/examples.rst
=> docs(conditions): add various notes and examples

mergify_engine/tasks/engine/commands_runner.py
=> fix(commands): warns about wrong account with correct case

mergify_engine/debug.py, mergify_engine/tests/unit/test_debug.py
=> fix(debug): don't crash on wrong URLs

mergify_engine/tasks/engine/actions_runner.py
There might be some old PR lying around with no previous conclusions, so don't
crash if we don't find them.
Fixes MERGIFY-ENGINE-16N
=> fix(actions_runner): do not crash on no previous conclusion

mergify_engine/actions/comment.py
=> fix(message): use correct status code

mergify_engine/actions/delete_head_branch.py
=> fix(delete_head_branch): handle error 500

mergify_engine/__init__.py, mergify_engine/config.py, mergify_engine/tests/unit/test_misc.py, mergify_engine/utils.py, requirements.txt, setup.cfg, tox.ini
=> feat: enable http cache

mergify_engine/__init__.py
For us, it's safe to not respect Vary: Authorization as we don't use
user token, but only installation token. As this token are only valid
for one organization/user, we can't have any permissions issue.
=> feat: don't invalid cache because Authorization differ

mergify_engine/__init__.py
=> fix: cache serialization

mergify_engine/branch_updater.py
=> fix: no need to log branch protection error

mergify_engine/duplicate_pull.py
=> fix: don't raise error if nothing need to be copied

mergify_engine/actions/merge/queue.py
=> fix: move pull to new queue when base branch change

doc/source/_static/mergify.css, doc/source/_static/mergify.js, doc/source/conditions.rst
=> Pull request for doc/regexp

doc/source/actions.rst, doc/source/conditions.rst, doc/source/examples.rst
- Rename array to list
- Explain how to use lists
- Add an example for matching files outside of a directory with a double
negative regex
- Fix the existing example
=> docs: improve document for attribute with list

mergify_engine/mergify_pull.py, mergify_engine/tests/unit/test_behind.py, mergify_engine/tests/unit/test_duplicate.py
=> fix: be more strict about pull_request payload coming from events

mergify_engine/branch_updater.py
=> chore: No need to log when remote ref have been deleted

mergify_engine/actions/merge/queue.py, mergify_engine/clients/github_app.py, mergify_engine/debug.py, mergify_engine/exceptions.py, mergify_engine/tasks/engine/__init__.py, mergify_engine/tasks/engine/commands_runner.py, mergify_engine/tasks/github_events.py, mergify_engine/tasks/mergify_events.py, mergify_engine/web.py
Fixes: MERGIFY-ENGINE-1BR
Fixes: MERGIFY-ENGINE-1B4
Fixes: MERGIFY-ENGINE-1B6
Fixes: MERGIFY-ENGINE-1B3
Fixes: MERGIFY-ENGINE-183
=> feat: better handling of event coming from uninstalled Mergify

mergify_engine/branch_updater.py
=> fix: fixup catch message when git loss connection

mergify_engine/tasks/engine/__init__.py, mergify_engine/tests/unit/check_run_event_from_forked_repo.json, mergify_engine/tests/unit/check_run_event_from_same_repo.json, mergify_engine/tests/unit/test_event_to_pull.py
This remove usage of check_suite in get_github_pull_from_event()
This also add a test.
=> chore: remove usage of check_suite

datadog/conf.d/redisdb.yaml
We don't use it anymore for now
=> fix(datadog): disable HTTPCACHE temporary

mergify_engine/debug.py
=> fix(debug): do not try to compute the rules if there's no config

requirements.txt, setup.cfg
=> fix: add jwt requirement

requirements.txt, setup.cfg
=> fix: add pyjwt requirement

mergify_engine/branch_updater.py
=> fix(branch-update): use correct error message location

Procfile, mergify_engine/actions/merge/action.py, mergify_engine/actions/merge/queue.py, mergify_engine/branch_updater.py, mergify_engine/clients/github_app.py, mergify_engine/duplicate_pull.py, mergify_engine/sub_utils.py, mergify_engine/tasks/engine/__init__.py, mergify_engine/tasks/engine/actions_runner.py, mergify_engine/web.py
We dn't care about the accesslog, we already have the heroku logger for
this
=> Pull request for rework-log

mergify_engine/tasks/engine/actions_runner.py
This consumes too many HTTP calls just to put a PR number in a user
message.
This changes the heuristic to detect such case and remove the pull
request number from the message.
=> feat: don't find the number of the parent pr

mergify_engine/branch_updater.py, mergify_engine/duplicate_pull.py, mergify_engine/tests/functional/base.py, mergify_engine/utils.py, mergify_engine/worker.py
=> feat: use ctxt logger for Gitter

mergify_engine/tests/bridge.py, mergify_engine/utils.py
=> Pull request for fastapi

mergify_engine/exceptions.py
This has been removed as part of 7b5879118c103f6ae57551594c769ea46cd704e9 but
requests is still used to getting subs from the dashboard.
Fixes MERGIFY-ENGINE-1CW
=> fix: revert retry on requests.HTTPError

requirements.txt, setup.cfg
This is not needed for running the app.
=> chore: remove ipython

mergify_engine/context.py
=> fix(context): dont fail on deleting never cached property

mergify_engine/sub_utils.py
The migration to httpx missed that.
Fixes MERGIFY-ENGINE-1E1
=> fix(sub): handle 404 error correctly

mergify_engine/context.py, mergify_engine/tests/unit/test_context.py
=> fix(context): get the right PR title when the first line is empty

doc/source/actions.rst
That's what is interesting and have the longer text.
=> docs: more width for explanation column

doc/source/actions.rst
=> Pull request for doc-use-list

mergify_engine/tests/unit/test_web_cli.py, mergify_engine/web_cli.py
=> fix(web_cli): fix import

doc/source/conditions.rst, mergify_engine/context.py, mergify_engine/rules/parser.py, mergify_engine/tests/functional/test_attributes.py, mergify_engine/tests/unit/rules/test_parser.py
This adds the PR number in the list of exposed attributes.
=> feat(conditions): allow to use PR number as an attributes

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
When retrying finally works, we must cleanup the attempts hash key.
=> fix: cleanup attempts hash correctly

mergify_engine/utils.py, mergify_engine/worker.py
=> feat: more worker logging

mergify_engine/worker.py
This reverts commit 951767d94d837d8db451fb80abdee0709b39de04.
=> Revert "feat: add timeout when engine run"

mergify_engine/sub_utils.py
=> fix: handle subscription retreival error correctly

mergify_engine/actions/merge/helpers.py, mergify_engine/actions/rebase.py, mergify_engine/branch_updater.py, mergify_engine/debug.py, mergify_engine/engine/__init__.py, mergify_engine/sub_utils.py, mergify_engine/tasks/github_events.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/functional/test_attributes.py, mergify_engine/tests/functional/test_engine.py, mergify_engine/utils.py
This reverts commit 3cc22b66f178f10b32610f2dd3c842de846cbd0f.
=> revert: "feat(sub): make subscription retrieval asynchronous"

mergify_engine/tasks/github_events.py
=> fix: installation can be None in logging

mergify_engine/exceptions.py, mergify_engine/worker.py
=> fix: ignore error we have no access to the expected resource

mergify_engine/branch_updater.py, mergify_engine/clients/github.py, mergify_engine/clients/github_app.py, mergify_engine/config.py, mergify_engine/debug.py, mergify_engine/duplicate_pull.py, mergify_engine/tests/functional/__init__.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/test_clients.py, mergify_engine/utils.py, setup.cfg
This also changes GITHUB_DOMAIN to GITHUB_URL and GITHUB_API_URL to
clients testable with unit tests
=> feat: always raise RateLimit if the 401 is due to rate limit

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
This refactor the code to create only thread per worker instead of one
thread for each engine run.
=> feat: create only one thread per worker

runtime.txt
Reverts Mergifyio/mergify-engine#1028
=> revert: "feat: upgrade to python 3.7.7"

mergify_engine/logs.py
I dunno if that our memory leak, but that a memory leak, so fix it.
=> fix: use weakref to store the list of logger

mergify_engine/worker.py
=> fix: don't run engine if pull request return 404

mergify_engine/github_events.py
=> fix: ensure base/repo is present for checks

mergify_engine/github_events.py
=> fix: check repository/installation first

mergify_engine/context.py
=> fix: review user can be None

mergify_engine/exceptions.py
=> fix: ignore 404 on /pulls

mergify_engine/actions/merge/action.py, mergify_engine/actions/merge/helpers.py, mergify_engine/actions/merge/queue.py, mergify_engine/tasks/__init__.py
=> Refactor merge queue code

mergify_engine/clients/github.py
This reverts commit 8688c68ee6f780065abd2c7c4ec2c9c067ad6830.
=> revert: "chore: log request url"

mergify_engine/worker.py
=> fix: clean the queue when mergify have been uninstalled

mergify_engine/worker.py
=> feat: monitoring the new engine latency

mergify_engine/config.py, mergify_engine/worker.py
=> more monitoring

mergify_engine/github_events.py, mergify_engine/worker.py
=> fix: ignore 404 if repo doesn't exists

mergify_engine/worker.py
=> fix: don't proceed PR does not exists

mergify_engine/tests/functional/test_engine.py
This change all self.assertXXX from test_engine.py
=> chore: remove some python deprecation

mergify_engine/clients/http.py, mergify_engine/tests/functional/__init__.py, mergify_engine/tests/unit/test_clients.py
=> feat: handle AsyncClient retries

mergify_engine/clients/http.py, mergify_engine/tests/functional/__init__.py, mergify_engine/tests/unit/test_clients.py
Reverts Mergifyio/mergify-engine#1115
=> Revert "feat: handle AsyncClient retries"

mergify_engine/exceptions.py
=> fix: ignore some 422 error

mergify_engine/clients/http.py, mergify_engine/tests/functional/base.py
Fixes MERGIFY-ENGINE-1M4 MERGIFY-ENGINE-1M5
=> fix: use urllib3 only in tests

mergify_engine/web.py
We now push GitHub events on the fly rather than moving it to the background
which uses a lot of memory.
We instead do that asynchronously with a quite short timeout. We can afford
losing those events if the dashboard is down.
This is also safer as if the dashboard was responsive, the current workflow
would push tons of event in the background queue with a maximum cap.
=> refactor: push GitHub events on the fly

mergify_engine/actions/merge/queue.py
=> fix: set default strict merge method

mergify_engine/actions/merge/queue.py
Fixes MERGIFY-ENGINE-1MV MERGIFY-ENGINE-1MW
=> fix: set default strict merge method correctly

mergify_engine/tests/unit/rules/test_filter.py
This triggers a DeprecationWarning.
=> test: fix regexp format

doc/source/actions.rst, doc/source/commands.rst, doc/source/global-substitutions.rst, mergify_engine/actions/backport.py, mergify_engine/actions/copy.py, mergify_engine/actions/merge/action.py, mergify_engine/actions/rebase.py, mergify_engine/clients/github.py, mergify_engine/config.py, mergify_engine/tests/functional/base.py
This introduces Github Action mode by:
* Create a new auth mode
* Make some configuration optional if used with a Github Action
* Disable some non working feature
=> feat: github action mode

mergify_engine/worker.py
=> fix(worker): catch MergifyNotInstalled when getting PR

mergify_engine/worker.py
This will be handled by the caller, do not retry blindly on this one.
Fixes MERGIFY-ENGINE-1NW
=> fix(worker): propagate MergifyNotInstalled up

mergify_engine/clients/github.py
Fixes MERGIFY-ENGINE-1NY MERGIFY-ENGINE-1NZ
=> fix: handle /installation redirection

mergify_engine/worker.py
=> fix(worker): add missing get_client exception translation

mergify_engine/clients/github.py, mergify_engine/clients/http.py, mergify_engine/tests/unit/test_clients.py
Fixes MERGIFY-ENGINE-1P6, MERGIFY-ENGINE-1P5
=> fix: reraise authentication issue

mergify_engine/actions/merge/queue.py
This avoid logging error, for excepted thing to retry.
Fixes: MERGIFY-ENGINE-1P3, MERGIFY-ENGINE-1PF
=> fix: rework merge queue exception handling

mergify_engine/clients/github.py, mergify_engine/tests/unit/test_clients.py
=> fix: catch 404 earlier for /installation

mergify_engine/clients/github.py, mergify_engine/tests/unit/test_clients.py
=> fix: fix 301 handling on installation

mergify_engine/__init__.py, mergify_engine/actions/merge/queue.py, mergify_engine/asgi.py, mergify_engine/clients/github.py, mergify_engine/clients/github_app.py, mergify_engine/clients/http.py, mergify_engine/engine/__init__.py, mergify_engine/engine/commands_runner.py, mergify_engine/github_events.py, mergify_engine/logs.py, mergify_engine/sub_utils.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/utils.py, mergify_engine/worker.py
=> Pull request for fix-logging-issue

mergify_engine/sub_utils.py
=> fix: config attribute typo

mergify_engine/engine/__init__.py
We may received many synchronize in a row, we must at all of them to
find the Summary.
=> fix: looks at all synchronize events to find summary

mergify_engine/actions/merge/queue.py
=> fix: set default bot account

mergify_engine/branch_updater.py
=> fix(branch_updater): fix typo on pull number

mergify_engine/duplicate_pull.py
=> fix: catch more HTTP 500 during git operation

.github/FUNDING.yml
Let's use the one coming for the whole organization.
=> chore: remove FUNDING

mergify_engine/branch_updater.py
=> fix: correct case of bot login

mergify_engine/clients/github.py, mergify_engine/tests/functional/test_simulator.py, mergify_engine/web.py, mergify_engine/web/__init__.py, mergify_engine/web/auth.py, mergify_engine/web/badges.py, mergify_engine/web/config_validator.py, mergify_engine/web/simulator.py
=> feat: enable cors for simulator

mergify_engine/duplicate_pull.py
=> fix(duplicate_pull): handle branch deletion case

mergify_engine/rules/__init__.py
This reverts commit 3e6a73750cca429ca1a564d930405979c7ce417d.
=> Revert "fix: don't shallow unexpected jinja issue"

.mergify.yml
We don't want to active this for this month.
=> ci(mergify): disable dependabot auto merge

mergify_engine/engine/actions_runner.py, mergify_engine/tests/unit/test_duplicate.py, mergify_engine/utils.py, mergify_engine/worker.py
=> Pull request for chore

mergify_engine/actions/merge/helpers.py, mergify_engine/actions/rebase.py, mergify_engine/context.py
=> fix(rebase): avoid rebasing .github/workflows PR

mergify_engine/actions/rebase.py
=> fix(rebase): add missing conclusion

mergify_engine/actions/copy.py, mergify_engine/branch_updater.py, mergify_engine/clients/github.py, mergify_engine/clients/http.py, mergify_engine/exceptions.py, mergify_engine/github_events.py, mergify_engine/tests/functional/test_github_async_client.py, mergify_engine/tests/functional/test_github_client.py, mergify_engine/tests/unit/test_clients.py, mergify_engine/tests/unit/test_event_to_pull.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/web/auth.py, requirements.txt, setup.cfg
httpx have fixed their exception handling \o/
=> feat(http): upgrade httpx to 0.14

.mergify.yml
This reverts commit b701a83a3eff8d3afe38f92c7e7c73fd5ad36234.
=> revert: "ci(mergify): disable dependabot auto merge"

mergify_engine/branch_updater.py
=> fix(branch_updater): fix typo in Authentication class name

mergify_engine/branch_updater.py
=> fix(branch_updater): handle archived repository

mergify_engine/actions/merge/queue.py
=> fix(queue): add bot_account in default config

mergify_engine/tests/unit/test_worker.py
=> fix(engine): add a test for the stream processor after a ReadError

mergify_engine/actions/merge/action.py
=> fix: handle case or merge is still pending

runtime.txt
Reverts Mergifyio/mergify-engine#1374
=> Revert "chore: upgrade Python on Heroku"

mergify_engine/actions/merge/queue.py
The current code moves the PR from one queue to the same one, which does not do
anything.
=> fix(merge): _move_pull_to_new_base_branch actually move to a new branch

mergify_engine/actions/merge/queue.py
The config is now used instead.
=> chore(queue): remove old method cache key

mergify_engine/subscription.py
Fixes MERGIFY-ENGINE-1T4
Fixes MERGIFYIO-PG
=> fix(sub): allow to load subscription even without features

mergify_engine/engine/__init__.py, mergify_engine/github_events.py
=> fix: keep after/before attribute

mergify_engine/context.py, mergify_engine/debug.py, mergify_engine/subscription.py, mergify_engine/tests/unit/test_subscription.py
=> refactor(subscription): load features as Enum

mergify_engine/subscription.py
=> fix: feature are not yet in subscription payload

requirements.txt
Reverts Mergifyio/mergify-engine#1403
=> Revert "build: update h2/hpack/hyperframe"

mergify_engine/engine/__init__.py
=> fix: rename variable to avoid shadowing

mergify_engine/tests/conftest.py, mergify_engine/utils.py, mergify_engine/web/__init__.py
=> Pull request for aredis-idle-config

mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
=> fix(rules): don't crash on YAMLInvalid.path being None

mergify_engine/engine/commands_runner.py
=> feat: add commands logging

mergify_engine/clients/github.py
Github API report it during access_token call, not when we get the
installation
Fixes MERGIFY-ENGINE-1V5
Fixes MERGIFY-ENGINE-1V6
=> fix: move installation suspension check

mergify_engine/check_api.py
=> fix: conclusion can't be None

docs/source/_static/mergify.css, docs/source/_static/mergify.js, docs/source/_templates/layout.html, docs/source/conf.py
=> docs: use cleaner icon and style for permalink

mergify_engine/engine/actions_runner.py
=> fix: missing check_api.Result

docs/source/_static/mergify.css, docs/source/_templates/navigation.html
=> docs: expand left navbar

mergify_engine/engine/actions_runner.py
=> Pull request for log-run-action

mergify_engine/tests/conftest.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/utils.py, mergify_engine/web/__init__.py, mergify_engine/worker.py
This cancel aredis pending tasks instead of ignoring the logging.
=> test: cancel aredis pending tasks

mergify_engine/exceptions.py
=> fix: ignore 404 on branches

mergify_engine/github_events.py
=> fix: don't log useless error

mergify_engine/actions/merge/queue.py
=> chore(merge): remove unused code

docs/source/actions.rst, docs/source/badge.rst, docs/source/commands.rst, docs/source/conditions.rst, docs/source/configuration.rst, docs/source/examples.rst, docs/source/examples/bots.rst, docs/source/faq.rst, docs/source/getting-started.rst, docs/source/global-substitutions.rst, docs/source/index.rst, docs/source/merge-action.rst, tox.ini
=> docs: add meta tag description and keywords

docs/source/merge-action.rst
=> fix: a typo in doc

mergify_engine/context.py, mergify_engine/tests/unit/rules/test_rules.py
=> fix(template): some PR attributes are list

mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
=> feat: cache mergify config location

mergify_engine/worker.py
=> chore: improve readability

mergify_engine/exceptions.py
=> fix: do not retry some server error

mergify_engine/exceptions.py
The current exception handling was expecting exact message match, but
some error have some noise around.
So just check the payload contains the expected message.
=> fix: rework ignored exception handling

mergify_engine/actions/merge.py, mergify_engine/engine/__init__.py, mergify_engine/rules/__init__.py, mergify_engine/tests/unit/actions/test_merge.py, mergify_engine/tests/unit/rules/test_rules.py
This reorganize and add type to merge action.
=> refactor: reorganize the merge action

mergify_engine/exceptions.py
=> fix: archived repo should be ignored

mergify_engine/actions/dismiss_reviews.py, mergify_engine/actions/merge.py, mergify_engine/context.py
=> fix(merge): always cancel merge if PR is synchronized

mergify_engine/debug.py, mergify_engine/tests/functional/test_debug.py
=> fix(debug): do not always print no valid OAuth tokens

mergify_engine/actions/merge.py, mergify_engine/branch_updater.py, mergify_engine/context.py, mergify_engine/engine/commands_runner.py
=> chore(log): replace status= by status_code=

mergify_engine/actions/merge.py
Since we have removed the background queue task, we don't need that
anymore.
=> chore(merge): remove useless parameter of merge_report()

mergify_engine/engine/actions_runner.py
=> fix(merge): improve detection of the pull merged_by

mergify_engine/context.py, mergify_engine/engine/__init__.py
=> refactor(context): do not use installation id in summary sha

mergify_engine/subscription.py
Some part of the engine expect the token to be the full github dict, some
other place expect it to be the `access_token` string.
So depending on how the Subscription is created, we may cache the dict
instead of the string.
This updates from_dict() to handle both case. The dashboard will be
updated to return the access_token only.
And when the cache we not contain dict anymore, we will drop this
workaround.
=> fix: add support to new dashboard token format

mergify_engine/config.py, mergify_engine/exceptions.py, mergify_engine/worker.py
=> fix(exceptions): use timedelta for default values

mergify_engine/engine/actions_runner.py
Fixes MRGFY-211
Fixes MERGIFY-ENGINE-1XT
=> fix: reraise exception that need to be ignored or retried

mergify_engine/clients/github.py
=> fix: ignore 404 for /access_token

mergify_engine/worker.py
It's clearer to return an exception with this method, it makes
clearer the exception flow and mypy can understand it.
=> chore(worker): make translate_exception returns an exception

mergify_engine/worker.py
=> fix: handle IgnoredException when expand push/refresh events

mergify_engine/actions/merge_base.py, mergify_engine/queue.py
This change ensures we always pass context.Context to Queue API, instead
of just the pull request number.
=> refactor: simplify internal queue mechanism

mergify_engine/queue.py
This uses the return value of redis command to known if queue changed or
not.
=> chore: avoid using contextmanager to refresh queue

mergify_engine/worker.py
Ensure mypy check the layout of built OrderedDict()
=> chore: create type for Worker._extract_pulls_from_stream() return value

mergify_engine/engine/commands_runner.py, mergify_engine/github_events.py, mergify_engine/github_types.py
This removes case that can't happen anymore, add types and split the big
method.
=> refactor(command_runner): tidy code, adds types

mergify_engine/exceptions.py
=> fix: reduce retry backoff

mergify_engine/rules/filter.py
This simplifies the code a little bit.
=> refactor(rules/filter): remove unused ATTR_SEPARATOR

mergify_engine/github_events.py
This makes clear per event type what we keep.
=> Pull request for detailled-event-filter

mergify_engine/github_events.py, mergify_engine/tests/unit/test_forwards.py, mergify_engine/web/__init__.py
This sounds like a leftover of Celery.
=> chore: remove job_ from job_filter_and_dispatch

mergify_engine/github_events.py
get_ignore_reason() should only be used to filter events before pushing them to
the engine worker, not for the rest.
=> refactor(events): handle events before ignoring them

mergify_engine/github_events.py
Reverts Mergifyio/mergify-engine#1686
=> Revert "fix(github_events): also send initial summary on synchronize events"

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
Don't wait for the engine thread to finish after 25 seconds
=> feat: faster shutdown

mergify_engine/actions/close.py, mergify_engine/engine/__init__.py, mergify_engine/github_events.py, mergify_engine/github_types.py, setup.cfg
This catches a few bugs and and more strict checks.
=> fix(mypy): enable warn_redundant_casts and strict_equality

mergify_engine/github_events.py
=> fix(github_events): clear cache correctly for organization event

mergify_engine/github_events.py
=> fix(github_events): use right event key name

mergify_engine/actions/copy.py, mergify_engine/context.py, mergify_engine/debug.py, mergify_engine/github_types.py
=> fix(github_types): add GitHubBranch types

mergify_engine/github_events.py, mergify_engine/github_types.py, mergify_engine/tests/unit/events/team.enterprise.json, mergify_engine/tests/unit/test_github_events.py
Thanks GitHub for the wrong documentation. :'(
Fixes MERGIFY-ENGINE-1ZG
=> fix(github_events): handle team event for entreprise

mergify_engine/worker.py
=> fix: retry worker.push() on redis issue

mergify_engine/web/__init__.py
=> fix(web): forward ratelimit to dashboard

docs/source/_templates/layout.html
=> Fix font awesome and bootstrap upgrade

mergify_engine/engine/__init__.py, mergify_engine/utils.py
The former does not raise the Exception but returns it.
=> fix: replace async_run_one by asyncio.run

tox.ini
=> chore(flake8): ignore B902

mergify_engine/engine/actions_runner.py
=> fix: fix up retry when posting action check-run

mergify_engine/context.py
=> chore: PullRequestContext to PullRequestJinjaContext

mergify_engine/clients/github.py, mergify_engine/config.py, mergify_engine/debug.py, mergify_engine/engine/__init__.py, mergify_engine/github_types.py, mergify_engine/rules/__init__.py, mergify_engine/rules/types.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_clients.py, mergify_engine/tests/unit/test_context.py, mergify_engine/tests/unit/test_synchronize.py, mergify_engine/web/__init__.py, mergify_engine/worker.py
=> refactor(rules): make config retrieval async

.github/workflows/ci.yaml
Workaround for https://github.com/actions/checkout/issues/299
=> test: checkout correct right ref

.github/workflows/ci.yaml
This reverts commit fb1a462f485980a076b941059429e97a97e1a024.
=> revert: test: checkout correct right ref

mergify_engine/rules/parser.py, mergify_engine/tests/unit/rules/test_parser.py
Fixes MERGIFY-ENGINE-202
Fixes MERGIFY-ENGINE-201
=> fix: don't allow to count boolean value

mergify_engine/github_events.py, mergify_engine/queue.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
=> feat: add owner id to stream name

mergify_engine/actions/merge_base.py
=> feat: log when the legacy bot_account is used

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
=> feat: only get subscription once per stream

mergify_engine/worker.py
installation may not yet exists at this point
=> fix(worker): logging should use owner_login

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
=> fix: translate exception of subscription retrieval

mergify_engine/context.py
It parses the template twice, but that worses it to make the template
rendering async later.
=> refactor: drop our custom PullRequestJinjaContext

mergify_engine/check_api.py
=> fix: add missing stale conclusion

mergify_engine/worker.py
aredis quietly drops connection without closing them when the asyncio loop change.
until we can drop the engine thread we must not change the redis client
between the main thread and the engine thread.
This adds a temporary workaroung for that.
Fixes MERGIFY-ENGINE-20R MERGIFY-ENGINE-20P
=> fix: redis connection leaks

mergify_engine/actions/copy.py
=> fix: avoid copying PR with github workflow inside

mergify_engine/queue.py
This ensures we always have the config when a pull is in queue.
And we don't have config left behind with a pull is removed from the
queue.
Fixes MRGFY-71
=> fix: add/remove pull and config to/from queue in a transaction

mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
Everything except logging is async now.
=> chore: drop the engine thread

mergify_engine/actions/merge_base.py
=> fix: handle forbidden squash/rebase/merge commits

mergify_engine/web_cli.py
=> fix: make cli tools async

mergify_engine/branch_updater.py
=> fix(branch_updater): wrong upstream name

docs/source/actions.rst
=> docs(rebase action): rename update_bot_account option

mergify_engine/actions/queue.py, mergify_engine/subscription.py
Fixes MRGFY-272
Fixes MERGIFY-ENGINE-219
=> feat: add feature flag on queue action

mergify_engine/actions/label.py, mergify_engine/worker.py, tox.ini
=> ci: add bandit

mergify_engine/context.py, mergify_engine/debug.py, mergify_engine/engine/__init__.py, mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
=> Pull request for cache-config

mergify_engine/engine/__init__.py, mergify_engine/engine/actions_runner.py
=> fix: handle broken summary check content

mergify_engine/web/simulator.py
=> fix: fix the simulator simulated events

.mergify.yml
Do not request review if CI fails. It's not ready yet.
=> ci(mergify): update wording + request review on CI pass

docs/source/actions.rst, docs/source/examples.rst, docs/source/getting-started.rst
Adding example for update example it was not trivial to get it done, see my question #1872
=> docs: add example with update

.github/workflows/ci.yaml, docker-compose.yml, run-tests.sh, setup.cfg, tox.ini
=> ci: use docker-compose instead of pifpaf

mergify_engine/context.py, mergify_engine/github_events.py, mergify_engine/github_types.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_context.py
=> feat: cache team members

mergify_engine/github_events.py
=> fix: membership event without team slug

mergify_engine/clients/github.py, mergify_engine/worker.py
=> feat: adaptative requests logging

mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/test_worker.py, mergify_engine/worker.py
This just create one aredis client for cache.
=> chore: just use aredis connection pool

mergify_engine/engine/queue_runner.py, mergify_engine/github_types.py, mergify_engine/rules/types.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_duplicate.py, mergify_engine/tests/unit/test_engine.py, mergify_engine/tests/unit/test_synchronize.py, mergify_engine/tests/unit/test_train.py, mergify_engine/web/__init__.py
=> feat: add some sanity check on merge-queue pr

docs/source/configuration.rst, mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/web/simulator.py
I'm not sure of the way I'm doing this. So I need some advice on it.
=> feat(config): allow to add defaults options for actions

mergify_engine/tests/unit/test_simulator.py, mergify_engine/web/simulator.py
This returns the parsed pull request rules conditions with the
configuration validation to the dashboard.
=> feat(simulator): return parsed rule conditions

mergify_engine/crypto.py, requirements.txt
=> chore(deps): bump cryptography from 3.4.3 to 3.4.4

docs/source/examples/bots.rst
=> docs(dependabot): update + add example for major version bump only

mergify_engine/config.py
=> feat: allow to have only one redis

.github/workflows/ci.yaml, .github/workflows/docker.yaml, .gitignore, Dockerfile, entrypoint.sh, tox.ini
Initial step to be able to deploy the engine as docker image
Fixes MRGFY-12
=> feat: add docker configuration

mergify_engine/config.py, mergify_engine/subscription.py, mergify_engine/tests/unit/test_subscription.py
=> feat: allow to pass tokens via environments

mergify_engine/config.py, mergify_engine/utils.py
=> feat: allow to configure the ssl verification mode

mergify_engine/logs.py
This makes the message bold making easier to distinguish the message
from the extras.
=> test: enhance color output

mergify_engine/actions/comment.py, mergify_engine/actions/merge_base.py, mergify_engine/actions/review.py, mergify_engine/branch_updater.py, mergify_engine/context.py, mergify_engine/debug.py, mergify_engine/subscription.py, mergify_engine/tests/functional/actions/test_post_check.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/functional/test_engine.py, mergify_engine/tests/unit/actions/test_merge.py, mergify_engine/tests/unit/rules/test_rules.py, mergify_engine/tests/unit/test_context.py, mergify_engine/tests/unit/test_duplicate.py, mergify_engine/tests/unit/test_engine.py, mergify_engine/tests/unit/test_forwards.py, mergify_engine/tests/unit/test_subscription.py, mergify_engine/tests/unit/test_synchronize.py, mergify_engine/tests/unit/test_train.py, mergify_engine/tests/unit/test_user_tokens.py, mergify_engine/user_tokens.py, mergify_engine/web/__init__.py
=> feat: use new dashboard subscription endpoint

mergify_engine/gitter.py
=> fix(gitter): don't fail if init() fail

mergify_engine/queue/__init__.py
=> fix(debug): break circular dependency

mergify_engine/actions/copy.py, mergify_engine/duplicate_pull.py
=> fix(copy): be more explicit about some failures

mergify_engine/duplicate_pull.py
=> fix(duplicate): handle token expiration

mergify_engine/branch_updater.py
=> fix: a git error message is now lower case

mergify_engine/tests/unit/test_simulator.py, mergify_engine/web/simulator.py
=> fix(simulator): catch invalid json

mergify_engine/web/__init__.py
=> fix: just log warning when event forwarding fail

mergify_engine/web/__init__.py
=> fix: logging during event forward

mergify_engine/duplicate_pull.py
Fixes MERGIFY-ENGINE-239
Fixes MERGIFY-ENGINE-23S
=> fix: retry DuplicateNeedRetry silently

mergify_engine/logs.py
The goal is to distinguish during restart logs from old and new workers.
=> feat(logging): add Heroku release and commitid

mergify_engine/github_events.py
=> fix: don't answer on comment done on issues

mergify_engine/queue/merge_train.py, mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/web/root.py
=> feat: return train queues in queue API

mergify_engine/web/root.py, mergify_engine/worker.py
=> feat(metric): track aredis.ConnectionError

mergify_engine/worker.py
=> fix: add missing shutdown waiter

mergify_engine/branch_updater.py
=> fix(branch-updater): fix wording

mergify_engine/github_types.py, mergify_engine/queue/merge_train.py
=> fix: add support for skipped conclusion

mergify_engine/duplicate_pull.py
=> fix(duplicate): handle if base branch have been deleted

mergify_engine/actions/merge_base.py
=> fix: don't fail to retrieve branch protection if branch is gone

docs/source/examples.rst
=> docs(examples): fix approval = requested examples

mergify_engine/engine/__init__.py
=> fix: ignore error when posting initial summary

docs/source/configuration.rst
> Description here
Just fixing a typo
> Fix #1
=> fix the the typo

docs/source/_static/mergify.css
Sphinx now generates section item, not div with section classes.
=> docs: fix section

mergify_engine/clients/http.py
=> chore: improve the user-agent string

mergify_engine/context.py, mergify_engine/web/simulator.py
=> fix: use the correct owner_id in simulator

mergify_engine/actions/copy.py
=> fix(copy): allow to set branches in defaults

docs/source/conditions.rst
=> docs(conditions): fix some typos and reword some text for clarity

mergify_engine/actions/merge_base.py
=> chore: informs users about bot_account removal

mergify_engine/actions/copy.py
=> fix(copy): return an error if no branches are found

mergify_engine/actions/__init__.py, mergify_engine/actions/delete_head_branch.py, mergify_engine/actions/queue.py, mergify_engine/actions/update.py, mergify_engine/engine/commands_runner.py, mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
This makes defaults working with `Required` config key, like the queue
name.
=> fix: allow to set default for queue name

mergify_engine/queue/merge_train.py, mergify_engine/tests/unit/test_train.py
=> fix(queues): ensure pull are correctly removed from queue

mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
=> fix: pull_request_rules is now optional

tox.ini
Fixes MRGFY-398
> Description here
> Fix #xyz
=> docs(sphinx): use linkcheck

mergify_engine/clients/http.py, mergify_engine/config.py, mergify_engine/subscription.py, mergify_engine/tests/functional/actions/test_post_check.py, mergify_engine/tests/functional/base.py, mergify_engine/tests/unit/test_subscription.py, mergify_engine/web/root.py
=> feat: allow to get subscription on new endpoint

entrypoint.sh, installer/Procfile
* start aio mode by defaults
* listen on port 5000 for installer like the engine
=> fix(installer): change defaults

installer/src/App.jsx
This is needed to get logs in docker in a timely fashion
=> fix(installer): set PYTHONUNBUFFERED=1

mergify_engine/subscription.py
=> chore: track people that have installed GitHub App without registering

docs/source/actions/update.rst
This looks weird once rendered.
=> docs(update): remove block code

mergify_engine/branch_updater.py
If we have the author token pick it instead of a random one.
=> feat(rebase): pick the author token if possible

mergify_engine/engine/__init__.py
This represents 6% of useless info
=> chore: remove useless logs

docs/source/configuration.rst
The ssl certificate is expired and broke our CI.
=> fix(docs): remove pythex.org

.github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/docs.yaml, .mergify.yml, README.rst
=> ci: rename branch master to main

mergify_engine/tests/bridge.py, mergify_engine/tests/functional/base.py, mergify_engine/web_cli.py
data= is deprecated in favor of content=
=> chore(httpx): remove deprecation warning

mergify_engine/actions/merge.py, mergify_engine/actions/merge_base.py, mergify_engine/actions/queue.py, mergify_engine/signals.py, mergify_engine/tests/unit/test_signals.py, mergify_engine_signals/noop/__init__.py
=> feat(signal): improve tracking of queue/merge actions

mergify_engine/engine/actions_runner.py
action already returns a CheckResult now, we can drop the fallback.
=> chore(action_runner): remove dead code

mergify_engine/rules/types.py, mergify_engine/tests/unit/rules/test_types.py
=> fix: ensure jinja template are string

mergify_engine/worker.py
All messages in stream have repo id set now.
=> chore(worker): make repository id mandatory

mergify_engine/tests/unit/test_github_events.py
=> fix(tests): don't assume domain is github.com

mergify_engine/branch_updater.py
=> fix(branch-update): mark rebase conflict as failure

mergify_engine/rules/filter.py, mergify_engine/tests/unit/rules/test_filter.py
This will be used to implements and/or in conditions.
=> feat(filter): allow to chain Filter

docs/source/actions/queue.rst, mergify_engine/actions/queue.py, mergify_engine/rules/__init__.py
=> fix: limit number of queue with free plan

mergify_engine/actions/comment.py, mergify_engine/actions/merge.py, mergify_engine/actions/queue.py, mergify_engine/actions/utils.py, mergify_engine/github_types.py
=> fix(bot_account): allow admin to be used

mergify_engine/tests/unit/test_cache.py, mergify_engine/web/root.py
=> feat(web): add endpoint to cleanup user_tokens cache

mergify_engine/branch_updater.py
Fixes MRGFY-477
Change-Id: I4bb3ded0915256d61cac79dbc34b19c0bcb18897
Change-Id: I4a940386353bef4eb264d4c38727b22f8af66854
=> chore: log when we update base branch

.github/workflows/ci.yaml
Change-Id: Ia0ef5594bd129780d5d3058f58b6ac078185c4bd
=> ci(tests): run jobs on git_push_stack branches

docs/source/conditions.rst, mergify_engine/actions/merge.py, mergify_engine/actions/merge_base.py, mergify_engine/actions/queue.py, mergify_engine/context.py, mergify_engine/engine/queue_runner.py, mergify_engine/queue/merge_train.py, mergify_engine/rules/__init__.py, mergify_engine/tests/unit/rules/test_rules.py
Change-Id: I9f2df8ae19a41352a39446e2e114a60c1ce64292
=> feat(conditions): allow checks condition in and/or

mergify_engine/engine/__init__.py
We got twice a merge queue stuck, each time it was due to an outdated
loaded previous summary.
This change adds some logging to debug the issue.
Related MRGFY-485
Change-Id: Ia55f718646f93d8ebdc6002d50bdf6523ed1c391
=> chore: add logging to summary copier

docs/source/actions/merge.rst, docs/source/global-substitutions.rst
=> docs: deprecate strict mode

.github/workflows/docs-upload-gcp.yaml
Change-Id: I8e279e402831c1f36e7ae417c4bb391768e7101e
=> fix(ci): apt need to be root

mergify_engine/actions/merge_base.py
Change-Id: I5e65747c5515297532118cfea0766ba8fc0bb3da
=> chore: add logging to get_rule_checks_status()

mergify_engine/context.py, mergify_engine/tests/unit/actions/test_merge.py, mergify_engine/tests/unit/rules/test_rules.py
Change-Id: Ibeae85d3e4ecfb299ce8cd0c5466d13e2fe9aea9
=> feat(refactor): move branch protection checks earlier in the process

.github/workflows/docs-upload-gcp.yaml
Change-Id: I553ea5d3dc50f5c80cf048e78bf5951954c3c448
=> fix(ci): use status instead of check-runs to report the doc preview link

mergify_engine/actions/merge_base.py, mergify_engine/context.py, mergify_engine/tests/unit/actions/test_queue.py
When some CIs are pending and some success, get_rule_checks_status may
return FAILURE instead of PENDING
Change-Id: I9acb38f149b1174196d13bb5d5fe3c18f9ed5048
=> fix(queue): get_rule_checks_status return value

mergify_engine/rules/filter.py, tox.ini
Change-Id: I0e191d8b7331b32e4dbfc2ff9c7138aaf3cac57f
=> chore(deps): upgrade mypy>=0.901

mergify_engine/actions/merge_base.py
This reverts commit 39d0e6bc7a336ccc86a3f70f2a94fd77e2fd0ad1.
Change-Id: Idd17ba6271df99ec5fd2514eabf60a571a9723c2
=> revert: "chore: add logging to get_rule_checks_status()"

mergify_engine/logs.py, mergify_engine/worker.py
Change-Id: If9876d3dc39960f95c56f7b2a38b86b5e34c13ed
=> feat(logs): add worker id to log

mergify_engine/queue/merge_train.py
Fixes MRGFY-494
Change-Id: Ic9da82f3188056ea6460c32c540d10a6f978d142
=> fix(queue): add missing await

mergify_engine/rules/__init__.py
Change-Id: I72df57087959a8b9fce69f48158efb37ed0e0880
=> fix(mypy): handle new typing of yaml.MarkedYAMLError

docs/source/conditions.rst, mergify_engine/context.py, mergify_engine/date.py, mergify_engine/rules/filter.py, mergify_engine/rules/parser.py, mergify_engine/tests/unit/rules/test_filter.py, mergify_engine/tests/unit/rules/test_parser.py
Change-Id: Id6407aaff6e4ad76f55f7a12770a07dbd7cf6769
=> feat(conditions): add current-day/month/year/day-of-week conditions

mergify_engine/engine/queue_runner.py
Change-Id: I97cf6a2d00abebbd20e5fbdb4c73b5892cbb0e75
=> chore(merge-train): make log more readable

mergify_engine/engine/queue_runner.py
Change-Id: Ic5d773230e017b608ac0378b022533ae0c74399d
=> chore(merge-train): add queued pull request number to some logs

docs/source/conditions.rst, mergify_engine/date.py, mergify_engine/rules/filter.py, mergify_engine/rules/parser.py, mergify_engine/tests/unit/rules/test_filter.py, mergify_engine/tests/unit/rules/test_parser.py
Change-Id: Iac71bd17e89a93c2172dd9f93c62d4f1944678e7
=> feat(conditions): add support for named current-day-of-week

mergify_engine/engine/queue_runner.py
Change-Id: Id19a10fc1671a3cf891d2827f69da0653c223c05
=> chore(train): log Context.sources

mergify_engine/github_events.py
Change-Id: I45c1e24cc58f84222e8677108ba3fe5d6673017a
=> chore(events): log event content

mergify_engine/actions/merge_base.py
Change-Id: I83e1d71d39ff39c452805c371fcc8b83066144b6
=> chore(merge/queue): change confusing logging

mergify_engine/tests/unit/actions/test_queue.py
Change-Id: I1232d57009a97ef326f57ebfc50c6c48be02fcd9
=> chore(queue): add a couple of tests

mergify_engine/actions/review.py
Change-Id: I8b0df1a96a34ee02c1706ec8f649cc006348b591
=> fix(review): report configuration issue

docs/source/conditions.rst
Change-Id: Ib4ad50c361a3da647917922ee99053a288cdca12
=> chore(docs): time-based conditions are UTC

mergify_engine/check_api.py, mergify_engine/clients/http.py, mergify_engine/context.py, mergify_engine/date.py, mergify_engine/delayed_refresh.py, mergify_engine/engine/__init__.py, mergify_engine/queue/merge_train.py, mergify_engine/queue/naive.py, mergify_engine/rules/filter.py, mergify_engine/tests/functional/actions/test_queue.py, mergify_engine/tests/unit/rules/test_filter.py, mergify_engine/tests/unit/test_clients.py, mergify_engine/tests/unit/test_date.py, mergify_engine/tests/unit/test_utils.py, mergify_engine/utils.py, mergify_engine/worker.py
Change-Id: Ib8a84328cfe8c8041892997ec4b20ebdb2abd7c5
=> chore(date): move utcnow/pretty_timedelta to date module

docs/source/_static/mergify.css, docs/source/_static/mergify.js, docs/source/actions/backport.rst, docs/source/actions/merge.rst, docs/source/actions/queue.rst, docs/source/actions/rebase.rst, docs/source/conditions.rst, docs/source/configuration.rst, docs/source/getting-started.rst
Better colors and box designs.
=> docs: redesign admonition style

docs/package.json, docs/source/_static/mergify.css, docs/source/_static/mergify.js, docs/source/_templates/layout.html, docs/source/_templates/navbar.html, docs/source/global-substitutions.rst, docs/source/scss/custom.scss, docs/yarn.lock
=> docs: upgrade to Bootstrap 5

docs/source/_static/mergify.css, docs/source/_static/mergify.js, docs/source/_templates/layout.html
This makes sure emojis display in the same fashion everywhere.
=> docs: add twemoji support

.github/workflows/docs-upload-gcp.yaml
Change-Id: I7391354e1de2573168cefd02271d920408f1ee96
=> chore(ci): log the workflow info that generate the doc

.github/workflows/docs-upload-gcp.yaml
Change-Id: I590675294628441624bf0ceff8c6621b5f51bcdb
=> chore(ci): log the event info that generate the doc

mergify_engine/web_cli.py
Fixes MERGIFY-ENGINE-27F
Change-Id: I7c650fce2a77d7d77e182a85a3049819f3a13b8a
=> fix: ensure owner_id is a int in queue viewer cli

mergify_engine/engine/__init__.py
We known why some summary was badly copied (sha1 collision).
We can remove this logs, now.
Change-Id: I2aba991f0ada6c5d94d5d53fd1c8c5bca4380d25
=> chore(logs): change some log level

setup.cfg, tox.ini
Change-Id: I44e55e7910d29ebab450b6808289868076ea9eed
=> feat(tests): add pytest-timeout

mergify_engine/actions/queue.py, mergify_engine/date.py, mergify_engine/delayed_refresh.py, mergify_engine/engine/actions_runner.py, mergify_engine/engine/queue_runner.py
=> fix: compute delayed refresh date for queue_rules

mergify_engine/exceptions.py
=> fix(exceptions): ignore per_page arg

mergify_engine/context.py
Remove some attributes from __repr__ output.
=> feat(context): less verbose __repr__

mergify_engine/branch_updater.py, mergify_engine/context.py
=> fix(branch-update): handle deleted head repository
